>P1;SASP_Homo_sapiens
VDSGAQV--SVVH--P---------NL-WE------------E-----VT
DG-----DLDTLQ---PFE-------------------------------
-----NV-VKV-A-NGAEM----KI-LG---------VWDTA-VSL----
----------GK-------------LKLKAQ-----------FL-VAN--
---AS-----------------------------------------AEEA
IIGTD-VL-QDHNAI--LDF
*
>P1;SASP_Pan_troglodytes
VDSGAQV--SVVH--P---------NL-WE------------E-----VT
DG-----DLDTLQ---PFE-------------------------------
-----NV-VKV-A-NGAEM----KI-LG---------VWDTA-VSL----
----------GK-------------LKLKAQ-----------FL-VAN--
---AS-----------------------------------------AEEA
IIGTD-VL-QDHNAI--LDF
*
>P1;SASP_Bos_taurus
VDSGAQV--SVVH--P---------SL-WE------------E-----VT
DG-----ELDTLR---PFE-------------------------------
-----NV-VKV-A-NGAEM----KI-LG---------VWDTV-VSL----
----------GK-------------LKLKAA-----------FL-VAN--
---AS-----------------------------------------AEEA
IIGTD-VL-QDHNAV--LDF
*
>P1;SASP_Mus_musculus
VDSGAQV--SVVH--P---------AL-WE------------E-----VT
DG-----DLDTLR---PFN-------------------------------
-----NV-VKV-A-NGAEM----KI-LG---------VWDTE-ISL----
----------GK-------------TKLKAE-----------FL-VAN--
---AS-----------------------------------------AEEA
IIGTD-VL-QDHNAV--LDF
*
>P1;SASP_Canis_familiaris
VDSGAQV--SVVH--P---------SL-WE------------E-----VT
DG-----DLDTLR---PFE-------------------------------
-----NV-VKV-A-NGAEM----KI-LG---------IWDTV-VSL----
----------GK-------------LKLKAE-----------FL-VAN--
---AS-----------------------------------------AEEA
IIGTD-VL-QDHNAV--LDF
*
>P1;SASP_Monodelphis_domestica
VDSGAQV--SVVS--P---------DL-WE------------Q-----AT
DG-----DVDTLR---PFE-------------------------------
-----NV-VKV-A-NGAEM----KI-LG---------IWDTK-VTL----
----------GK-------------FEMEAE-----------FL-VAN--
---AS-----------------------------------------TEEA
IIGTD-VL-QDHGAI--LDF
*
>P1;Athila4-1
CDLGASV--SLM---P-LS-------V-AK------------R------L
-G-----FTQYK----SCN-------------------------------
------ISLIL-A-DR-SV----RIPHG-L-------LENLP-IRI----
----------GAV-------------EIPTD-----------FV-VLEM-
---DEEP---------------------------------------KDPL
ILGRH-FLATAGAM---IDV
*
>P1;Diaspora
LDLGASV--SVM---P-LS-------I-FN------------SLS----L
-G-----PLQ------STD-------------------------------
------VVIHL-A-NR-SV----AYPVG-F-------IEDVL-VRV----
----------GEL-------------IFPVD-----------FY-ILNME
DG-FSQG---------------------------------------SVPI
ILGRP-FMKTARTK---IDV
*
>P1;BAB61168.1
CDLGASV--SVM---P-KN-------V-FD------------K------L
-N-----FTVLA----PTP-------------------------------
------MRLQL-A-DS-LV----RYPTG-I-------AEDML-VKI----
----------WDF-------------FIPVD-----------FV-VLDM-
---DNGK---------------------------------------ETPL
ILGRP-FLSTAGAN---IDV
*
>P1;Calypso4-1
IDLGASI--NLM---P-LS-------M-CR------------R------L
-G-----EIEIM----PTR-------------------------------
------MTLQL-V-DH-SI----TRPYG-V-------IEDML-IQV----
----------KQL-------------VFPVD-----------FV-VMDI-
---EEDP---------------------------------------DIPI
ILGRP-FM-SATNYI--VDI
*
>P1;Cyclops-2
IDLGSSI--NLI---P-LS-------I--K------------R------L
-G-----NIEIK----SIR-------------------------------
------MTLQL-A-DKSTL----TKTSW-A-------TP-GW-V-V----
----------DKF-------------FFPVD-----------FI-VIDM-
---EEDD---------------------------------------DAPL
ILGRP-FMKTARMM---IDV
*
>P1;VfCyclops2
INLGASV--SLM---P-LS-------I-YK------------K------L
-G-----IGNVQ----NTR-------------------------------
------MTLQF-A-DH-SV----KRPYG-I-------VEYVL-VKI----
----------DKF-------------VFLVD-----------FV-VLEM-
---PEDE---------------------------------------KITL
ILGRP-FLETERSL---IDI
*
>P1;Bagy-2
CDMGASV--SAI---P-RSL------YDEI------------KDE----I
AP------AELE----PID-------------------------------
------VTITL-A-NRDTI-----CPVI-VR-----DVEVL----C----
----------GKT-------------KYPTD-----------FL-VLAT-
---AQDS---------------------------------------FCPI
IFGRP-FLNTVNAH---IDC
*
>P1;Rigy-2
CDLGASV--SIM---L-KD-------V-FD------------K------L
-N-----FTVLA----PTP-------------------------------
------MRLQL-A-DS-SV----CYTAG-I-------EEDVP-VKI----
----------RDF-------------FILVD-----------FV-VLDM-
---DTGK---------------------------------------ETPL
ILGRP-FLSTAGAN---FDV
*
>P1;Calypso5-1
IDLGASI--NLM---T-LS-------M-CQ------------Q------L
-G-----EIEIM----PTR-------------------------------
------MTLQL-A-DR-SI----ARPYG-V-------IEDML-IQV----
----------KQL-------------VFPCN-----------FV-VMDI-
---EEDP---------------------------------------DIPI
ILGRP-FMSTTSCV---VDM
*
>P1;DDIHum
VDSGAQM--TIMS------------QACAE------------R------C
-N-----IMRLVD-------------------------------------
------RRWAGIA-KGVG-T--QKI-IGRV-------H--LAQVQI----
---------EGD--------------FL-PCS----------FS-ILE--
---EQ-----------------------------------------PMDM
LLGLD-ML-KRHQCS--IDL
*
>P1;DDIXen
VDSGAQM--TIMS------------QACAE------------R------C
-H-----IMRLVD-------------------------------------
------RRWAGIA-KGVG-T--QKI-IGRV-------H--LAQVQI----
---------EGD--------------FL-PCS----------FS-ILE--
---EQ-----------------------------------------PMDM
LLGLD-ML-KRHQCS--IDL
*
>P1;DDIDan
VDSGAQM--TIMS------------QACAE------------R------C
-N-----IMRLVD-------------------------------------
------RRWAGIA-KGVG-T--QKI-IGRV-------H--LAQVQI----
---------EGD--------------FL-PCS----------FS-ILE--
---DQ-----------------------------------------PMDM
LLGLD-ML-KRHQCS--IDL
*
>P1;DDIMfas
VDSGAQM--TIMS------------QACAE------------R------C
-N-----IMRLVD-------------------------------------
------RRWAGVA-KGVG-T--QRI-IGRV-------H--LAQIQI----
---------EGD--------------FL-QCS----------FS-ILE--
---DQ-----------------------------------------PMDM
LLGLD-ML-RRHQCS--IDL
*
>P1;DDIMmus
VDSGAQM--TIMS------------QACAE------------R------C
-N-----IMRLVD-------------------------------------
------RRWGGVA-KGVG-T--QRI-MGRV-------H--LAQIQI----
---------EGD--------------FL-QCS----------FS-ILE--
---EQ-----------------------------------------PMDI
LLGLD-ML-RRHQCS--IDL
*
>P1;DDIan
IDSGAQA--TIMS------------AAAAE------------R------C
-N-----IMRLVD-------------------------------------
------TRWAGIA-KGVG-V--QRI-IGRI-------H--MVQIQI----
---------EKD--------------FL-TSS----------FS-VLE--
---EQ-----------------------------------------PMDM
LLGLD-ML-KRHQCN--IDL
*
>P1;DDIDro
VDSGAQT--TIMS------------KDCAE------------R------C
-H-----VNRLID-------------------------------------
------TRWNGVA-KGVG-T--QPI-LGRI-------H--MVQLQI----
---------END--------------HL-TSS----------FT-VLG--
---QQ-----------------------------------------PMDM
LLGLD-ML-KRHQCL--IDL
*
>P1;DDIAra
VDSGAQS--TIIS------------KSCAE------------R------C
-G-----LLRLMD-------------------------------------
------QRYKGIA-HGVG-Q--TEI-LGRI-------H--VAPIKI----
----------GNN-------------FY-PCS----------FV-VLD--
---SP-----------------------------------------NMEF
LFGLD-ML-RKHQCT--IDL
*
>P1;DDILei
VDSGAQN--SIMN------------KRTAE------------R------C
-G-----LMRLVD-------------------------------------
------VRMRGVA-VGVG-R--QEI-CGRI-------H--MTPVNL----
----------AGM-------------YI-PFA----------FY-VIE--
---DQ-----------------------------------------AMDL
IIGLD-QL-KRHQMM--IDL
*
>P1;DDICer
IDSGAQK--SIMS------------MACAE------------R------C
-G-----LNGLID-------------------------------------
------RRFQSMA-RGVG-G-TEKI-EGKI-------H--LCDVKV----
----------EDA-------------HF-SCP----------FE-VMA--
---RR-----------------------------------------EMDL
LIGLN-VL-RKHGCC--INL
*
>P1;DDIMgri
VDSGAQV--TIMS------------PACAE------------A------C
-G-----IMRLVD-------------------------------------
------TRFSGIA-RGVG-T--ANI-IGRV-------H--TAPIKI----
----------GSL-------------HL-PCS----------FT-VME--
---GK-----------------------------------------AVDL
LLGID-ML-KRYQAC--IDL
*
>P1;DDIGzea
VDSGAQA--TIMS------------PSCAE------------A------C
-G-----IMRLVD-------------------------------------
------TRFAGVA-RGVG-T--ANI-IGRV-------H--SAQIKI----
----------GNL-------------FL-PCS----------FT-VME--
---GK-----------------------------------------SVDL
LLGLD-ML-KRYQAT--IDL
*
>P1;DDINcra
VDSGAQA--TIMS------------PDIAE------------A------C
-G-----IMRLVD-------------------------------------
------KRYGGIA-KGVG-T--AKI-IGRV-------H--TAPVKI----
----------GSL-------------FL-PCS----------FT-VME--
---GK-----------------------------------------NVDM
LLGLD-ML-KRYQAC--IDL
*
>P1;DDIAni
VDSGAQV--TIMS------------PDCAT------------A------C
-N-----IMRLVD-------------------------------------
------SRYGGIA-KGVG-T--ANI-LGRV-------H--SAQIKI----
----------GDM-------------FL-PCS----------FT-VME--
---GK-----------------------------------------HIDL
LLGLD-ML-RRHQAC--IDL
*
>P1;DDISpom
VDSGAQA--TILS------------ADCAE------------K------C
-G-----LTRLLD-------------------------------------
------TRFQGVA-KGVG-M--AKI-LGCV-------H--SAPLKI----
----------GDL-------------YL-PCR----------FT-VIE--
---GR-----------------------------------------DVDM
LLGLD-ML-RRYQAC--IDL
*
>P1;DDIPfal
VDSGAQS--SIMS------------KKCAQ------------K------C
-N-----ILRLMD-------------------------------------
------KRFTGIA-KGVG-T--KTI-LGKI-------H--MIDIKI----
----------GNY-------------FY-AVS----------LT-IIE--
---DY-----------------------------------------DIDF
IFGLD-LL-KRHQCL--IDF
*
>P1;DDIPyoe
VDSGAQT--SIIS------------KRCAE------------K------C
-N-----ILRLMD-------------------------------------
------TRFTGIA-KGVG-T--KSI-LGKI-------H--MIDIKI----
----------GNY-------------FY-AVA----------LT-IID--
---DY-----------------------------------------DIDF
IFGLD-LL-KRHQCS--IDL
*
>P1;DDIRnor
VDSGAQM--TIMS------------QACAE------------R------C
-N-----IMRLVD-------------------------------------
------RRWAGIA-KGVG-T--QKI-IGRV-------H--LAQVQI----
---------EGD--------------FL-ACS----------FS-ILE--
---EQ-----------------------------------------PMDM
LLGLD-ML-KRHQCS--IDL
*
>P1;DDIGlam
IDTGAEF--STIS------------LETAI------------R------C
-G-----LEDHID-------------------------------------
------KRQEGKA-LGIGS---SKI-VGKI-------H--LVQLKY----
----------GDEY------------F--ATN----------FM-VVE--
---NV-----------------------------------------VGT-
LLGMP-FL-RMHRMV--IDL
*
>P1;DDICbri
VDTGAQL--SIIT------------RSVAE------------K------C
-G-----IFQKLD-------------------------------------
------SRFQVDA-QGIGGV--SQA-LGKI-------L--DVELEF----
---------SGY--------------FL-PVV----------LA-VFE--
---ECSL---------------------------------------GCVL
IIGVD-IL-TAYCAN--VDF
*
>P1;NIXm
VDTGTQH--NQIS------------AGCLR------------R------L
-G------L-GK--------------------------------------
------RVPKAPG--GDVAP----E-PPT---------Q-VEQLELEL--
----------GQE-------------TV-ACS----------AQ-VVD--
---VD-----------------------------------------SPEF
CLGLQTLL-SLK-CC--IDL
*
>P1;NIXh
VDTGTQY--NRIS------------AGCLS------------R------L
-G------L-EK--------------------------------------
------RVLKASA--GDLAP----G-PPT---------Q-VEQLELQL--
----------GQE-------------TV-VCS----------AQ-VVD--
---AE-----------------------------------------SPEF
CLGLQTLL-SLK-CC--IDL
*
>P1;NIXMm
VDTGCQY--NLIS------------SACVD------------R------L
-G------LKDH--------------------------------------
------VKSHKHE--GEKLS----L-PRHL-------KV-VGQIEHLMIT
---------VGSL-------------RL-DCQ----------AA-VVD--
---DN-----------------------------------------EKSL
SLGLQTLR-SLK-CI--INL
*
>P1;NIXrn
VDTGCQH--NLIS------------SACVD------------R------L
-G------LRDH--------------------------------------
------VKSHKHE--GEKLS----L-PRHL-------KV-VGQIEHLLIT
---------VGSL-------------RL-DCP----------AA-VVD--
---DN-----------------------------------------EKSL
SLGLQTLR-SLK-CI--INL
*
>P1;NIX3
VDTGCLY--NLIS------------LACVD------------R------L
-G------LKEH--------------------------------------
------VKSHKHE--GEKLS----L-PRHL-------KV-VGQIEHLVIT
---------LGSL-------------RL-DCP----------AA-VVD--
---DN-----------------------------------------EKNL
SLGLQTLR-SLK-CI--INL
*
>P1;BLL3736
IDTGAT---SVV---L-TW-------ETAK------------A------I
-G-----LPLEM----LE-YD-----------------------------
------VDLET-A-GGHTK-----A-ARL---------T-LDRLAV----
----------GH--------------LV-EKSVP--------A--LVV--
---QRGQ---------------------------------------MKTN
LLGMS-FL--DRLES--WGV
*
>P1;ATU1893
VDTGAS---SVV---L-AN-------ADAA------------E------I
-G-----IDTGS----LR-YT-----------------------------
------VPVMT-A-NGRTA-----A-APV---------T-LSEIGI----
----------GP--------------IM-RRNIP--------A-LVAQ--
----DGQ---------------------------------------LGQS
LLGMS-FL--STLGS--LQM
*
>P1;CC1307
VDTGAT---AVS---L-SL-------ADAQ------------R------L
-G-----IDTSR----LT-YD-----------------------------
------YNVIT-A-DGRTR-----A-AAV---------K-LASVSI----
---------AGA---------------R-VRDVD--------A-LVIE--
-----KG---------------------------------------LENS
LLGMS-YL--GRLSR--FEA
*
>P1;MLR0565
VDTGAT---STV---L-TS-------EDAQ------------A------A
-G-----FNPAA----LN-YT-----------------------------
------IPVST-A-NGMAR-----A-AAV---------K-TDAVAI----
----------GG--------------IV-RKDM---------P-VMVA--
---APGM---------------------------------------LSQS
LLGMN-FI--GSLSG--FDV
*
>P1;RC1339
VDTGAS---DIA---L-TK-------EDAQ------------K------L
-G-----FDLTK----LK-YT-----------------------------
------RTYLT-A-NGENK-----A-API---------T-LNSVVI----
----------G---------------KE-FKNIK--------G-HVGL--
-----GD---------------------------------------LDIS
LLGMS-LL--ERFKG--FRI
*
>P1;MMC12119
VDTGAS---AIV---L-AP-------QVLS------------R------L
-G-----LDRRK----LR-FT-----------------------------
------QPFQT-A-NGQVF-----N-APV---------I-LQDVQL----
----------GD--------------LH-LQRVP--------A--VVN--
----QTA---------------------------------------MDNS
LLGMS-FF--KRLKS--YRV
*
>P1;Rsph03003184
ADTGAS---SIV---L-SQ-------ADAR------------R------L
-G-----IEPDR----LD-YM-----------------------------
------GEAIT-A-NGPVR-----T-ARV---------R-IGPVVL----
----------GP--------------YS-EQRIP--------A--WVN--
----EGP---------------------------------------MDMS
LLGMD-YL--RRFRI--EIA
*
>P1;RP867
VDTGAS---DIA---L-TK-------EDAQ------------K------L
-G-----FDLNK----LK-YT-----------------------------
------RTYLT-A-NGENK-----A-API---------I-LNSVVI----
----------GT---------------E-FKNIK--------G-HVGL--
-----GN---------------------------------------LDIS
LLGMS-LL--ERFKG--FRI
*
>P1;PA4048
VDTGAT---SIA---M-NE-------NEAR------------R------L
-G-----IDYRVD---GK-P------------------------------
------MVAST-A-SGTSR-----G-WRV---------T-LDRVKI----
----------GG--------------IE-LLGVE--------A--AVI--
---EGGY---------------------------------------PTEA
LLGMS-FL--NRVR---WRE
*
>P1;MDEG2586
VDTGAS---SIA---L-NS-------IVAK------------Q------L
-G-----IDYLTS---PR-Y------------------------------
------VGVAT-A-SGTTR-----G-YRV---------T-LREVTV----
----------GG--------------IT-LNNVI--------A--VVT--
---EGEF---------------------------------------PRDI
LLGNT-FL--SELD---MKV
*
>P1;PSPTO4961
IDTGAT---DVA---I-PG-------DMAD------------S------L
-G-----LKR------G--LP-----------------------------
------VTVST-A-NGNSQ-----G-FRT---------T-LDRLQL----
----------GD--------------IV-LHNVR--------A--LVA--
---PGLE---------------------------------------GEQV
LLGMS-AL--KQLE---FTQ
*
>P1;Pflu02000192
LDTGAT---DVA---I-PA-------EVAK------------N------L
-R-----LEE------G--FG-----------------------------
------VTLST-A-NGLSQ-----G-YRT---------R-IDRLQL----
----------GD--------------IV-LRDVR--------A--LVA--
---PGLH---------------------------------------GDQV
LLGMS-AL--NKLE---FTQ
*
>P1;PA4965
LDTGAT---QVA---V-PE-------ALAA------------R------L
-A-----LER------G--AP-----------------------------
------ITLST-A-NGRAT-----G-WRT---------R-LDQLQL----
----------GD--------------IR-LSGVA--------A--LIA--
---PGMD---------------------------------------GDEV
LLGMS-AL--KQLE---FTQ
*
>P1;Mdeg0200624
LDTGAT---DVA---I-PS-------ALAK------------K------L
-G-----LKR------G--AK-----------------------------
------GAAHT-A-NGVTT-----T-YRT---------N-IDVLKL----
----------GS--------------IT-LYDVD--------A--SIT--
---MGFT---------------------------------------GDEI
LLGMS-AL--KSVE---FTH
*
>P1;ATU0134
VDTGAS---MVA---I-NE-------TMAR------------R------L
-G-----YGVN-----SLDFK-----------------------------
------YAIST-A-NGQTL-----A-AHV---------K-LDRVEI----
----------GA--------------IR-VQNVD--------T--MVL--
---KDNA---------------------------------------LSNM
LVGMS-FL--KQLSS--FKV
*
>P1;MLL3161
IDTGAT---LVA---V-NT-------STAR------------R------I
-G-----LSLN-----PSDFS-----------------------------
------HEVNT-A-NGSIK-----A-AVV---------T-IDRLQI----
----------GS--------------IS-VDDVQ--------A--IVL--
---DDKA---------------------------------------LSTN
LIGMS-FL--NRLGK--YQA
*
>P1;BLL8127
VDTGAS---VVA---L-NE-------TSAA------------R------F
-G-----LRPSR----GE-YN-----------------------------
------ATVST-A-NGTIK-----A-ART---------R-IAMLEV----
----------GG--------------LV-VRDVD--------A--MVL--
---PDEA---------------------------------------LSEN
LLGLS-FL--SRLKR--FEY
*
>P1;RPAL1816
VDTGAS---VVA---L-NE-------SSAA------------R------F
-G-----LRPSR----GD-YK-----------------------------
------TKVST-A-NGQVK-----A-ARA---------R-IAMLDV----
----------GG--------------LI-VRDVD--------A--LVL--
---PDEA---------------------------------------LSEN
LLGLS-YL--SKLKR--FAY
*
>P1;all7265
IDTGFNGYLTLP---P-QA-------ISAM------------N------L
-P-----LHST---------------------------------------
------IPAIL-A-DGSQV-----L-SSI----------HLT-TIV----
----------W---------------DN-V-EKV--------VFV-LA--
------S---------------------------------------ANKP
LLGTG-MM--NGYHLG-IDF
*
>P1;PAE0993
IDTGAT-Y-TVI---P-RR--------LAE------------E------I
-G-----APRT------GIY------------------------------
------AEVKT-A-YG-VV----KLELTH-----------IL-LEI----
---------EGT--------------RA-L-E----------AVL-VS--
-----DS---------------------------------------LEIP
LIGVR-TL--EGLGFR-VDP
*
>P1;PAE0531
VDTGAT-F-TVL---P-LE--------VAD------------K------L
IE-----TPFT---------------------------------------
------VELKL-G-NGEKV----VAKVYV-----------AE-AEI----
---------EG---------------RR-G------------PVRIVA--
-----FK---------------------------------------GAIP
VIGVD-TL--ETLGLR-VNP
*
>P1;AF0612
IDTGYEGF-AVV---P-QD--------IFK------------K------L
RL-----DELS------Q-H------------------------------
----K-RAL-T-L--PTER----LIESTGS---------YAR-III----
---------PEL--------------KT-FRD----------GFVETT--
----DGV---------------------------------------DEI-
VLGTE-FL--EGFKLV-LDY
*
>P1;SSO1395
VDTGFDGE-IIV---T-KE--------IFD------------K------I
-P-----YNSSD--------------------------------------
----G-TRICT-A-SME-C-----Y-STF--------------VKL----
---------VRTK-------------FL-GREIT--------AEVLNS--
----PVI---------------------------------------EKN-
IIGEG-LL--KKVSAV-INY
*
>P1;SSO2164
IDTGFSGY-LLI---P-PS--------VYN------------K------V
NS---LELENP---------------------------------------
------RVYAT-L-NG-IV-----KTRVA----------KAI-IKI----
----------GK--------------IK-L-DT---------LIESPI--
----LGR---------------------------------------EIS-
LLGRE-LQ--KILHIE-F--
*
>P1;SSO1929
VNTGFSGW-LLL---N-YE--------IYT------------K------L
NY---MEIPIT---------------------------------------
------RKYRS-I-LG-NI------EVYM---------AKAS-ISI----
--------------------------NR-L-NID--------AFIESS--
----PYV---------------------------------------EMN-
LLGRE-IL--KKLNIC-F-Y
*
>P1;SSO1523
IDTGFSGW-LLL---N-YE--------IYT------------K------L
NS---LEIPIT---------------------------------------
------RKYRS-I-LG-NI------EVFM---------SKAS-ITI----
--------------------------NR-L-NID--------AFIESS--
----PYI---------------------------------------EMN-
LLGRE-IL--KKLNIC-F-Y
*
>P1;ST0709
IDTGFSGE-IMV---N-YE--------IFD------------KIPFPTFN
AG----FVCIT------E-N------------------------------
------ECY-A-A-FG-KI-------ST---------------LRI----
---------LG---------------NE-I-N---------TVVL-WI--
----PQL---------------------------------------DEN-
LIGEG-AL--IKLGLV-INY
*
>P1;RB8280
VDTGFNGF-LSI---P-FR--------LVH------------Q------L
-G-----LPLSD-----V-Q------------------------------
------QGV-T-A-DG-RS-------SFF------------DTVEL----
---------TVI--------------WH-G-N----------PL-TVQ--
----AQV---------------------------------------LDEP
LLGTR--L--LRGSK--IEA
*
>P1;BR0864
VDTGAS---SVV---L-SQ-------EDAE------------R------A
-G-----IDTAS----LN-YS-----------------------------
------VPIMT-A-NGQAR-----A-ASI---------T-IATLQI----
----------GD--------------IE-RHDVR--------A--MVT--
---KEGL---------------------------------------LTGS
LLGMN-FL--QTLGG--FTV
*
>P1;MAGN03006869
FDTGAS---SVV---L-TA-------ENAA------------A------L
-G-----IRPAE----GD-FT-----------------------------
------QRVST-A-NGTAL-----A-API---------R-LASITV----
----------GP--------------IT-ERNID--------A--LVS--
---RPGM---------------------------------------LSTN
LLGQS-FL--QRLPS--YEV
*
>P1;PepArin2
VDTGTSLL-SGPT--N-AI-ASIQG-YIGA----------------SQNA
N------GEMVV----SCS-------------------------------
AINTL-PNIVFTI-NG---------VQYP-----LP-PSAY-VLQSQ---
---------QG---C---TSG-----FQ-GMD---------IPTSSG---
-----------------------------------------------ELW
ILGDV-FI-RQYFTV--FDR
*
>P1;Pepgal2
IDTGTSLV-AGPA--S-DI-NDIQS-AVGA----------------NQNT
Y------GEYSV----NCS-------------------------------
HILAM-PDVVFVI-GG---------IQYP-----VP-ALAY-TEQNG---
---------QG--TC---MSS-----FQ-NSS-------------AD---
------------------------------------------------LW
ILGDV-FI-RVYYSI--FDR
*
>P1;CatExen2
VDTGTSMI-TGPS--S-DI-VQLQS-IIGA----------------S-AA
N------GDYEV----DCT-------------------------------
VLNKM-PTMTFTI-NG---------IGYQ-----MT-PQQY-TLQDD---
---------DG--VC---SSG-----FQ-GLD---------ISPPAG---
-----------------------------------------------PLW
ILGDV-FI-GQYYSV--FDR
*
>P1;PepFequ2
VDTGTSLL-LGPQ--D-AV-LNIQE-IIQA----------------RRST
S------GGYFI----DCD-------------------------------
AVNTL-PDILFTI-DG---------IGYP-----VP-ANAY--IQKD---
-----A--ALG--IC---FSS-----FE-GNE---------DILNNL---
-----------------------------------------------EEW
ILGDV-FL-RLYFTV--FDR
*
>P1;Sccpep2
IDTGTSLI-TLPS--S-LA-E-IIN-KIGA----------------TKSW
S------GQYQV----DCA-------------------------------
KRDSL-PDLTLTF-AG---------YNFT-----LT-PYDY-IL-E----
--------VSGS--C---ISV-----FT-PMD---------FPQPIG---
-----------------------------------------------DLA
IVGDA-FL-RKYYSI--YDL
*
>P1;Renrat2
VDTGTSYI-SGPT--S-SL-QLIMQ-ALGV----------------KEKR
A------NNYVV----NCS-------------------------------
QVPTL-PDISFYL-GG---------RTYT-----LS-NMDY-VQKNP---
--------FRNDDLC---ILA-----LQ-GLD---------IPPPTG---
-----------------------------------------------PVW
VLGAT-FI-RKFYTE--FDR
*
>P1;Rencal2
VDTGASYI-SGST--S-SI-EKLME-ALGA----------------KKRL
-------FDYVV----KCN-------------------------------
EGPTL-PDISFHL-GG---------KEYT-----LT-SADY-VFQES---
--------YSSKKLC---TLA-----IH-AMD---------IPPPTG---
-----------------------------------------------PTW
ALGAT-FI-RKFYTE--FDR
*
>P1;Eimpeim2
VDTGSSLI-TGPS--S-VI-NPLIK-A-----------------------
-------LNVAE----NCS-------------------------------
NLGTL-PTLTFVL-KDIYG----RLVNFS-----LE-PRDY-VVEELDA-
--------RGNANNC---AAG-----FM-AMDVP-------AP-RGP---
------------------------------------------------LF
VLGNS-FI-RKYYSI--FDR
*
>P1;Plasmep2
VDSGTSSI-TAPT--E-FL-NKFFE-GLDV---------------VKIPF
L------PLYIT----TC--------------------------------
NNPKL-PTLEFRS-AT---------NVYT-----LE-PEYY-LQQIF---
--------DFGISLC---MVS-----II-PVD----------L--NK---
-----------------------------------------------NTF
ILGDP-FM-RKYFTV--FDY
*
>P1;Enpepcry2
ADTGTTLL-YLPA--T-VVSAYWAQ-VSGA---------------KSSSS
V------GGYVF----PCS-------------------------------
--ATL-PSFT-FG-VG--------SARIV-----IP-GDYI-DFGP----
-----I--STGSSSC-----------FG-GIQSSA-------G--IG---
-----------------------------------------------IN-
IFGDV-AL-KAAFVV--FNG
*
>P1;Ppeppen2
ADTGTTLL-LLDD--S-VVSQYYSQ-VSGA---------------QQDSN
A------GGYVF----DCS-------------------------------
--TNL-PDFSVSI-SG---------YTAT-----VP-GSLI-NYGP----
-----S--GDG-STC-----------LG-GIQSNS-------G--IG---
------------------------------------------------FS
IFGDI-FL-KSQYVV--FDS
*
>P1;Sypepsyn2
LDTGTTLL-IFDQ--A-TGSKVAAA-Y-GA---------------K-DNG
D------GTYTI----SCD-------------------------------
QSKLQ-PLALT-M-GG--------KDFF------VP-ADSL-IYVK----
---------QG-SQC---IA------GF-G------------YSSMD---
------------------------------------------------FA
IIGDT-FL-KNNYVV--FNQ
*
>P1;Mucorhi2
IDTGTNFF-IMP---S-SAASKIVKALPDA----------------TETQ
Q------G-WVV---PCASYQ-----------------------------
NSKST-ISIVMQK-SG----SSSDTIEIS-----VP-VSKM-LLPV----
--------DQSNETC---M-------FI-I-----------LPD-GGN--
------------------------------------------------QY
IVGNL-FL-RFFVNV--YDF
*
>P1;SAP7can2
LDTGTTYS-YLSK--D-QV-ESIVG-L-YG---------------NVTYN
DAGK---A-YEV----PCW-------------------------------
----V-GNPGNYL-EF-----NFKNEQYI----KVP-TSEF-VISVGT--
-----Y--ASGAELC-----------VF-G------------IL-PGT--
------------------------------------------------HS
ILGDN-FM-RSVYAV--FDL
*
>P1;hMem1-2
VDSGTTLL-RLPQ--K-VFDAVVEA-VARA------------S-LIPEFS
DGFWT--G-SQL----ACWTN-----------------------------
SETPW-SYFPKIS-IYLRDENSSRSFRIT----ILP--QLY-IQPMM---
-----G--AGLNYEC-----------YR-F------------GI-SPS--
----------------------------------------------TNAL
VIGAT-VM-EGFYVI--FDR
*
>P1;hMem2-2
VDSGTTNL-RLPK--K-VF-EAAVKSIKAA------------S-STEKFP
DGFWL--G-EQL----VCWQA-----------------------------
GTTPW-NIFPVIS-LYLMGEVTNQSFRIT----ILP--QQY-LRPVED--
-----V--ATSQDDC-----------YK-F------------AI-SQS--
----------------------------------------------STGT
VMGAV-IM-EGFYVV--FDR
*
>P1;Cparap2
LDSGTTLT-YFPS--D-FAAQLADK-A-GA------------R-LVQVAR
DQ-----YLYFI----DCN-------------------------------
TDTSG-TTVFNFG-NG---------AKIT-----VP-NTEY-VYQN----
--------GDG--TC-----------LW-G------------IQPSD---
------------------------------------------------DT
ILGDN-FLRHAYYLL--YNL
*
>P1;CatDhum2
VDTGTSLM-VGPV--D-EV-RELQK-AIGA----------------VPLI
Q------GEYMI----PCE-------------------------------
KVSTL-PAITLKL-GG---------KGYK-----LS-PEDY-TLKVSQ--
---------AGKTLC---LSG-----FM-GMD---------IPPPSG---
-----------------------------------------------PLW
ILGDV-FI-GRYYTV--FDR
*
>P1;CatDchi2
VDSGTSLI-TGPS--V-EV-KALQK-AIGA----------------FPLI
Q------GEYMV----NCD-------------------------------
TVPSL-PVISFTV-GG---------QVYT-----LT-GEQY-ILKVTQ--
---------AGKTMC---LSG-----FM-GLD---------IPAPAG---
-----------------------------------------------PLW
ILGDV-FM-GQYYTV--FDR
*
>P1;CatDgal2
VDTGTSLI-TGPT--K-EV-KELQT-AIGA----------------KPLI
K------GQYVI----SCD-------------------------------
KISSL-PVVTLML-GG---------KPYQ-----LT-GEQY-VFKVSA--
---------QGETIC---LSG-----FS-GLD---------VPPPGG---
-----------------------------------------------PLW
ILGDV-FI-GPYYTV--FDR
*
>P1;CatDdro2
ADTGTSLI-AAPL--E-EATSINQK-I-GG----------------TPII
G------GQYVV----SCD-------------------------------
LIPQL-PVIKFVL-GG---------KTFE-----LE-GKDY-ILRVAQ--
---------MGKTIC---LSG-----FM-GLD---------IPPPNG---
-----------------------------------------------PLW
ILGDV-FI-GKYYTE--FDM
*
>P1;CatDceg2
ADTGTSLI-AGPK--A-QI-EAIQN-FIGA----------------EPLI
K------GEYMI----SCD-------------------------------
KVPTL-PPVSFVI-GG---------QEFS-----LK-GEDY-VLKVSQ--
---------GGKTIC---LSG-----FM-GID---------LPERVG---
-----------------------------------------------ELW
ILGDV-FI-GRYYSV--FDF
*
>P1;CatDhyn2
VDTGTSLI-IGPS--A-EV-TALQK-AIGA----------------IPLI
Q------GEYMI----PCD-------------------------------
KVPSL-PVITFNL-GG---------KAFT-----VS-GEDY-VLKVSQ--
---------AGHTIC---LSG-----FM-GMD---------IPPPSG---
------------------------------------------------LW
TLGDV-FI-GPYYTV--FDR
*
>P1;CatDschi2
ADTGTSMI-AGPT--D-EVKQINQK-L-GA----------------THLP
G------GIYTV----SCD-------------------------------
VINNL-PSIDFVI-NG---------KHMT-----LE-PTDY-IMKVSK--
---------LGSEIC---LTG-----FI-GMD---------LP-RKK---
------------------------------------------------LW
ILGDV-FI-GKFYTI--FDM
*
>P1;Gastmac2
VDTGTSLL-TVPQ--Q-YM-SALLQ-ATGA----------------QEDE
Y------GQFLV----NCN-------------------------------
SIQNL-PTLTFII-NG---------VEFP-----LP-PSSY-IL------
-----N--NNG--YC---TVG-----VE-PTY---------LSAQNS---
----------------------------------------------QPLW
ILGDV-FL-RSYYSV--YDL
*
>P1;CatDonc2
VDTGTSLI-TGPA--A-EV-KALQR-AIGA----------------TPLI
Q------GEYMV----NCD-------------------------------
KIPTM-PVITFNL-GG---------QSYS-----LT-AEQY-VLKESQ--
---------AGKTIC---LSG-----FM-GLD---------IPAPAG---
-----------------------------------------------PLW
ILGDV-FI-GQYYTV--FDR
*
>P1;Napamo2
LDTGTSLI-TGPS--E-EI-RALNK-AIGG----------------YPFL
N------GQYFI----QCS-------------------------------
KTPTL-PPVSFHL-GG---------VWFN-----LT-GQDY-VIKILQ--
-----S--DVG--LC---LLG-----FQ-ALD---------IPKPAG---
-----------------------------------------------PLW
ILGDV-FL-GPYVAV--FDR
*
>P1;CND412
LDSGTVIT-RLAP--S-VY-RAVRA-EFAR----------QFGAERYPAA
------PPFSLLD---ACY--------------------N------LTGH
DEVKV-PLLTLRLEGG---------ADMT---VDAA-GMLF-MAR-----
--------KDGSQVC--LAMA-----SLSFED---------QTPIIG---
------------------------------------------NYQQKNKR
VVYDT-VGSRLGFAD--EDC
*
>P1;Nephen2
IDSGTTLT-YLPQ--D-AY-NAVAQ-AFTD----------QIN---LPTV
DE---SSSGLS-----TCF--------------------QQ-----PSDG
STVQV-PEISMQFDGG-----------------VLNLGEQNILISP----
--------AEG-VIC--LAMG-------SSSQ--------LGISIFG---
------------------------------------------NIQQQETQ
VLYDL-QNLAVSFVP--TQC
*
>P1;AtASP382
VDSGTQFT-FLLG--P-VY-TALRS-HFLN------RTNGILTVYEDPDF
V----FQGTM-D----LCY--------------------RISP-VRIRSG
ILHRL-PTVSLVFEGA--------EIAVS-----GQ-PLLYRVPHLTV--
------G--NDSVYC--FTFG--------NSD-----LMGMEAYVIG---
------------------------------------------HHHQQNMW
IEFDL-QRSRIGLAP--VEC
*
>P1;NM_11499_2
FDTGTSFT-HLLE--P-EY-GLITK-AFDD----------HVTDKRRPID
P----ELP-FE-----FCY--------------------DLS-----PNK
TTILF-PRVAMTFEGG----------SQM----FLRNPL-F-IVW-----
------NEDNSAMYC---L-G-----ILKSVD--------FKINIIG---
------------------------------------------QNFMSGYR
IVFDR-ERMILGWKR--SDC
*
>P1;Nucelin2
FDSGATYT-YFAL--Q-PY-HATLS-VVKS--------TLSKECKFLTEV
KE---KDRALT-----VCW--------------------KGKDKIRTIDE
VKKCF-RSLSLKFADG--------DKKAT---LEIP-PEHY-LIISQ---
---------EG-HVCLGILDG--S-KEHPSLA---------GTNLIG---
------------------------------------------GITMLDQM
VIYDS-ERSLLGWVN--YQC
*
>P1;Ppeppen1
FDTGSADL-WVFS--T-EL----PASQQSG------------HSV----Y
N------P--SAT--GKELS------------------------------
GYT---WSISY-G-DG-SS-----AS-GNV-------FTDS--VTV----
---------GGVTA-----HG---QAVQ--AA------QQISAQFQQDT-
----------------------------------------------NNDG
LLGLA-FS-SINTVQ--PQS
*
>P1;Cparap1
IDTGSSDF-WVVD-NA-QC---GKGVDCKS------------SGT----F
T------PSSSSS--YKNL-------------------------------
GAA---FTIRY-G-DG-ST-----SQ-GTW-------GKDT--VTI----
---------NGVSI-----TG---QQIA--DV--------TQTS--VD--
------------------------------------------------QG
ILGIG-YTSNEAVYDTSGRQ
*
>P1;SAP7can1
IDTGSSDL-WFISGNS-QCKVNGGSIDCDK------------YGV----F
D------KSKSSS--WHDN-------------------------------
KTD---YSISY-Y-DG-DK-----AS-GTM-------GQDN--ITFA---
---------DGFSI-----EN---ANFA--VI--------DNTTSSI---
-------------------------------------------------G
VFGVG-YP-ELEAVKSKYTN
*
>P1;hMem1-1
VDTGSSNF-AVA----------GTP-HSYI------------DTY----F
D------TERSST--YRSK-------------------------------
GFD---VTVKY-T-QG-S------WT-GFV-------GEDL--VTIP---
---------KGFNT-----SF--LVNIA--TI--------FESENFFL--
----PGI---------------------------------------KWNG
ILGLA-YA-TL-AK---PSS
*
>P1;hMem2-1
VDTGSSNF-AVG----------AAP-HPFL------------HRY----Y
Q------RQLSST--YRDLRK-----------------------------
G-----VYVPY-T-QG-K------WE-GEL-------GTDL--VSIP---
---------HGPNV-----TV--RANIA--AI--------TESDKFFI--
----NGS---------------------------------------NWEG
ILGLA-YA-EI-AR---PDD
*
>P1;Enpepcry1
FDTGSSDL-WVFS--S-ET----TASEVDG------------QTI----Y
T------PSKSTT--AKLLS------------------------------
GAT---WSISY-G-DG-SS-----SS-GDV-------YTDT--VSV----
---------GGLTV-----TG---QAVE-SA---------KKVSSSFT--
----EDS---------------------------------------TIDG
LLGLA-FS-TLNTVS--PTQ
*
>P1;Sypepsyn1
FDTGSSDL-WFSS--T-LC----TS--CGS------------KS-----F
D------PTKSST--YKKV-------------------------------
GKS---WQISY-G-DG-SS-----AS-GIT-------ATDN--VEL----
---------GGLKI-----TG---QTIE-LA---------TRESSSFS--
-----SG---------------------------------------AIDG
ILGLG-FD--TIST---VAG
*
>P1;PepFequ1
FDTGSADL-WVPS--I-YC----SSPACSN------------HNT----F
N------PLRSST--FVAS-------------------------------
GQP---IKLIY-G-TG-K------MS-GFV-------GYDT--IKI----
---------SSLVD-----RN---QAFG-LSV--------EEPDKILE--
-----LA---------------------------------------TFDG
ILGLS-YP--I-LS---VKG
*
>P1;CatExen1
FDTGSSNL-WVPS--V-YC----ISPACAQ------------HNR----F
Q------PQLSST--YESN-------------------------------
GNN---FSLQY-G-TG-S------LS-GVI-------GIDS--VTV----
---------EGILV-----QN---QQFG-ESV--------SEPGSTFV--
-----DA---------------------------------------SFDG
ILGLG-YP--S-IA---VGG
*
>P1;Gastmac1
FDTGSSNL-WVPS--V-YC----QSQACTS------------HSR----F
N------PSESST--YSTN-------------------------------
GQT---FSLQY-G-SG-S------LT-GFF-------GYDT--LTV----
---------QSIQV-----PN---QEFG-LSE--------NEPGTNFV--
-----YA---------------------------------------QFDG
IMGLA-YP--T-LS---VDG
*
>P1;PepArin1
FDTGSSNL-WVPS--V-YC----SSPACSN------------HNR----F
N------PQQSST--YQGT-------------------------------
NQK---LSVAY-G-TG-S------MT-GIL-------GYDT--VQV----
---------GGITD-----TN---QIFG-LSE--------TEPGSFLY--
-----YA---------------------------------------PFDG
ILGLA-YP--S-IA---SSG
*
>P1;Pepgal1
FDTGSSNL-WVPS--V-SC----TSPACQS------------HQM----F
N------PSQSST--YKST-------------------------------
GQN---LSIHY-G-TG-D------ME-GTV-------GCDT--VTV----
---------ASLMD-----TN---QLFG-LST--------SEPGQFFV--
-----YV---------------------------------------KFDG
ILGLG-YP--S-LA---ADG
*
>P1;CatDonc1
FDTGSSNL-WVPS--V-HC--SFTDIACLL------------HHK----Y
N------GAKSST--YVKN-------------------------------
GTA---FAIQY-G-SG-S------LS-GYL-------SQDT--CTI----
---------GGLSI-----ED---QGFG-EAI--------KQPGVAFI--
-----AA---------------------------------------KFDG
ILGMA-YP--R-IS---VDG
*
>P1;CatDhum1
FDTGSSNL-WVPS--I-HC--KLLDIACWI------------HHK----Y
N------SDKSST--YVKN-------------------------------
GTS---FDIHY-G-SG-S------LS-GYL-------SQDT--VSVPCQS
ASSASA--LGGVKV-----ER---QVFG-EAT--------KQPGITFI--
-----AA---------------------------------------KFDG
ILGMA-YP--R-IS---VNN
*
>P1;CatDchi1
FDTGSSNL-WVPS--I-HC--SLLDIACLL------------HHK----Y
N------SGKSST--YVKN-------------------------------
GTA---FAIQY-G-SG-S------LS-GYL-------SQDT--CTI----
---------GDLAI-----DS---QLFG-EAI--------KQPGVAFI--
-----AA---------------------------------------KFDG
ILGMA-YP--R-IS---VDG
*
>P1;CatDgal1
FDTGSSNL-WVPS--V-HC--HLLDIACLL------------HHK----Y
D------ASKSST--YVEN-------------------------------
GTE---FAIHY-G-TG-S------LS-GFL-------SQDT--VTL----
---------GNLKI-----KN---QIFG-EAV--------KQPGITFI--
-----AA---------------------------------------KFDG
ILGMA-FP--R-IS---VDK
*
>P1;CatDdro1
FDTGSSNL-WVPS--K-KC--HLTNIACLM------------HNK----Y
D------ASKSKT--YTKN-------------------------------
GTE---FAIQY-G-SG-S------LS-GYL-------STDT--VSI----
---------AGLDI-----KD---QTFA-EAL--------SEPGLVFV--
-----AA---------------------------------------KFDG
ILGLG-YN--S-IS---VDK
*
>P1;CatDceg1
FDTGSSNL-WIPS--K-KC--PFYDIACML------------HHR----Y
D------SKSSST--YKED-------------------------------
GRK---MAIQY-G-TG-S------MK-GFI-------SKDS--VCV----
---------AGVCA-----ED---QPFA-EAT--------SEPGITFV--
-----AA---------------------------------------KFDG
ILGMA-YP--E-IA---VLG
*
>P1;CatDhyn1
FDTGSSNL-WVPS--V-HC--SLLDIACLV------------HPK----Y
D------SSSSST--YVKN-------------------------------
GTE---FSIQY-G-TG-S------LS-GYL-------RQDT--VSV----
---------GGLGV-----LK---QVFG-EAI--------KQPGVAFI--
-----AA---------------------------------------KFDG
ILGMA-YP--R-IS---VDG
*
>P1;CatDschi1
FDTGSSNL-WVPS--K-HC--SYFDIACLL------------HRK----Y
D------SSKSTT--YVPN-------------------------------
GTD---FSIRY-G-TG-S------LS-GFL-------STDS--LQL----
---------GSLGV-----KG---QTFG-EAT--------KQPGLVFV--
-----MA---------------------------------------KFDG
ILGMA-YP--S-LA---VGG
*
>P1;Renrat1
FDTGSANL-WVPS--T-KC--GPLYTACEI------------HNL----Y
D------SSESSS--YMEN-------------------------------
GTE---FTIHY-G-SG-K------VK-GFL-------SQDV--VTV----
---------GGIIV-----T----QTFG-EVT--------ELPLIPFM--
-----LA---------------------------------------KFDG
VLGMG-FP--A-QA---VDG
*
>P1;Rencal1
FDTGSSNV-WVPS--S-KC--SRLYTACVY------------HKL----F
D------ASDSSS--YKHN-------------------------------
GTE---LTLRY-S-TG-T------VS-GFL-------SQDV--ITV----
---------GGITV-----T----QTFG-EVT--------EMPALPFM--
-----LA---------------------------------------EFDG
VVGMG-FS--E-QA---IGK
*
>P1;Napamo1
FDTGSSNL-WVPS--T-RC--HFFSLACWF------------HHR----F
N------PKASSS--FRPN-------------------------------
GTK---FAIQY-G-TG-R------LS-GIL-------SQDN--LTI----
---------GGIHD-----AF---VTFG-EAL--------WEPSLIFA--
-----LA---------------------------------------HFDG
ILGLG-FP--T-LA---VGG
*
>P1;Sccpep1
LDTGSSNL-WVPS--Q-DC---T-SLACFL------------HAK----Y
D------HDASST--YKVN-------------------------------
GSE---FSIQY-G-SG-S------ME-GYI-------SQDV--LTI----
---------GDLVI-----PG---QDFA-EAT--------SEPGLAFA--
-----FG---------------------------------------KFDG
ILGLA-YD--T-IS---VNH
*
>P1;Mucorhi1
FDTGSSDT-WVPH--K-GC---TKSEGCVG------------SRF----F
D------PSASST--FKATN------------------------------
YN----LNITY-G-TG-G------AN-GLY-------FEDS--IAI----
---------GDITV-----TK---QILA-YVD---NVRGPTAEQSPNA--
-----DI---------------------------------------FLDG
LFGAA-YP--DNTAMEAEYG
*
>P1;Eimpeim1
FDTGSSNL-WVPA--A-EC---EKG-GCAP------------HEK----F
D------PKYSST-FSPIRSL-----------------------------
TGDPA-VAFIQYG-TG--------AC-VLR------MGRDI--VEI----
---------GGIKV-----PN---QAIG-LAV--------EESTHPFA--
-----DL---------------------------------------PFDG
LVGLG-FP--D-VSGE-EGL
*
>P1;Plasmep1
FDTGSANL-WVPS--A-QCN--TI--GCKT------------KNL----Y
D------SNKSKT--YEKD-------------------------------
GTK---VEMNY-V-SG-T------VS-GFF-------SKDI--VTI----
---------ANLSF-----PY---KFIE-VTD--------TNGFEPAY--
----TLG---------------------------------------QFDG
IVGLG-WK--D-LS---IGS
*
>P1;CND411
VDTGS-DLTWVQC--K-PC------SVCY----------AQRDPL----F
D------PSGSAS--YAAVPCNASACEASLKAATGVPGSCATVGGGGGGG
KSERCYYSLAY-G-DG-S------FSRGVL-------ATDT--VAL----
---------GGASV-----DG---FVFG-CGL---------SNRGLFG--
---G-------------------------------------------TAG
LMGLG-P-------------
*
>P1;Nephen1
MDTGS-DLIWTQC--E-PC------TQCF----------SQPTPI----F
N------PQDSSS--FSTLPCESQYCQDL-------PSETC---------
NNNECQYTYGY-G-DG-S------TTQGYM-------ATET--FTF----
---------ETSSV-----PN---IAFG-CGE---------DNQGFGQ--
---GN------------------------------------------GAG
LIGMG-WG--P-LS---LPS
*
>P1;AtASP381
IDTGS-ELSWLRC--N-RS------SNPN------------PVNN----F
D------PTRSSS--YSPIPCSSPTCRTRTRDFLI-PASCD---------
SDKLCHATLSY-A-DA-S------SSEGNL-------AAEI--FHF----
---------GNSTN----DSN---LIFG-CMG---------SVSGSDP--
---EEDT---------------------------------------KTTG
LLGMN-RG--S-LS---FIS
*
>P1;NM_11499_1
LDTGS-DLFWLPC--N-CG------STCIRDLKEVGLSQSRPLNL----Y
S------PNTSST--SSSIRCSDDRCFGSSRCSSP-ASSCP---------
--YQIQYLSKD-T-FT-T------GTLFED-------VLHL--VTE----
-----D--EGLEPV----KAN---ITLG-CGK---------NQTGFLQ--
---SSAA---------------------------------------VNGL
LGLGL-KD--Y-SV---PSI
*
>P1;Nucelin1
IDTGS-TLTWLQC--DYPC------INCN----------KVPHGL----Y
K------PELK----YA-VKCTEQRCADLYADLRK-PMKCG---------
PKNQCHYGIQY-V-GG-S-------SIGVL-------IVDS--FSL----
-----P--ASNGTN----PTS---IAFG-CGY---------NQGKNNH--
---NVPT---------------------------------------PVNG
ILGLG-RG--K-VT---LLS
*
>P1;Bs1
LDSGGARL-LLPS--A-A---LP---FASA--------------TDTAFS
S-------IYGV----ECG-------------------------------
TIHTY-TAALTRP-AA-----------LH-----KP-LVVA-HAKCST--
-----P--GHNR-VC---AET----QRQ-G------------PRQARRQC
RLRVHVRR---------------------------------------LHF
TGLQL-HV-RQH-----GRR
*
>P1;RTVL-H3
IDTGATH--STL---------------PSF------------Q------G
-P------VS------LAP-------------------------------
------ITVVG-I-DGQ--------------------ASKPL-KTPP---
---LWC--QLG-------------QHSFMHS-----------FL-VIPT-
------C---------------------------------------PLP-
LLGRN-ILT--KLSAS-LTI
*
>P1;SMRV-H
LDTGADA--TVI---------------SYT------------H------W
-P-----RNW------PLTTV-----------------------------
----A-THLRG-I--GQ-------ATNPQ--------QSAQM-LKWED--
---SEG--NNG----------------HIT------------PY-VLPN-
------L---------------------------------------PVN-
LWGRD-ILSQMK-----LVM
*
>P1;SERV
IDTGADV--TII---------------KQE------------D------W
-P-----SHW------PTTET-----------------------------
----L-THLRG-I--GQ-------SSNPK--------QSSKY-LTWTD--
---KEN--NSG----------------LIK------------PF-IIPH-
------L---------------------------------------PVN-
LWGRD-LLSQMK-----IIM
*
>P1;JSRV
LDTGADI--SVI---------------SDK------------Y------W
-P-----TTW------PKQMA-----------------------------
----I-STLQG-I--GQ-------TTNPE--------QSSSL-LTWKD--
---KDG--HTG----------------QFK------------PY-ILPY-
------L---------------------------------------PVN-
LWGRD-ILSKMG-----VYL
*
>P1;MPMV
IDTGADV--TII---------------KLE------------D------W
-P-----PNW------PITDT-----------------------------
----L-TNLRG-I--GQ-------SNNPK--------QSSKY-LTWRD--
---KEN--NSG----------------LIK------------PF-VIPN-
------L---------------------------------------PVN-
LWGRD-LLSQMKIMMCSPND
*
>P1;MMTV
LDTGADK--TCI---------------AGR------------D------W
-P-----ANW------PIHQT-----------------------------
----E-SSLQG-L--GM-------ACGVA--------RSSQP-LRW-Q--
---HED--KSG----------------IIH------------PF-VIPT-
------L---------------------------------------PFT-
LWGRD-IMKDIKVRLMQPVW
*
>P1;SRV-1
IDTGADV--TII---------------KLE------------D------W
-P-----PNW------PITDT-----------------------------
----L-TNLRG-I--GQ-------SNNPK--------QSSKY-LTWRD--
---KEN--NSG----------------LIK------------PF-VIPN-
------L---------------------------------------PVN-
LWGRD-LLSQMKIMMCSPSD
*
>P1;HERV-K10
VDTGADV--SII---------------ALN------------Q------W
-P-----KNW------PKQKA-----------------------------
----V-TGL-V-G-IG-------TASEVY--------QSMEI--LHCL--
---GPD--NQE----------------STV-----------QPM-ITS--
------I---------------------------------------PLN-
LWGRD-LLQQWG-AEITMPA
*
>P1;KoRV
VDTGAEH--SVL-----------------T------------K------P
MG-------------KMGSK------------------------------
----R-TVVAG-A-TG--------SKVY--------PWTTKRLLKI----
----------G-------------QKQVTHS-----------FL-VIPE-
------C---------------------------------------PAP-
LLGRD-LL--TKLK---AQI
*
>P1;PERV-MSL
VDTGAKH--SVL-----------------L------------Q------P
LG-------------KLKDK------------------------------
----K-SWVMG-A-TG--------QQQY--------PWTTRRTVDL----
----------G-------------VGRVTHS-----------FL-VIPE-
------C---------------------------------------PAP-
LLGRD-LL--TKMG---AQI
*
>P1;RCHO-K1
VDTGAQH--SVL-----------------N------------RS-----P
GP--------------LS-H------------------------------
---RT-AWVQG-A-TG--------GKQY--------HWTTNRQLQL----
----------A-------------TGKVMHS-----------FL-HVPD-
------C---------------------------------------PYP-
LLGRD-LL--TKLR---AQI
*
>P1;HERV-E
VDTSAEH--SVV-----------------T------------ASV----A
-P--------------LS-K------------------------------
---KT-IDIIG-A-MG-----VSAKQAFCL------PQTCTI--------
----------G-------------GHKVIHQ-----------FL-YMPD-
------C---------------------------------------PLP-
LLGRD-LL--SKLR---ATI
*
>P1;RTVL-Ia
VDSGAAC--SSV------------------------------C------F
-P----SSNV-----ACSSE------------------------------
---EL-IVSEIKG-EG---------FTVR--------ILENTEVKY----
----------Q--------------DTTQVQ-----------FL-LIPE-
------A---------------------------------------ATS-
LLGRD-LM--LKLGIG-LQV
*
>P1;GALV
VDTGAEH--SVL-----------------T------------Q------P
MG------KV------GSRR------------------------------
------TVVEG-A-TG--------SKVY--------PWTTKRLLKI----
----------G-------------HKQVTHS-----------FL-VIPE-
------C---------------------------------------PAP-
LLGRD-LL--TKLK---AQI
*
>P1;MdEV
IDTGAEH--SVL-----------------T------------S------P
LG------KL------GSKR------------------------------
------TIVVG-A-TG--------SKLY--------PWTTKRALQI----
----------D-------------KNMVTHS-----------FL-VIPE-
------C---------------------------------------PAP-
LLGRD-LL--TKLK---AQV
*
>P1;Q88269
IDTGAEH--LVL-----------------Q------------I------P
LG------S-------VSNK------------------------------
----K-VAVQG-S-MGA------IQEYP---------VTHSREVSL----
----------G-------------QKRVTHS-----------FL-AVPE-
------C---------------------------------------PFP-
LLRRD-LL--HKLQTS-ISL
*
>P1;REV
VDTGATH--SVV-----------------Q------------K------P
VG--------------PMSKE-----------------------------
----S-VAIIG-A-TGN------IRNYP---------KSEGRLVDL----
----------G-------------RGLVTHS-----------FL-VIPE-
------C---------------------------------------PDP-
LLGRD-LL--QKLR---ATI
*
>P1;FeLV
VDTGAQH--SVL-----------------T------------RPD----G
-P--------------LSDR------------------------------
----T-ALVQG-A-TGS--------KNY--------RWTTDRRVQL----
----------A-------------TGKVTHS-----------FL-YVPE-
------C---------------------------------------PYP-
LLGRD-LL--TKLK---AQI
*
>P1;MuLV
VDTGAQH--SVL---------------TQN------------P------G
-P--------------LSDK------------------------------
----S-AWVQG-A-TGG--------KRY--------RWTTDRKVHL----
--------ATG---------------KVTHS-----------FL-HVPD-
------C---------------------------------------PYP-
LLGRD-LL--TKLK---AQI
*
>P1;BAEVM
VDTGAQH--SVL---------------TKA------------N------G
-P--------------LSSR------------------------------
----T-SWVQG-A-TG---------RKMH-------KWTNRRTVNL----
--------GQG---------------MVTHS-----------FL-VVPE-
------C---------------------------------------PYP-
LLGRD-LL--TKLG---AQI
*
>P1;LOC386135
LDTGADK--SII---------------STH------------W------W
-P-----KAW------PTTES-----------------------------
----S-HSLQG-L--GY-------QSCPT--------ISSVA-LTW----
----ES--SEG---------------QQGKF----------IPY-VLP--
------L---------------------------------------PVN-
LWGRD-IM--QHLG---LIL
*
>P1;WdSV
VDTGACL--TAI---------------GGA------------ATVV---P
DL------K-------LTN-------------------------------
----T--EI-I-A-VGI-----SAEPVPH-------VLAKPTKIQI----
---------EN--------------TNIDIS-----------PW-YNP--
-----DQ---------------------------------------TFH-
ILGRD-TL--SKMR---AIV
*
>P1;MuERV-L
LDTGSEL--TLI------------------------------P------G
DP-----KKHCG----PP--------------------------------
------VKV-G-A-YGG------QVING--------VLTDVR-LTV----
----------G------------PVGPRTH------------PVVISP--
------V---------------------------------------PEC-
IIGID-IL---RN----WQN
*
>P1;RSV
LDSGADI--TII---------------SEE------------D------W
-P-----TDW------PVMEA-----------------------------
A---N-PQIHG-I-GG---------GIPM----RK-SRD-M--IEVGV--
---INR---DG--------------S--LER-----------PLLLFPAV
AM----V---------------------------------------RGS-
ILGRD-CL-QGLG----LRL
*
>P1;LPDV
LDTGADV--TVI---------------NEP------------S------W
-P-----CTW------PAIPT-----------------------------
------VGVEG-V-GG---------LTN-------ASRSE---FLLQG--
---RIR--REK------------EEIRVS-------------PY-IAA--
------I---------------------------------------GFN-
ILGREALA-QLHCVV--SNL
*
>P1;EAV-HP
IDSGADV--TVV---------------AET------------E------W
-P-----SSW------PAEAS-----------------------------
------QSIMG-V-GG---------ATPS----RR-STN-E--VQAVV--
---INR---DG------------SLEKPAL-----------LTP-LVAR-
------V---------------------------------------PGT-
LLGRD-FLRQI-G----ARL
*
>P1;FFV
WDSQADI--TCV-----PK---------DL-------------------L
QG--------------EEPVR-----------------------------
Q-----QNVTT-I-HGT------QEGDV---------YY-VN-LKID---
----------GRRIN-----------TEVIGT----------TLDYAI--
----IT----------------------------------------PGDV
PWILKKPL-ELTIK---LDL
*
>P1;FSV
WDSQADV--TCV-----PK---------SL-------------------L
QG--------------EEPVR-----------------------------
Q-----QNVTT-I-HGT------QEEDV---------YY-VN-LKID---
----------GRRIN-----------TEVIGT----------TLDYAI--
----IT----------------------------------------PGDV
PWILKKPL-ELTIK---LDS
*
>P1;HFV
WDSGATI--TCI-----PE---------SF-------------------L
ED--------------EQPIK-----------------------------
K-----TLIKT-I-HGE------KQQNV---------YY-VT-FKVK---
----------GRKVE-----------AEVIAS----------PYEYIL--
----LS----------------------------------------PTDV
PWLTQQPL-QLTIL---VPL
*
>P1;SFV-3
WDSGATI--TCV-----PQ---------AF-------------------L
EE--------------EVPIK-----------------------------
N-----IWIKT-I-HGE------KEQPV---------YY-LT-FKIQ---
----------GRKVE-----------AEVISS----------PYDYIL--
----VS----------------------------------------PSDI
PWLMKKPL-QLTTL---VPL
*
>P1;EFV
YDTGAEI--TCV-----PA---------IF-------------------L
IE--------------EEPIG-----------------------------
E-----RTIQT-I-HGI------TKEKV---------YY-LT-FKIQ---
----------GRKLA-----------AEVIGT----------QLDYVI--
----IA----------------------------------------PSDI
PWYKKYEL-ELTIH---IDI
*
>P1;SFV-1
WDSGATI--TCV-----PE---------AF-------------------L
ED--------------ERPIQ-----------------------------
T-----MLIKT-I-HGE------KQQDV---------YY-LT-FKVQ---
----------GRKVE-----------AEVLAS----------PYDYIL--
----LN----------------------------------------PSDV
PWLMKKPL-QLTTL---VPL
*
>P1;HIV-1
LDTGADD--TVL---------------EDI------------N------L
PG------K-------WKPK------------------------------
-------MIGG-I-GG--------FIKVR-------QYDRIL-IEI----
---------CG--------------KKAIGT-----------V--LVGP-
------T---------------------------------------PVN-
IIGRN-MLTQIGCT---LNF
*
>P1;SA-OMVV
VDTGADR--TIV---------------RYH------------D------N
SG------I-------PTGR------------------------------
------IKLQG-I-GG--------IIEGE-------KWDKV--V-IQ---
-----Y---KE--------------KRIEGT-----------I--VVLP-
-----SS---------------------------------------PVE-
VLGRDNMA-KLDIGIIMANL
*
>P1;CAEV
FDTGADR--TIV---------------RWH------------E------G
SG------N-------PAGR------------------------------
------IKLQG-I-GG--------IVEGE-------KWNN---VELE---
-----Y---KG--------------ETRKGT-----------I--VVLP-
-----QS---------------------------------------PVE-
VLGRDNMA-RFGIKIIMANL
*
>P1;FIV
LDTGADI--TIL---------------NRR------------D------F
QV-----KNS-----IENGR------------------------------
------QNMIG-V-GGG-------KR-GT-------NYINVH-LEIRD--
---ENY---KT--------------QCIFGN-----------VC-VLED-
-----NS---------------------------------------LIQP
LLGRDNMI-KFNIRLVMAQI
*
>P1;EIAV
LDTGADT--SVL-------------TTAHY------------NRLK---Y
RG-----KK-------YQGT------------------------------
-------GIIG-V-GG----------NVE-------TFSTP--VTIK---
-----K---KG--------------RHI-KT-----------RM-LVAD-
------I---------------------------------------PVT-
ILGRD-ILQDLGAKLVLAQL
*
>P1;VMV
VDTGADK--TIV---------------TSH------------D------M
SG------I-------PKGR------------------------------
------IILQG-I-GG--------IIEGE-------KWEQVH-LQYK---
-----D---KM--------------IK--GT-----------IV-VLAT-
------S---------------------------------------PVE-
VLGRDNMR-ELGIGLIMANL
*
>P1;SIVMND
LDTGADD--TIF---------------NER------------NIK----L
KG------N-------WQPK------------------------------
-------IIGG-I-GG--------NLRVK-------QYDNVY-VEIR---
-----G---KG--------------TF--GT-----------V--LIGP-
------T---------------------------------------PID-
IIGRN-IMEKLGGKLILAQL
*
>P1;HIV-2
LDTGVDD--SIV----------------AG------------I------E
LG-----SN-------YTPK------------------------------
-------IVGG-I-GG--------FINTK-------EYKDVE-IEVV---
----------G--------------KR--VR-----------AT-IMTG-
-----DT---------------------------------------PIN-
IFGRN-ILNTLGMT---LNF
*
>P1;SIVAGM
LDTGADD--TII---------------KEE------------DIH----L
EG------R-------WRPK------------------------------
-------VVGG-I-GG--------GISVK-------QYDNIL-VNID---
----------G------------KETR--GN-----------V--LIGP-
------T---------------------------------------PIN-
IVGRN-ILAPLGARLIMGQL
*
>P1;BIV
VDTGADE--VVL-------------KNIHW------------DR-----I
KG-----YP-------GTPI------------------------------
-------KQIG-V-NGV------NVAKRK---------THVE-WRFK---
----------D--------------KT--GI-----------ID-VLFS-
-----DT---------------------------------------PVN-
LFGRS-LLRSIVTC---FT-
*
>P1;SIVMAC
LDTGADD--SIV---------------TGI------------E------L
-G-----PH-------YTPK------------------------------
------I-VGG-I-GG--------FINTK-------EYKNVE-IEVL---
----------G--------------KR--IK-----------GT-IMTG-
-----DT---------------------------------------PIN-
IFGRN-LLTALGMS---LNL
*
>P1;STcLV2PP1664
LDTGADL--TVL---------------PQA------------L------A
-P-----ESVS-----VSDTT-----------------------------
--------VLG-A-GGQ------TSSQF-------KLLQSP--LCVY---
---------LP----------------FRRA-----------PV-TLPSC
LVD-TNS---------------------------------------KWA-
IIGRD-ILQKCQSVLYLPED
*
>P1;HTLV-2
LDTGADL--TVI---------------PQT------------L------V
PG--------------PVKLH-----------------------------
----D-TLILG-A-SGQ------TNTQF-------KLLQTP--LHIF---
---------LP----------------FRRS-----------PV-ILSSC
LLD-THN---------------------------------------KWT-
IIGRD-ALQQCQGLLYLPDD
*
>P1;HTLV-1
LDTGADM--TVL---------------PIA------------L------F
SS------NT------PLKNT-----------------------------
-------SVLG-A-GGQ------TQDHF-------KLTSLP--VLIR---
---------LP----------------FRTT-----------PI-VLTSC
LVD-TKN---------------------------------------NWA-
IIGRD-ALQQCQGVLYLPEA
*
>P1;BLV
VDTGAEN--TVL---------------PQN-------------------W
-L-----VRDY-----PRIPA-----------------------------
-------AVLG-A-GGV------SRNRYN--------WLQ---GPLTL--
---ALK--PEG---------------PFITI-----------PK-ILVDT
F-----D---------------------------------------KWQ-
ILGRD-VLSRLQASISIPEE
*
>P1;RetroSor1
VDSGSSA--DII---F-AG--------TFD------------Q------M
KL----SRSQLQ----PSES------------------------------
------P-LIG-F-GGKQI-----HALG----------K-VA-LPVS---
---------FGTTEN-----------ART-EYVT--------FD-VVDL-
-----HY---------------------------------------PYNA
IFGRG-FL--NKF----NAA
*
>P1;Cinful-1
VDTGSAA--DII---F-AK-------A-FR------------Q------M
-Q-EL-EDKIHD----ATH-------------------------------
------P-LCG-F-GGRQI-----VALG----------K-IT-MSVT---
---------FGFINN-----------TRT-EQVV--------FD-IVDM-
-----EY---------------------------------------PYNA
IIGRG-TL--NAF----EAI
*
>P1;B1147A04.5
IDGGAAL--NIL---S-PA-------A-FD------------A------I
-K--A-PGMVLR----PSQ-------------------------------
------P-IIGVT-PGHTW------PLG----------H-ID-LPVT---
---------FGGSAN-----------FRT-ERVN--------FD-VADL-
-----SL---------------------------------------PYNA
VLGRP-AL--VKF----MAA
*
>P1;Ogre
VDTGSSL--NVL---P-KQ-------I-LK------------K------I
-D--V-EGFVLT----PSD-------------------------------
------L-IVRAF-D-RSK----RSVCG----------E-VT-LPVK---
---------IG-PEV-----------F---DII---------FY-VMDI-
-----QP---------------------------------------AYSC
LLGRP-WI--HAA----GAV
*
>P1;Grande1-4
VDGGSSI--NVT---F-PR-------T-LQ------------G------L
-G--V-HLKELH----ESDT------------------------------
------P-FFGIV-PMEGE-----YPLG----------H-IY-MPVT---
---------FGTPEN-----------YRT-EFLR--------FE-VANF-
-----DC---------------------------------------GYNA
IIGRP-GL--AKF----MAI
*
>P1;Tat4-1
IDTGSSV--NVI---F-KD-------V-LQ------------K------M
-E--V-HERHIK----PSVR------------------------------
------P-LTG-F-DGNTL-----MTNG----------T-IK-LPIY---
---------LGGAAT-----------WHK-------------FV-VVDK-
-----PV---------------------------------------IYNI
ILGTP-WI--HDM----QAI
*
>P1;Tft2
IDTGSSV--DLI---F-LS-------T-LE------------R------M
-G--I-SRADVV----GPPS------------------------------
------P-LVA-F-TSESL-----MSLG----------T-IK-LPVL---
---------AGKI-------------SKIVD-----------FV-VFDK-
-----PA---------------------------------------AYNI
ILGTL-WI--YQM----KAV
*
>P1;Tft1
VDTGSSV--DVL---F-YD-------A-FK------------R------T
-G--H-LDSKLQ----GRKT------------------------------
------P-LTG-F-AGDTF------SIG----------T-IQ-LPTI---
--------ARGVR-------------QLT-N-----------FL-VVDK-
-----KA---------------------------------------PFNA
ILGRP-WL--HVM----KAV
*
>P1;Orizacinful
IDGGSAL--NIL---F-AK-------T-LD------------D------I
-Q--I-PRTELK----PSSA------------------------------
------P-FHGVI-PGLSS-----TPLG----------Q-IT-LLVT---
---------FGTREN-----------FRTENIC---------FE-VADF-
-----KT---------------------------------------TYHA
ILGRP-AL--AKF----IAV
*
>P1;RIRE2
IDGGSAL--NIL---F-AK-------T-LD------------D------M
QI----PRSELK----PSNA------------------------------
------P-FHGVI-PGLSA-----TPLG----------Q-IT-LPVT---
---------FGTREN-----------FRTENIS---------FE-VADF-
-----ET---------------------------------------AYHA
ILGRP-AL--AKF----MAV
*
>P1;Legolas
FDSGATH--CFVS--P-EL---------VE------------T-------
-G------GFRKE---PNTD------------------------------
----Y-GMVRA-A-GGQAM----YPTGL---------VRGIS-VVV----
---------NGV-------------NM--PAD----------LI-IVPL-
------K---------------------------------------KHDV
ILGMD-WL--GKYKAH-IDC
*
>P1;T32022.14
FDSGATH--SFVS--P-RM---------IG------------K-------
-G------KFQKE---PRMD------------------------------
----P-TVVNA-A-GGQAM----IPEGQ---------VCGIP-VSI----
---------KGI-------------EM--PVD----------LI-IIPL-
------E---------------------------------------KHEV
ILGMD-WL--GKYKAT-LNC
*
>P1;Tma
FDSGASH--CFIT--P-ES---------AS------------R-------
-G------NIRGD---PGEQ------------------------------
----L-GAVKV-A-GGQFV-----AVLG--------RTKGVD-IQI----
---------AGE-------------SM--PAD----------LI-ISPV-
------E---------------------------------------LYDV
ILGMD-WL--DHYRVH-LDC
*
>P1;Del
IDTGSTH--SFIT--P-RI---------I-------------K------M
-L------EIPVQ---PLGY------------------------------
------ILSVISP-IGTST-----FVNQ---------VCKGCMITI----
----------GNQ------------EL--TVD----------LI-ILDL-
------E---------------------------------------DPDI
LLGMD-WL--AAYHVV-LDC
*
>P1;Peabody
IDTGATH--SFIS--L-DC---------AV------------K------L
KL------EISLE---MFGS------------------------------
----M-VIDTP-A-KGSVT-----TTS----------VCLNCPLSI----
---------FGR-------------DF--GMD----------LV-CLPL-
------V---------------------------------------QIDV
ILGMN-WL--VFNRVS-INC
*
>P1;Retrosat-2
FDSGATH--SFIS--K-KF---------VG------------M------Y
-G---LRKEELRT---P---------------------------------
----M-RVHTP-G-NSS------TSVS----------FSPSVLIEI----
----------QRS------------PF--LAN----------LI-LLES-
------K---------------------------------------DLDV
ILGMD-WL--TKFKGV-IDC
*
>P1;Bagy-1
FDTGSSH--SFIS--E-SYA--------LL------------H-----NM
SF-----CDMPI----PLIVQ-----------------------------
T-----PGSK--W-ETS--------RIT--------YDNEILVYRL----
-------------------------VF--LAS----------LL-ALKS-
------L---------------------------------------DINI
ILGMD-WMS-AHY-AK-IDT
*
>P1;Monkey
VDTGATH--NFIA--D-RE---------AQ------------R------L
-G-----LTLEKS---PSRM------------------------------
----K-AVNSE-A-RRIS------G-L----------AKGVP-IKI----
----------GT--------------WGGNTN----------MM-AVPL-
------D---------------------------------------DFQV
ILGME-FM---HAAKL-VPM
*
>P1;Tntom1
IDTGATH--NYLA--L-TH---------VE------------C------L
-G-----LVVGKGR--G-HV------------------------------
----K-GINSP-P-QPVG------G-I----------ANEVP-VKLW---
----------GR--------------YEGNFN----------LR-VVII-
------D---------------------------------------DFEL
IVVLE-FL---RQTNT-MPI
*
>P1;Gloin
LDSGATH--NFIT--P-KV---------TE------------KT-----K
SG-----TQRAK--------------------------------------
------G-FNI-K-LGTSI--MVQGSG---------VSKDVH-FTV----
---------QGH-------------EF--VND----------FI-TLEL-
------G---------------------------------------NVDL
ILGIA-WH---KTMGDSNAN
*
>P1;Ifg7
IDSGSTH--NFIH--C-MV---------A-------------K-------
-------ELNFLY---PTAE------------------------------
------CQVMV-A-NGGTI----NCSG-----------KCHN-IKL----
---------SME--------------YV-LTS----------PMLSIPM-
------G---------------------------------------GADV
VLGVQ-WL--SLGTTT-FNF
*
>P1;Reina
VDSGSST--SFMS--D-HL---------MG------------K------V
TG-----VQSILE---P---------------------------------
------VQVKV-A-DGRCL--WSKYFVP---------G-CQW-LCG----
----------GIT-------------F--HTD----------FK-FLPL-
------S---------------------------------------GYDI
ILGMD-WLE-AHS-P--MKV
*
>P1;Galadriel
VDTGATH--TFVD--V-KI---------AT------------K------L
-G-----LKLSKS---PSYV------------------------------
------KTVNAKA-QAIV------G-M----------AYSVS-MST----
----------GN-------------WV-GKHN----------LM-VMPL-
------G---------------------------------------DFEI
ILGID-FL--RKYQF--VPF
*
>P1;Gimli
VDSGSTH--NFMD--P-QM---------AK------------K------L
-G------CS-LL---PSDN------------------------------
------ARVRV-A-DGYNL----KVIAR---------IQNFK-WEI----
----------HNT------------TF--VAD----------FM-VIPL-
------K---------------------------------------GIDA
VLGVH-WL---KPLGP-ITW
*
>P1;Cereba
IDGGSCN--NLAS--M-EM---------VE------------K------L
SL-----TTRPH----PH--------------------------------
----P-YYIQW-F-NNS-------GKVK---------V-TRT-VRV----
----HF--SIA--------------TYSNFVD----------CD-EVPM-
------Q---------------------------------------ACSV
LLGRPCQFD--KNYVHPGRT
*
>P1;CRM
IDGGSCN--NLAS--S-DM---------VE------------K------L
AL-----TTKPH----PH--------------------------------
----P-YHIQW-L-NNS-------GKVK---------V-TKL-VRIN---
-----F--AIG--------------SYRDVVD----------CD-VVPM-
------D---------------------------------------ACNI
LLGRP-WQF-DSDCMHHGRS
*
>P1;Beetle1
IDGGSCT--NVAS--S-SM-------VE--------------K------L
NY-----PTFSH----PK--------------------------------
----P-YKLHW-L-ND--------GTVW---------R-YKQ-ALIS---
-----F--SFGD-------------SYNDKVL----------CD-VVPM-
------N---------------------------------------ACHI
LLGRP-WQS-DKETKHNGRT
*
>P1;Tse3
ADTGASH--NFIE--Q-RF---------IQ------------G------M
-G-----LVKQRL---PEQS------------------------------
------VVKGA-L-NTS-------G-LI----QHYVRLKFKHNKDL----
--------------------------Y---EE-I--------FL-IIDS-
-----PL---------------------------------------PQPV
VFGIG-FFK-QH-----PEI
*
>P1;Dane-1
LDTGADGK-RFID--Q-EW-------VEDN------------H------L
EL-----LPL-KN---P---------------------------------
------IHLES-F-DGRES---EEG-PI----THYVRIN-LTIYDY----
--------------------------Y---EKKAC-------FL-AIQL-
------A---------------------------------------HYPI
ILGMP-WLE-TH-----ARW
*
>P1;Cgret
IDSGSEG--DFVS--P-RA-------VNKL------------R------I
-P-----WHEKRQ---P---------------------------------
------YQLNN-V-EGEQV-QYEGGTI-----KNET-AP-LEMSYL----
-------------------------DR---NEQLQ-------LD-ITNI-
------G---------------------------------------EYDL
VLGMP-WLE-KNNPR--IDW
*
>P1;Cft-1
IDSGASG--NFAS--E-SF-------VTRN------------R------I
-A-----TCKKKE---G---------------------------------
------YELIA-V-DGSSL-----PSV-----ERET-IP-LP-LAI----
----------Q--------------RH--HEE-IT-------LD-VTDM-
------A---------------------------------------SHDI
VLGMP-WLR-KHNPV--IDW
*
>P1;Skippy
VDSGADM--NFIS--P-TT-------VNEL------------R------L
-P-----WKDKND---P---------------------------------
------YTVHD-G-QGETY-LYENGNI-----TRE--IDHLK-VFV----
----------N--------------GK---NQGID-------FD-IIPV-
------W---------------------------------------RYDL
VLGYP-WLL-RYNPQ--FNW
*
>P1;Ty3-1
FDSGSPT--SFIR--R-DI-------VELL------------K------Y
EI-----YET------P---------------------------------
------P-LR--F-RG-FV-ATKSA-V-----TSE--AVTID-LKI----
-------------------------ND--LQITLA-------AY-ILDN-
------M---------------------------------------DYQL
LIGNP-ILR-RY-PK--I-L
*
>P1;Pyret
LDNGAQG--NYIS--P-RV-------VAKR------------R------I
-P-----WQQKKE---P---------------------------------
------YQLQT-V-EKKAV-LYGNGTI-----KIET-VHLWM-ESY----
----------G--------------RK----EQIT-------LN-ITEI-
------G---------------------------------------DKNV
ILGIP-WLK-KSNPR--IDW
*
>P1;marY1
LDSGATG--LFID--S-HL-------VQQH------------R------L
NT-----RSLSR----P---------------------------------
----I-PVYN--V-DGSPN---EAG-A-----IREV-AD-LV-LRY----
----------K--------------DH---SERA--------LFAVTQL-
------G---------------------------------------KQKA
ILGYP-WLR-DHNPE--VDW
*
>P1;Maggy
TDCGAEGK-CFLD--Q-GW-------AEER------------Q------L
QM-----YPLRN----P---------------------------------
------FDIEV-F-DGRTA---ESGKC-----THYVR---GQ-LRI----
----------K--------------DH--IQKNA--------LFFVTQL-
------A---------------------------------------HYPI
VLGMP-WLK-QHDPT--IGF
*
>P1;Real
VDSGCLC--YSL--------------VN-K------------K------F
AY-RH-RLERFQI---P---------------------------------
----V-RIIEG-V-NG-KL----SE-I------NEV-AR-FS-FKL----
---------HG---------------H---EETA--------YAYVMDL-
-----SF---------------------------------------GEDI
YLGRG-WMN-HNNVS--V-A
*
>P1;MGLR3
IDTGANG--YVFI--S-KQ-------LA-R------------R------L
-YTTL-KAPKIVGFH-P---------------------------------
------QKVGG-Y-DG-KA----SQQID----TAAL-AT-F--V-I----
---------QG--------------RR--FRETP--------ML-VLDM-
------P----------------------------------------QEM
IVGRL-FLA-EHGIL--TDC
*
>P1;Grasshopper
VDSGCEC--YAAM-SD-KC-------ATRL------------R------I
----E-RIPLPQ----A---------------------------------
------RHVGT-A-VG-RA----QPMI------REL-AK-CE-MDV----
---------DG-------------------WVTP--------MLFYIVP-
-----GL---------------------------------------ARDV
ILGLP-WMT-HRRIS--LDA
*
>P1;Pyggy
VDCGCLC--YAL--------------VN-K------------K------F
-AYRH-HLERFQI---P---------------------------------
----A-RLIEG-V-NG-KL----SE-I------HKV-AR-FS-LRM----
---------HG---------------H---EEIA--------YAYVMDL-
-----SS---------------------------------------EEDI
YLGRG-WMD-HQDVT--VAP
*
>P1;Sushi-ichi
IDSGADE--SLMD--F-S---------L-A------------R-----QA
-G-----IPLV-----PLDRS-----------------------------
------LSPQA-I-DGRSL-----GNI-----THRT-IP-LT-LTL----
---------SG--------------NH--IESTP--------FL-VLHA-
------P---------------------------------------TAPL
VLGRP-WLE-RHDPH--ISW
*
>P1;FLJ38865
VDSGSYR--NSID--H-TV-------VLRE------------K------L
-P-----IRSNIF---P---------------------------------
------LMLET-V-DGHPL---INGPI-----TKET-SP-VQ-VQI----
----------G--------------NH--VEELQ--------FD-IIHA-
------P---------------------------------------RYPL
IIGIH-WLE-THDPN--IEW
*
>P1;AfRTL-1
IDSGATN--NFMS--P-RY-------RENM------------K------I
EG-----RQKENAE--P---------------------------------
------L-L-G-L-DGQKL---GTGQV-----SVET-VP-VT-MAV----
----------G--------------QH--VESIA--------FD-ITPL-
-----GN---------------------------------------KYDV
VLGIS-WLE-DHNPT--IDW
*
>P1;Skipper
LDTGSNV--SLIN--K-RL------ISKDM------------K------N
HV-HK-TKAKINF---P---------------------------------
------L-LDV-K-EE-FV-EQINIQV-----NNE---------------
-------------------------IH--NFFIIE-------LD-IIDV-
------L---------------------------------------FGND
ILKDS-IIN-QKDKI--IKL
*
>P1;TF2
IDTGAQA--NIIT--E-ET-------VRAH------------K------L
-P------TR------P---------------------------------
----W-SKSVI-Y-GG-VY-----PNK----INRK-TIK-LN-ISL----
---------NG------------ISIK---TE----------FL-VVKK-
------F---------------------------------------SHPA
AISFTTLY--DNN----IEI
*
>P1;TF1
IDTGAQV--NVIT--E-ET-------VRAH------------K------L
-P------TR------P---------------------------------
----W-LQSVI-Y-GG-VY-----PTK----INRK-TTK-LI-INL----
---------NG------------ISIK---TE----------FL-VVKK-
------F---------------------------------------SHPA
AISFTTLY--DNN----IEI
*
>P1;Cer1
LDSGASI--SLM--SK-NT---------WE------------K---IVEV
NG-----KSWEQDQIYEELEY-----------------------------
------KTART-A-NNQLF------TLL------R--AV-M--VEI----
---------KMQ-------------TK-SEV-----------IKFHIGD-
----MDR---------------------------------------E-NV
IIGAG-HFEQM-GIQ--MN-
*
>P1;Cer2
VDTGANI--TVA--SR-N----------IL------------K------G
LG-----IVRLQAA--DN--------------------------------
------DNAVG-F-GGNEV-----SMIG--------SAI-VR-FQI----
----------GSQVV---K----QRVHFTN------------GH-CMPD-
----IDG---------------------------------------SYQF
IFGND-LLSRL-PIFM-FDY
*
>P1;Cer3
VDTGANI--TVT--SK-D----------LL------------K------G
LG-----ISRTLPM--LN--------------------------------
------AQAVG-L-GGHTV-----DMVG--------SAV-VQ-FKI----
----------GTHTI---D----HRVHFTT------------GR-CMPE-
----ING---------------------------------------EYQF
IIGND-MLSKL-PMFV-FNY
*
>P1;Cigr-1
LDSGASD--NFL---N-KKV--------AH------------R----LNL
RV-------EK-----SSA-------------------------------
------VIGMA-T-NGLSA-----TTQGRA-------SAS---ISL----
---------LG---------------RD-YTNV---------PFQVLDG-
-----LC---------------------------------------A-DI
ILGHN-FMCRHS-EVI-FKM
*
>P1;Osvaldo
IDTGASS--SFI---S-ERL--------AK------------R----LHG
GG-------VVR----ATR-------------------------------
------RRIRL-A-NGSCS------EVNSQ-------LDLK--IRL----
----------GS--------------RQ-MEV----------PLLVLP--
-----GV---------------------------------------IDDL
VLGCD-FLAGMG-TP--WNV
*
>P1;Woot
LDTGSEV--SCI---S-EEV--------WS------------K---LIE-
TG-------NKPPTL-PVTSI-----------------------------
------H-LRG-A-IGQRS-----CQVVIQC------Y-LE--IKI----
---------DE---------------HL-YPV----------VALVVKN-
-----LI----------------------------------------KPT
ILGAD-WL-NEQRAV--IDF
*
>P1;Ulysses
LDTGASV--SLL-----GQ---------GC------------RE--LVEK
LG------WEARP---YESMV-----------------------------
----R-TACMG-A-N--RP------ILGRV-------V-LP--VKY----
----------G---------------IE-RLD----------IVFYMCP-
----DLR---------------------------------------Q-EL
YLGID-FW-RAFEIA--PEL
*
>P1;Circe
VDSGANK--SVI---G-GE--------LAQ------------QL---ISS
KP------F-------NKFKS-----------------------------
------V-VRT-A-DGQTQ-----NVAGTIQ--------IPKTQRR----
---------FY---------------SRTIVDSQKSKFQ---KV-IIDF-
----FPS---------------------------------------FGNE
GLGID-KL--MR-NSN-NDF
*
>P1;Cer4
LDTVSDI--TLL---S-KGS--------WV------------K------L
-G------SPKLE---PVP-------------------------------
------HKIVC-A-NGSAL-----DVLGRTK------VS-FE-LK-----
----------G---------------VE-YVD----------YAYVSNR-
----------------------------------------------ENN-
LLGMS-WV-SHSPEM--RDA
*
>P1;Cer5
LDTGSMI--TLI---S-FKC--------WE------------K------V
-G------SPPLE---KVP-------------------------------
------HRFSC-A-NGTPM-----AVKGRCL------VK-FK-LK-----
----------G---------------IE-YTE----------YVYVCDR-
----------------------------------------------QTN-
LLGTS-WL-NLCPQM--RSA
*
>P1;Mag
VDTGSAL--SCI---S-KNV--------YD------------K------Y
F------SKEKLQA--CL--------------------------------
------LNLKF-Y-DGSII-----RPLGF--------IN-TI-VKY----
---------QG---------------VS-KML----------DLYVIDK-
------G---------------------------------------TTN-
LLGRQ-WLAELNINI--KI-
*
>P1;SURL
IDTGAQA--NLL---P-ETV--------YH------------K------L
KT------KPKLQKAKVK--------------------------------
------LTGYYEA-DI-P-------VMGRCC------VQ-VE-YK-----
----------G---------------NR-RSV----------PFLVIP--
------G---------------------------------------NRQP
LLGLRTSE-ELYLVK--RVY
*
>P1;Gulliver
VDTGSDI--TMT---S-EAT--------W-------------L------M
IG------RPVLL---PTS-------------------------------
------HKTKS-A-TEEDI-----VFLGE--------VL-LN-LT-----
----------F---------------CG-KSEFG--------KCYV-SKN
------C---------------------------------------KSD-
LLGID-WI-WKVGF---RDV
*
>P1;Cer6
LDTGSQI--TLI---N-VDS--------W-------------KE-----I
-G-----CLQK-----VT--------------------------------
------HSICC-A-NGTPM-----TVKGRVR------VN-FK-LK-----
----------E---------------VD-YTD----------YVYVCDRD
-----------------------------------------------TN-
LIGTS-WL-NHSPEM--RAA
*
>P1;CsRN1
VDTGAEV--SVL----------------PH------------K-----TP
LH-------D-----SAS--------------------------------
------YSLQA-A-NGTRI-----ATYG----------ERSLTLDL----
----------GL--------------RRAFK----------WISLLAD--
----------------------------------------------FKTP
IIGAD-FLTHYNLS---VDV
*
>P1;Kabuki
VDTGANI--SVL--------------PVP-------------KI----SK
FI------KN------PN--------------------------------
------YKLYA-A-NGTEI-----ATFG----------EKTLVLDL----
----------KL--------------RRAFR----------WNFVLAD--
----------------------------------------------VKQA
ILGAD-FLTSNNLL---VDM
*
>P1;SbCMV
IDTGATL--CFGK-----R-------KISN-------------------N
-W-----EILKQ----P---------------------------------
------KEIII-A-DK-SK-----HYIREAI-------S-N--VFL----
---------KIENKE-----------FL-I------------PI-IY---
---LHDS---------------------------------------GLDL
IIGNN-FL-KLYQPF--IQR
*
>P1;PCSV
IDTGATI--CLAQ----AK-------ILPI------------K------Y
-W-----KKMIK----P---------------------------------
------IKVRI-A-NN-KV-----IHIWYKA---------VDLVLL----
---------L-EGKR-----------FP-L------------PS-VY---
---QQDA---------------------------------------GLPL
ILGNN-FL-KLYNPF--IQT
*
>P1;BRRV
IDTGASL--CLLP----EY-------NLP-------------KQ-----L
-W-----KELKK----P---------------------------------
------ITIRV-A-DK-RE-----LQINKVA-------L-M--ITI----
---------LIEKRK-----------FL-V------------PT-IY---
---QFDS---------------------------------------GVPM
IIGNN-FL-RLYYPF--CQY
*
>P1;CYLCV
VDTGATI--CLAD--------------PKI------------KL-----K
-W-----VKMEK----P---------------------------------
------IKISI-A-DK-SV-----QEIWHRA-------E-MVEI-W----
---------IRNYK------------FV-A------------AT-VC---
---QKSS---------------------------------------GMDF
VIGNN-FL-RLYQPF--IQG
*
>P1;CaMV
VDTGASL--CIAS-----K-------FVIP------------EE-----H
-W-----VNAER----P---------------------------------
------IMVKI-A-DG-SS-----ITISKVC------KD-ID-LII----
---------AGEI-------------FK-I------------PT-VY---
---QQES---------------------------------------GIDF
IIGNN-FC-QLYEPF--IQF
*
>P1;CERV
VDTGSSL--CMAS-----K-------YVIP------------EE-----Y
-W-----QTAEK----P---------------------------------
------LNIKI-A-NG-KI-----IQLTKVC------SK-LP-IRL----
---------GGER-------------FL-I------------PT-LF---
---QQES---------------------------------------GIDL
LLGNN-FC-QLYSPF--IQY
*
>P1;FMV
VDTGASL--CIAS-----R-------YIIP------------EE-----L
-W-----ENSPK----D---------------------------------
------IQVKI-A-NQ-EL-----IKITKVC------KN-LK-VKF----
---------AGKS-------------FE-I------------PT-VY---
---QQET---------------------------------------GIDF
LIGNN-FC-RLYNPF--IQW
*
>P1;MMV
VDTGASL--CLAS-----K-------HVIP------------DD-----F
-W-----ENAPR----S---------------------------------
------IPVKI-A-NQ-SS-----ITLNKVC------RG-LK-INI----
---------AGNE-------------FF-I------------PT-IY---
---QQET---------------------------------------GIDI
LLGNN-FC-QTYQPF--IQW
*
>P1;SVBV
VDTGASM--CTAN-----K-------HVIP------------EE-----F
-W-----VNAKN----P---------------------------------
------IRARI-A-ND-SI-----MTFNKVA------EL-MQ-VQI----
---------ADET-------------FI-I------------PT-LY---
---QATT---------------------------------------KGDI
TLGNN-FC-RLYEPF--VQY
*
>P1;DMV
VDTGAGL--CLAS-----K-------YIIP------------EE-----L
-W-----ENSPNT-------------------------------------
------IQVTV-A-NQ-EK-----VYLTKVC------KN-LN-IYI----
---------AGEK-------------FT-I------------PT-IY---
---QQET---------------------------------------GIDI
LIGNN-FC-RLYNPF--IQW
*
>P1;CYMV
LDTGATTC-CIDS-----R-------SVP-------------KD-----A
-LE----ENSFV--------------------------------------
------VNFSG-I-NS-KQ-----QVKQKLK-------T-GK-MFI----
----------NEHY------------FR-I------------PYCYSFEM
---QIGD---------------------------------------GIQL
ILGCN-FI-RSMYGG--VRL
*
>P1;CSSV
LDTGATTC-CINI-----N-------SVPQ------------T------A
-IE----QNTFL--------------------------------------
------VQFRG-I-NS-TQ-----SVDKKLK-------Y-GR-MTI----
----------SNHQ------------FR-I------------PYCYAFPL
---SLGD---------------------------------------GIEM
ILGCN-FI-RGMYGG--LRI
*
>P1;TBV
IDTGATVC-CI-S----EK-------IVPE-------------------A
AKE----QLNYK--------------------------------------
------VNISG-I-SS-QQ-----QIQHRLK-------R-GT-LEI----
----------ASNK------------YA-L------------PLCYIIEL
---NDKD---------------------------------------DFSM
ILGCN-FF-KHMGGG--MRF
*
>P1;KTSV
LDTGATV--CVCS----EE-------MIP-------------K------E
IRE----PSKTN----T---------------------------------
------V-IRG-V-NGAN------KVTEVLK-------D-GR-LWV----
----------GDQY------------FR-L------------PRTFVMP-
---KLSD---------------------------------------GLHI
ILGMN-FI-SSMEGG--IRI
*
>P1;BSV
LDTGATV--CVAD----ER-------MIP--------------------S
-GM---KEQAKN----K---------------------------------
------IIIRG-V-NG-VT-----EVNEVTS-------A-GK-LWV----
----------GKQW------------FY-L------------PQTFIMP-
---SLAD---------------------------------------GVHM
IIGMN-FI-RTV--G--LRI
*
>P1;SBV
LDTGATRS-CINQFIE-EK------FLQPT------------K------F
-K------------------------------------------------
------VKIHG-V-NS-VT-----KLDRQVK-------D-GAKLWA----
----------GENW------------FR-L------------PITYVGPM
---YMGE---------------------------------------KTQM
LIGCN-FM-QSLAGG--VRL
*
>P1;CVMV
FDTGANI--CICK----KK-------VLPD------------E------L
-W-----HKTEN--------------------------------------
------LVLRGFN-DEKHV-----AEYRADN---------IT-IMI----
----------AKEK------------FI-I------------PYIYAM--
----DEM---------------------------------------SPDI
IIGAT-FY-NKYSP---IEL
*
>P1;RTBV
IDSGSTH--NIIC----PL-------LVP-------------E------I
-W-----VKSLN----L---------------------------------
------DIVMTTI-DNSKY-----SLNRGLH-------DEVK-IQF----
--------KEVDES------------FG-IKYSL--------GQTYVAP-
----KPT---------------------------------------GT-F
IIGHR-FM-TSEHGS--ITI
*
>P1;HMS-Beagle
IDTGSNK--NYI---Q-PN----------L------------VTNA---I
-P--------------NNK-------------------------------
------PYIADTP-GGDVK-----ISHY----------KRAS-L------
--------------------------FDFEIK----------FF-LLPT-
----LKT----------------------------------------FDA
ILGKD-TMKGMGAQ---IDL
*
>P1;Yoyo
IDTGSNK--NYI---Q-PN---------LV------------KNS----I
PN--------------NDI-------------------------------
------FYATS-V-GGKIK-----IT------------H-HTFIDL----
---------FGL--------------KDENLK----------FF-VLPT-
----LKS----------------------------------------FHG
ILGND-SLKQLEA----IIF
*
>P1;Gypsyvir
IDTGAAK--NYV---K-PL--------TEL------------KTI----T
PV--------------AKS-------------------------------
------FSVNS-I-HG--------STEIK---------R-KCLMNI----
--------------------------FQHTSP----------FF-LLDT-
----LSS----------------------------------------FDA
IIGFD-LLTQAGVK---LNL
*
>P1;Burdock
IDTGASK--NYI---Q-PL--------PEL------------KNI----M
PV--------------QNK-------------------------------
------FTVKS-L-HG-C------NT-V----------KQKC-F-I----
---------KL---------------FNTSVQ----------FF-ILPS-
----LSS----------------------------------------FDA
IIGLD-LLKQ-GNA--TLDF
*
>P1;Nomad
IDTGANK--NFI---S-RR---------LA------------AGC----T
TV--------------RKP-------------------------------
------FSVLS-A-AGNIM-----IT------------H-R--LVG----
---------KFFKPL-----------GNDSDIT---------FF-VLPN-
----LHS----------------------------------------FDG
IIGDD-TLKDLKAI---VDR
*
>P1;Gypsy
IDTDAAK--NYI---R-PV--------KEL------------KNV----M
PV--------------ASP-------------------------------
------FSVSS-I-HGST-------E-IK---------H-KC-L-M----
---------KVF--------------KHIS-P----------FF-LLDS-
----LNA----------------------------------------FDA
IIGLD-LLTQAGVK---LNL
*
>P1;297
LDTGSTI--NMI---N-EN---------IF------------C------L
PI--------------QNSR------------------------------
------CEVLT-S-NG-P------IT-L----------N-DL-IML----
----------PRNSI-----------FKKTEP----------F--YVHR-
----FSN---------------------------------------NYDM
LIGRK-LLKNAQSV---INY
*
>P1;17.6
IDTGSTV--NMT---S-KN---------IF------------D------L
PI--------------QNTST-----------------------------
------F-IHT-S-NG-P------LI-V----------N-KS-III----
----------PSKIL-----------FPTTNE----------F--LLHP-
----FSE---------------------------------------NYDL
LLGRK-LLAEAKAT---ISY
*
>P1;Tv1
IDTGSTI--NLM---K-TN---------RL------------NF-----P
VY--------------NET-------------------------------
------LKVHT-I-NG-V------IE-L----------K-QS-IRL----
---------GASKI------------CPSKQK----------F--YIHD-
----FSE---------------------------------------HYDV
LIGRE-YLEACQAK---IDY
*
>P1;Ted
IDTGANQ--SFI---S-PQAV-------QK------------YF-----S
NYSV------------NYDP------------------------------
------FEITN-I-HG--------VS-RNE--------HSIT-LPC----
----------FQE-------------FNETQDIKL-------F--IYH--
----FHD---------------------------------------YFDG
LIGLD-LLSKWEAK---IDL
*
>P1;Zam
IDTGSNN--SFI---D-PES--------AN------------Q------L
ECTI------------LPTS------------------------------
------TSITTAL-NS-FK-----IE-E----------K-AI-FPM----
----------PPE-------------FKTEGQ----------IT-LLKF-
---KFHS---------------------------------------YFNG
LIGMD-LLSHLEAK---VDL
*
>P1;Idefix
IDTGSSI--NII---R-EN---------FE------------N------L
EEKE------------EN--------------------------------
------LIVYT-I-KG-P------IT-L----------K-RS-III----
---------KPTS-------------VCPSAQK---------F--YIHK-
----FSD---------------------------------------NYDF
LLGRK-YLEDTKAK---IDY
*
>P1;Tom
IDTGSTI--SMM---R-KN---------FF------------S------L
PI--------------HNTE------------------------------
------CEVFT-S-NG-P------MT-L----------K-DS-ITL----
----------PSNNI-----------FRTPEQ----------F--YLHD-
----FSD---------------------------------------DYDV
LIGRK-LLNKAQGI---INY
*
>P1;Springer
IDTGAAK--NFI---R-PF--------KGL------------KGV----R
PV--------------QSP-------------------------------
------FTIHS-I-HG-V------TT-IT---------K-KC-F-V----
-----------SI-------------FNLKAT----------FF-LLP--
---DLT----------------------------------------SFDA
IVGLD-LLKQAGAS---LCL
*
>P1;412
LDTGADI--SIL---K-EN-------SDKF------------SN-----I
QI--------------TNK-------------------------------
------INIQG-I--GQQKI----QSRGQ---------TF---IEI----
--------QTGK-------------YVIPHD-----------FH-LVDK-
---NFPI---------------------------------------PCDG
IIGID-FIK--KYNCQ-IDL
*
>P1;Mdg1
IDTGAEI--SLL---K-CR-------NNNL------------ND-----L
NP--------------KNT-------------------------------
------TNISG-I--GQGTI----QSLG----------TLH--LEM----
--------CIAN-------------AAIPYE-----------FH-IVPN-
---NFPI---------------------------------------PGDG
IIGLD-FIK--KYNCI-LEF
*
>P1;Blastopia
VDTGSDV--TII---K-EA------IFKKM------------KD-----V
DL--------------NRTAT-----------------------------
------V-LRG-L--GNAST----QPIG---------CFRA--L-I----
----------KTDQ-----------VEASHN-----------VL-VVHD-
----SKF---------------------------------------SCDG
IVGHD-FIS--KFRLI-CSA
*
>P1;Micropia
FDSGAEC--SLI---K-DD--------ISS------------K------L
SG------KRI-----NNTV------------------------------
------M-IKG-I-GGGSV-----CSTL---------Q-----I-L----
--------SEVTIN------------ENIME----------ILFHVVPN-
----EEM---------------------------------------RNDI
LIGRE-ILK--QG-FY-VIL
*
>P1;Mdg3
IDSGSPI--SII---K-KS------LINET------------MK-----L
AL--------------VNT-------------------------------
------C-YFG-L--NNCIL----KTHG---------QTTCY-V-L----
---------KGSI------------KIYFR------------LI-IVCD-
----QSM---------------------------------------RYNV
ILGRD-FLT--ACNLN-LDP
*
>P1;Tas
FDSGSQK--SYIT-----------TRL-AN------------R------L
-R-----LNTTPQ-------------------------------------
-------KLSIST-FGDC--AP----QII------Q-SN----RT-----
------------V-------------IS-VQ-----------LQN-GT--
---RKAVRVSTIKRI-TSNLEVIGDNIEAHF-GDLKPSELPRKIRS-PDI
LIGHDYFSDFIPLTG--IKR
*
>P1;31196163
LDQGSQS--NFIT-----------ERL-AQ------------Q------L
-K-----LKRLRM-------------------------------------
-------SRPLSG-IGAV--AVTATSMVS------T-SI----RSR----
---------VSDF-------------QAGLQ-----------FLVLP---
---------KVTSDY-PSQM--VEVNRWNIPSGIALADPTFNKPER-IDI
LIGAGLFAELLGEGK--IRL
*
>P1;31232486
LDNGSQL--NFIT-----------ERV-AQ------------E------L
-R-----LKRARV-------------------------------------
-------SEQIAG-VGGA--IMRVAGS-V------V-GTI---RSL----
---------TTEY-------------TTCLE-----------FLILP---
---------KIATDL-PSET--MDVRGWKLPKDVRLADPTFHERGS-IDM
LIGADTFVEMIKAKK--IKL
*
>P1;31232862
IDSGSQV--DAIT-----------TDA-AQ------------R------L
-R-----LPLTPG-------------------------------------
-------YLILNG-VSGN--IQITNKT-Q------V-SIT---TTN----
---------GTYR-------------RQLNM-----------YLLPG---
----------LN-DQ-PTRV--IEYAESELPPMNSLADARFSYPGS-IDA
ILGAGVFFDAL-RSG--VRQ
*
>P1;31230427
LDEGSSV--TLME-----------HRL-LK------------E------L
-G-----LEGESK-------------------------------------
-------PLCLSW-TGGQ--NREESDSVE------T-SIM---IS-----
---------GT-R-------------KGDRR-----------FDMHA---
-------VRTVRTLGLPPQSADGCDISARYKHLQSLPLPSY-VSAV-PRL
LIGIDNYSLSRPLKT--VEG
*
>P1;31229813
LDSASQL--NIVT-----------ERL-VQ------------R------L
-R-----LPRIKE-------------------------------------
-------VYSISG-IGES--KIMSYSSVM------V-SIK---SN-----
---------CSAF-------------RTTSN-----------FHV-LS--
---------QVTRNL-PHNMNHLRKILKVLKKNGFVANHSKLKALN-PYI
EAGILRVGGRLRHAE--VPN
*
>P1;Tram
LDSASQA--NFVT-----------SRL-AD------------Q------L
-Q-----LDHRSS-------------------------------------
-------YVHISG-IGDS--ILP--SSKS------V-HIV---VQ-----
---------SQDA-------------SYRAS-----------FAAIV---
-------TNSITEMQ-PNFG--LDAKDWPMPNNLKLADPNFSKPQR-IDL
LIGSGLFFDLMCVGQ--IRL
*
>P1;4481821
IDSGSQS--TIIS-----------EES-AQ------------I------L
-K-----LKKFRS-------------------------------------
-------HTEISG--VSS--TGTCISKNK------T-VIS---IR-----
----------NSP-------------KNLEI-----------EALIL---
--------PKLMKAL-PVNT--INVDQKKW-KNFKLADPDFNKPGR-IDL
IIGADVYTHILQNGV--IKI
*
>P1;Bel
LDTGSTI--TLAS-----------ESF-VQ------------R------I
-G-----VRRTHA-------------------------------------
-------RISILG-LAAN--SAGV-TRGR------A-HIK---LRS----
---------RHSG-------------QTVEL-----------VSFIL---
-----TSLTSSL----PAQVIDTSSSTWRQICELPLADPTFCTPGA-IDV
IVGSDQLWSLYTGDR--KHF
*
>P1;Pao
LDDGSTV--TLID-----------EII-CK------------K------T
-G-----TTGPID-------------------------------------
-------PLHIQA-INNI--KSTETRSRR------V-NLT---LR-----
---------GLNS-------------RKEII-----------QARTVN--
---DLQVTAQKI----PKEQIDEYSHLQDISDIITYENA---KPG----I
LIGQD-NWHMLLASK--VRR
*
>P1;cer12
VDSGASL--SLI------------VHDTAI------------Q------I
-G-----LT-SVG-------------------------------------
-------SASLSL-QGFH--DESTSVSHI------F-PLR---LK-----
---------IHNS-------------VMSMG-----------FLIAGH--
---AQLPSTQFLAPV-LSDNDKNCLDLLKIDHRSITAQKTH-NGKP-IDM
ILGNDVLASLYADSH--TKR
*
>P1;cer11
LNHCELI--SHL-------------K--AK------------Q------V
-G-----LI-SSG-------------------------------------
-------SAKLSL-QGFH--EASTSISKI------F-KIS---LK-----
---------NKHS-------------SESVG-----------FLIAGY--
---SDLPATAFRAPA-FSDQDAHHLDSLEIDHLSISSQRTF-DGKR-IDM
ILGNDVLTCLHGDRH--TRR
*
>P1;cer10-1
ADLPTATL-CKI------------VQSPPN------------NTQ----S
-I-----SQFVRV-------------------------------------
-------TNHI-A-TGNS--IL--IISII------L--LS---VK-----
---------LRNF-------------FNCTR-----------FFIKGL--
---ENMPTTSFTAPK-FSANAQAFLLENGCNPYETQAQERL-NGPP-MEA
VLGSDVIAWLESDAH--TKR
*
>P1;cer8
VDSGASI--SLL------------AHDCAE------------KLK----M
KIL----ATTKVY-------------------------------------
--------LSGFN-GATT------QMSHV------F-KLQ---LR-----
---------KRAS-------------QSKLT-----------LMLAGI--
---EHMPKSPYKAPV-FSEEDRTYMENNNINHSEITSTAKL-DGRR-IDM
VLGNDLLAWLNANQD--TKK
*
>P1;Cer9
AN-GSAAP-AVF------------EL--AG------------K------A
-G-----IWDKTSNK-----------------------------------
--------RFWAG-RGT-------NVPRP------L-STA---VL-----
---------PPAS-------------NVSDS-----------FHT-HS--
---TLSPTS---AIPTINPLLTFLPTFSDSAHFEITSTNIY-NGRR-IDM
ILGNDLLAWLNANPE--TKK
*
>P1;cer7
LDTGADQ--SYI------------KANIAK------------DWK----L
-P----KVDEKTLR------------------------------------
-------LQTF-G-SG-K--AQPEKIFER------S-KIE---L------
----------ETD-------------GQKIS-----------MIV-LH--
---SE-YLT-GKIKATMTNEDLKFALTKQLQINKECFETRV-E----PDI
IIGCDHIAEIWR-----GDF
*
>P1;Copia
LDSGASD--HLI---N-DE-------SLYT------------DSVE-LVP
PL------------------------------------------------
-------KIAVAK-QGEFIY---ATKRGIV----------R--LRN----
---------DHE-------------ITLE--D----------VLFCKEA-
----------------------------------------------AGNL
-MSVKRL-QEAGMS---IEF
*
>P1;Yokozuna
IDSGASQ--NLV---I-DSYE-----KYM-------------SNIE---Y
LE--------------TK--------------------------------
------TKIYV-A-NGQYLF---SSKKGIL----------N--VKY----
-----------NN------------LPI-KIE----------ALLVKGL-
----------------------------------------------SHNI
-LSVKKL-LEKGNS---VRF
*
>P1;Ty4
IDTGSGV--NIT---N-DK-------TLL-------------HNYE-D-S
NR--------------ST--------------------------------
------RFFGI-G-KNSSVS---VKGYGYI----------K--IKN----
---------GHNNT-----------DNK-CLL----------TYYVPEE-
----------------------------------------------ESTI
-ISCYDL-AKTTKM---VLS
*
>P1;Lusen
LDSGSPY--HLT---C-DR-------SLL-------------HNYV---P
AG--------------AP--------------------------------
------KQIKW-G-NNQLAD---VMGTGQL----------L--LRTR---
---------DGES------------IWL-R-N----------VLHVPSS-
----------------------------------------------GLTL
-MSVDLL-VTLGCS---VTF
*
>P1;Tnp2
LDTGTTN--HMS---G-SR-------AAFV------------KLDT-A-V
LG------------------------------------------------
-------TVRF-G-DDPVAR---IEGHGTV----------VF-VCKN---
----------GK-------------LRS-FSD----------VYYIPQL-
----------------------------------------------TTNI
-VSLGQL-DEARYK---VSI
*
>P1;Opie-2
VDSGCSR--HMT---G-EA-------KWFT------------SLTR---A
SS--------------DE--------------------------------
-------TITF-G-DASSGR---VMAKGTI----------K--VNDK---
--------------------------FM-LKD----------VALVSKL-
----------------------------------------------KYNL
-LSVSQL-CDENLE---VRF
*
>P1;Endovir
FDSGASR--HMT---G-SQ-------ANL-------------NNYS-S-V
KE--------------S---------------------------------
-------NVMF-G-GGAKGR---IKGKGDL----------T--ETEK---
--------------------------PH-LTN----------VYFVEGL-
----------------------------------------------TANL
-ISVSQL-CDEGLT---VSF
*
>P1;ToRTL1
MDSGCSK--HMI---G-DV-------KNF-------------LSLK-T-L
QG--------------G---------------------------------
-------GVSF-G-DGKNGY---ILGVGKV--------------------
----------G---------------RS-LEDSIDN------VYHVDGL-
----------------------------------------------KYSW
-LSVSQI-CDKGNE---VKF
*
>P1;Sire-1
LDSGCSR--HMT---G-VK-------EFL-------------VNIE---P
CS--------------TS--------------------------------
-------YVTF-G-DGSKGK---ITGMGKL-------------VHD----
----------G-------------------------------LRYV--K-
----------------------------------------------EXDR
-AA--Q--CTRQDK---MSN
*
>P1;Ty1
LDSGASR--TLI---R-SA-------HHI-------------HSAS-SNP
-D------------------------------------------------
-------INVVDA-QKRNIP---INAIGDL----------Q--FHF----
----------QDN-------------TKTSIK----------VLHTPNI-
----------------------------------------------AYDL
-LSLNEL-AAVDIT---ACF
*
>P1;Ty2
IDSGASQ--TLV---R-SA-------HYL-------------HHAT---P
NS--------------EI--------------------------------
-------NIVD-A-QKQDIP---INAIGNL----------H--FNF----
----------QNGTK------------TS-IK----------ALHTPNI-
----------------------------------------------AYDL
-LSLSEL-ANQNIT---ACF
*
>P1;Osser
LDSGAIY--HVT---P-DA-------RSL-------------RDYK---P
CD--------------PI--------------------------------
-------PLKC-G-GGEVHY---AVGYGDLLVEVVKEQTDCYSFHI----
----------GNNYY---HK-QKGPVVIKIRN----------VYYVPGF-
----------------------------------------------KFRL
-LSLKQL--TNNG----AQF
*
>P1;BARE-1
LTSGLVM--NLN---N-CYL------VPA-------------LSMN--II
SG--------------S---------------------------------
-------CL-L-R-DGYSFK---SENNG------------C-SIS-----
-----------------------------MSN----------IFYGHAS-
----------------------------------------------NVRR
-LFILNLGSDNTH----IQN
*
>P1;Tnt
VDTAASH--HAT---P-VR-------DLFC------------RY-----V
AG--------------DFG-------------------------------
-------TVKM-G-NTSYSK---IAGIGDI----------C--IKTNV--
----------GCT-------------LV-LKD----------VRHVPDL-
----------------------------------------------RMNL
-ISGIAL-DRDGYE---SYF
*
>P1;Ta1-3
LDSGCTS--HMS---A-RR-------DWFC------------SFR----E
DG--------------GPT-------------------------------
-------IL-L-G-DDHSVK---SQGQGSI----------K--IETHG--
----------GTI-------------IG-LEN----------VKYVPEL-
----------------------------------------------RRNL
-ISTGTL-DKRGIKH--EGG
*
>P1;Tto1
IDSGATI--HAT---P-RR-------ELFS------------SY-----T
LG--------------DFG-------------------------------
-------RVKM-G-NANFST---VVGKGDV----------C--LETMN--
----------GMK-------------LL-LRD----------VRHVPDM-
----------------------------------------------RLNL
-ISVDKL-DEEGYC---NTF
*
>P1;Evelknievel
LDSGATH--HLT---S-DLN------NLAL------------HQP----Y
NG--------------GE--------------------------------
-------EVTI-A-DGSGLP---ISHSGSA----------L--LPTP---
----------TRS-------------LD-LKD----------VLYVPDI-
----------------------------------------------QKNL
-ISVYRMCNTNGVS---VEF
*
>P1;Hospcotch
TDTGATD--HIT---G-DLD------RLTM------------HDK----Y
TG--------------TD--------------------------------
-------QIIA-A-NGTGMT---ISNIGNA----------I--VPTS---
----------SRS-------------LH-LRS----------VLHVPST-
----------------------------------------------HKNL
-ISVHRLTNDNDVF---IEF
*
>P1;Sto-4
IDSSATV--HVA---N-SL-------QGL-------------RTSQ-RLP
KG--------------RR--------------------------------
-------TIRV-A-NGVEAA---VEAIGDI----------H--LKLVN--
----------GFV-------------LL-LRD----------VLYVPSL-
----------------------------------------------RRNL
-ISVSRLDDQHIH----CHF
*
>P1;Retrofit
IDTGATD--HIT---G-ELE------KLTT------------KEK----Y
NG--------------GE--------------------------------
-------QIHT-A-SGAGMD---ISHIGHT----------I--VHTP---
----------SRN-------------IH-LNN----------VLYVPQA-
----------------------------------------------KKNL
-ISASQLAADNSAF---LEL
*
>P1;MelmothArab
IDSGATH--HVS---H-DR-------SLFS------------S------L
DT--------------SVLS------------------------------
-------AVNL-P-TGPTVK---ISGVGTL----------K--LND----
----------D---------------IL-LKN----------VLFIPEF-
----------------------------------------------RLNL
-ISISSLTDDIGSR---VIF
*
>P1;Melmothbrass
IDSGATH--HVC---H-DR-------SMYT------------S------I
DI--------------TTTS------------------------------
-------NVNL-P-NGMIVK---ISGVGIV----------Q--LNE----
----------H---------------IT-LHN----------VLYIPEF-
----------------------------------------------RLNL
-LSISSLTSDIGSQ---VIF
*
>P1;RIRE1
MDSGATV--HIC---A-DR-------SMFS------------S------F
QG--------------FNSA------------------------------
-------PVLM-G-NGVPAA---VRGTGQV----------Y--LKLTS--
----------GKT-------------LV-LKD----------VLYVPSM-
----------------------------------------------SRNL
-ISVSLL-CRQGLK---LVF
*
>P1;Fourf
MDSGANI--HVC---A-DA-------SMFT------------S------Y
QV--------------GRS-------------------------------
-------GALLMG-NGSRAH---VLGVGTV----------I--LKFTS--
----------GKT-------------VP-LKS----------VQHVPSI-
----------------------------------------------KKNL
-VSASML-CRDGYKV--VLE
*
>P1;1731
LDSGATS--HMC---C-DR-------SVFT------------E------F
EE--------------HTE-------------------------------
-------KISLAG-NG-FLL---AKGIGTV----------K--LKTD---
----------LCT-------------LV-LNN----------VLFVPDL-
----------------------------------------------NGNF
-MSVSRA--AQYKCF--VNF
*
>P1;Ty5
FDTGCTS--HMC---H-DR-------SMFS------------S------F
TR--------------SSKKD-----------------------------
-------FVRG-V-GG-SIP---IMGSGTV--------------NI----
----------GT--------------VQ-LND----------VSYVPDL-
----------------------------------------------PVNL
-ISIWKL-CAKSNSS--VTF
*
