>P1;all7265

IDTGFNGYLTLPPQAISAMN------L-P--LHST---IPAILADGSQV-L-SSI-HLTT
IV-W--DNV-EKVVFV-LA--SANKPLLGTGMMNGYHLG-IDF
*
>P1;PAE0993

IDTGAT-Y-TVIPRR-LAEE------I-G--APRTGIYAEVKTAYG-VVKLELTH--ILL
EIEGT-RAL-E--AVL-VS-DSLEIPLIGVRTLEGLGFR-VDP
*
>P1;PAE0531

VDTGAT-F-TVLPLE-VADK------LIE--TPFT---VELKLGNGEKVVAKVYV--AEA
EIEG--RRG----PVRIVA-FKGAIPVIGVDTLETLGLR-VNP
*
>P1;AF0612

IDTGYEGF-AVVPQD-IFKK------LRL--DELSQHKRAL-TL-PTERLIESTGSYARI
IIPEL-KTFRD--GFVETTDGVDEI-VLGTEFLEGFKLV-LDY
*
>P1;SSO1395

VDTGFDGE-IIVTKE-IFDK------I-P--YNSSD-GTRICTASME-C-Y-STF----V
KLVRTKFLGREITAEVLNSPVIEKN-IIGEGLLKKVSAV-INY
*
>P1;SSO2164

IDTGFSGY-LLIPPS-VYNK------VNSLELENP---RVYATLNG-IV-KTRVA-KAII
KI-GK-IKL-DT-LIESPILGREIS-LLGRELQKILHIE-F--
*
>P1;SSO1929

VNTGFSGW-LLLNYE-IYTK------LNYMEIPIT---RKYRSILG-NI--EVYMAKASI
SI----NRL-NIDAFIESSPYVEMN-LLGREILKKLNIC-F-Y
*
>P1;SSO1523

IDTGFSGW-LLLNYE-IYTK------LNSLEIPIT---RKYRSILG-NI--EVFMSKASI
TI----NRL-NIDAFIESSPYIEMN-LLGREILKKLNIC-F-Y
*
>P1;ST0709

IDTGFSGE-IMVNYE-IFDKIPFPTFNAG-FVCIT-ENECY-AAFG-KI---ST-----L
RILG--NEI-N-TVVL-WIPQLDEN-LIGEGALIKLGLV-INY
*
>P1;RB8280

VDTGFNGF-LSIPFR-LVHQ------L-G--LPLSDVQQGV-TADG-RS---SFF--DTV
ELTVI-WHG-N--PL-TVQAQVLDEPLLGTR-LLRGSKIEAAW
*
