>P1;MAGN03006869

FDTGASSVVLTAENAAALGIRPAE-GD-FTQRVSTANGTALAAPIRLASITV-GPITERN
IDA-LVSRPGMLSTNLLGQSFLQRLPSYEV
*
>P1;BLL3736

IDTGATSVVLTWETAKAIGLPLEM-LE-YDVDLETAGGHTKAARLTLDRLAV-GHLVEKS
VPA-LVVQRGQMKTNLLGMSFLDRLESWGV
*
>P1;ATU1893

VDTGASSVVLANADAAEIGIDTGS-LR-YTVPVMTANGRTAAAPVTLSEIGI-GPIMRRN
IPALVAQ-DGQLGQSLLGMSFLSTLGSLQM
*
>P1;CC1307

VDTGATAVSLSLADAQRLGIDTSR-LT-YDYNVITADGRTRAAAVKLASVSIAGA-RVRD
VDALVIE--KGLENSLLGMSYLGRLSRFEA
*
>P1;MLR0565

VDTGATSTVLTSEDAQAAGFNPAA-LN-YTIPVSTANGMARAAAVKTDAVAI-GGIVRKD
M-PVMVAAPGMLSQSLLGMNFIGSLSGFDV
*
>P1;RC1339

VDTGASDIALTKEDAQKLGFDLTK-LK-YTRTYLTANGENKAAPITLNSVVI-G-KEFKN
IKGHVGL--GDLDISLLGMSLLERFKGFRI
*
>P1;MMC12119

VDTGASAIVLAPQVLSRLGLDRRK-LR-FTQPFQTANGQVFNAPVILQDVQL-GDLHLQR
VPA-VVN-QTAMDNSLLGMSFFKRLKSYRV
*
>P1;Rsph03003184

ADTGASSIVLSQADARRLGIEPDR-LD-YMGEAITANGPVRTARVRIGPVVL-GPYSEQR
IPA-WVN-EGPMDMSLLGMDYLRRFRIEIA
*
>P1;RP867

VDTGASDIALTKEDAQKLGFDLNK-LK-YTRTYLTANGENKAAPIILNSVVI-GT-EFKN
IKGHVGL--GNLDISLLGMSLLERFKGFRI
*
>P1;PA4048

VDTGATSIAMNENEARRLGIDYRVDGK-P-MVASTASGTSRGWRVTLDRVKI-GGIELLG
VEA-AVIEGGYPTEALLGMSFLNRVR-WRE
*
>P1;MDEG2586

VDTGASSIALNSIVAKQLGIDYLTSPR-Y-VGVATASGTTRGYRVTLREVTV-GGITLNN
VIA-VVTEGEFPRDILLGNTFLSELD-MKV
*
>P1;PSPTO4961

IDTGATDVAIPGDMADSLGLKR---G--LPVTVSTANGNSQGFRTTLDRLQL-GDIVLHN
VRA-LVAPGLEGEQVLLGMSALKQLE-FTQ
*
>P1;Pflu02000192

LDTGATDVAIPAEVAKNLRLEE---G--FGVTLSTANGLSQGYRTRIDRLQL-GDIVLRD
VRA-LVAPGLHGDQVLLGMSALNKLE-FTQ
*
>P1;PA4965

LDTGATQVAVPEALAARLALER---G--APITLSTANGRATGWRTRLDQLQL-GDIRLSG
VAA-LIAPGMDGDEVLLGMSALKQLE-FTQ
*
>P1;Mdeg0200624

LDTGATDVAIPSALAKKLGLKR---G--AKGAAHTANGVTTTYRTNIDVLKL-GSITLYD
VDA-SITMGFTGDEILLGMSALKSVE-FTH
*
>P1;ATU0134

VDTGASMVAINETMARRLGYGVN--SLDFKYAISTANGQTLAAHVKLDRVEI-GAIRVQN
VDT-MVLKDNALSNMLVGMSFLKQLSSFKV
*
>P1;MLL3161

IDTGATLVAVNTSTARRIGLSLN--PSDFSHEVNTANGSIKAAVVTIDRLQI-GSISVDD
VQA-IVLDDKALSTNLIGMSFLNRLGKYQA
*
>P1;BLL8127

VDTGASVVALNETSAARFGLRPSR-GE-YNATVSTANGTIKAARTRIAMLEV-GGLVVRD
VDA-MVLPDEALSENLLGLSFLSRLKRFEY
*
>P1;RPAL1816

VDTGASVVALNESSAARFGLRPSR-GD-YKTKVSTANGQVKAARARIAMLDV-GGLIVRD
VDA-LVLPDEALSENLLGLSYLSKLKRFAY
*
