>P1;F11C18.100
--GEI--EKIL----DREWRPTASNNPNSS-------DNGTPTL-----V
VVK-QYLVKWK-----GLSY--LHCSWVPEQE----F----EK--A----
YKSHP-HL---
*
>P1;C50A2.2
--FIV--DEIT----DMRY---------STTC---------R------QL
----QFLVKWA-----IP-G--SEMTWQPLDD----FPFGLN----H---
FSIL--DY---
*
>P1;dMi-2
--GKA--EKII----TWRWAQRSNDDGPSTSK--GSKNSNSR-------V
R---EYFIKWHN----M-SY--WHCEWVPEVQ----LDV------HHPL-
MIR---SF---
*
>P1;DmCHD3
--GKA--EKIL----SWRWALDRSVELRT-----------SK-------G
EKRREYFIKWH-----GMSY--WHCEWIPEGQM---L--------LHHAS
MVA---SF---
*
>P1;CHD-4
--GKV--QKIL----IWKWGQPPSPTPVPRPPDADPNTPSPKPL----EG
RPERQFFVKW-Q----GMSY--WHCSW-VSELQ---L----E---LHCQV
MFR---NY---
*
>P1;CHD-3
--GRV--QKIL----HWRWGEPPVAVPAPQQADGNPDVPPPRPL----QG
RSEREFFVKWV-----GLSY--WHCSW-AKELQ---L----E---IFHLV
MYR---NY---
*
>P1;F26F12.7
--WRW--KEWI----PYPEPLEAGKEASSD--DAMLK-PPRKM-----EP
RREREFFVKWK-----YLSY--WQCSW-VSEML---L----E---VHFRM
LIL---LY---
*
>P1;KIAA1416
--PVV--EKIM----SSRSVKK------------------QKESGE--EV
-EIEEFYVKYKN----F-SY--LHCQW-ASIED---L----E----KDKR
IQQKIKRF---
*
>P1;Beta-catenin
--AIV--DKVL----SMRVVK--------------------KELPSG-QY
TEAEEFFVKYKN----Y-SY--LHCEW-ATISQ---L----E----KDKR
IHQKLKRF---
*
>P1;EF-3CVK2
KKI-L--DKIL-----GRR----------------------K-------L
KKSYEYEVQWK---------NDETTQW-MSRER---L----EEY-GFGK-
LLND---I---
*
>P1;MSL3-like
--FEP--DPTK-----ARVLYDAKIVVV----------IVGKDEK----G
RKIPEYLIHF-N----GW--NRSWDRW-AAEDHV--LR---DTD--ENRR
LQRK---L---
*
>P1;MSL-3
--YEP--DKSK-----ARVLYTSKVLNV----------FERRNEH----G
LRFYEYKIHFQ-----GW--RPSYDRC-VRATVL--LK---DTE--ENRQ
LQRE---L---
*
>P1;ALP13
--FHG--PLLY----EAKIVDTE-----------------MK-------G
DVTT-YLIHYK-----GWK-N-SWDEW-VEQDRI--L----Q---WTEEN
LKTQKE-L---
*
>P1;MRG15
--FHG--PLLY----EAKCVKVA-----------------IK-------D
KQVK-YFIHYS-----GW--NKNWDEW-VPESRV--LKYV-DTN------
LQKQRE-L---
*
>P1;Y37D8A.11
-TYKG---KVY----DAVITDIKP----------------DKD------G
KEC--YCIHFK-----GWN-NR-YDEQ-I----P--IGE--ETDRI----
FKGIADGY---
*
>P1;RBBP-1
--LTG--TKVKV--KYGRGKTQKIYEAS------------IKSTEIDD-G
EVL--YLVHYY-----GW--NVSYDEW-VKADRI--IW-PLDK--G----
G------P---
*
>P1;F32E10.2
--YAV--ERVL----AHR-----------------------KVK-----G
SPL--YLVQWKG----YPHPVWNSEMWE--ED----L---DNCKD-----
LLA---AY---
*
>P1;F32E10.6
--FAV--EKII----AHRFS--------------------GKK------N
KPL--FLVMWRG----YPNPVSHSEMWE-NE-----L---SNCKD-----
LLE---AY---
*
>P1;3B49
--YVV--EKIV----AHRYPND-------------------RL------N
QPL--YLVMWRG----FPDPVSNTEMW-GEE-----L---ENCQE-----
LLD---AY---
*
>P1;PDD1
--YEV--EKIL----DSRFN--------------------PK------TK
QK--EYLVKWEN----WPI---EDSTWEPYEH----L---SN---VKE--
IVQ---AF---
*
>P1;polycomb-like/carrot
--FEI--EHIR----RKRV---------------------KK-------G
EV--QYLVKWR-----GWPE--SANTWEPVEH----L----E--AVPD--
VVD---AF---
*
>P1;CEC-1
--YTV--ESIL----EHRK---------------------KK-------G
KS--EFYIKWL-----GYDH--THNSWEPKEN----I---VD---PT---
LIE---AF---
*
>P1;HP1Ce
--FVV--EKVL----NKRL---------------------TR-------G
GS--EYYIKWQ-----GFPE--SECSWEPIEN----L--QCD----R---
MIQ---EY---
*
>P1;K01G5.2
--FMV--EKVL----DKRT---------------------GK-------A
GRD-EFLIQWQ-----GFPE--SDSSWEPREN----L----QC--VE---
MLD---EF---
*
>P1;PDDp3
--YEV--EKII----KTKY---------------------DDQ------L
RTNL-YLVKWK-----GYAD--HLNTWEPEWN----L----ENS-KE---
ILN---DF---
*
>P1;CHRp
--FEI--GDIL----EIKK---------------------KKN------G
FI---YLVKWK-----GYSD--DENTWEPESN----L--------IH---
LT----TF---
*
>P1;Suv39h1
--FEV--EYLC----DYK-----------------------K-------I
REQEYYLVKWR-----GYPD--SENTWEPRQN----L----KC--IR---
VLK---QF---
*
>P1;LdPh
--FVV--EKIL--AQEFD--------------------VSTKQ------F
M----FLVKWK-----GYSM--VHNTWEPLEH----LT---HCS-L----
LLT---QF---
*
>P1;H3-K9-HMTase
--YVV--ERIE--CVEMD------------------------Q------Y
QPV--FFVKWL-----GYHD--SENTWESLAN----VA---DC--AE---
ME----KF---
*
>P1;TsCpYp2
--FEV--EAIV----DKRQD---------------------KN------G
NT--QYLVRWK-----GYDK--QDDTWEPEQH----LM---NC--EKC--
VH----DF---
*
>P1;T09A5.8
--FEV--EKIL----AHKVT---------------------DN------L
LV---LQVRWL-----GYGA--DEDTWEPEED----LQ---EC--ASE--
VVA---EY---
*
>P1;Clr4
--YEV--ERIV----DEKLD---------------------RN------G
AVKL-YRIRWLN----YSS---RSDTWEPPEN----LS-------GCSA-
VLA---EW---
*
>P1;C29H12.5
--FSE--ERFK----RTK-----------------------KPQ-----L
ISNYFFLVKWL-----GYGN--KEMTWEPESN----IP---DS--V----
YLY---EY---
*
>P1;CG18186
--YIV--EKFL----GKRYL--------------------R--------G
RP--QYLTKWE-----GYPI--EQCTWEPLEN----LGK---C--MTL--
IA----DY---
*
>P1;CG10683-PA
--YVV--EKIL----GKRFVN----------------------------G
RP--QVLVKWS-----GFPN--ENNTWEPLEN----VG---NC--MKL--
VS----DF---
*
>P1;CG8120-PA
--YIV--ERIL----DRRHYM----------------------------G
QL--QYLVKWLD----YSD---EDNTWESAAD----L----DC--HSL--
ID----SI---
*
>P1;L9MH3
--YVV--EKVL----DRRV---------------------VK-------G
KV--EYLLKWK-----GFSD--EDNTWEPEEN----L----DC--PDL--
IA----EF---
*
>P1;HP1
--YAV--EKII----DRRV---------------------RK-------G
KV--EYYLKWK-----GYPE--TENTWEPENN----L----DC--QDL--
IQ----QY---
*
>P1;MPc2
--FAV--ESIE----KKRI---------------------RK-------G
RV--EYLVKWR-----GWSP--KYNTWEPEEN----IL---D---PRL--
LI----AF---
*
>P1;POLYCOMB
--YAA--EKII----QKRV---------------------KK-------G
VV--EYRVKWK-----GWNQ--RYNTWEPEVN----IL---D---RRL--
ID----IY---
*
>P1;Monkey
--KRV--ETIL---ADRKI---------------------KLPN-----G
AEQTEYLVKWRK----LLR---TEASWEPEDA----LRHEEE---V----
IN----NY---
*
>P1;Galadriel
--AEI--EKIL----DHRVLGT-----------------SK--------K
NTKTEFLVHWK-----GKSA--ADAVWEKAKD----LW---Q---FDAQ-
ID----DY---
*
>P1;Tntom1
--L-A--EFIL-NNSDSRLK-------------------ERSP------G
V----LGFKWH-----GCDA--EENTCEGGTN----LK-------AYKG-
LLD---DY---
*
>P1;G-Rhodo
--YEV--EDIL---A-HRA---------------------K--------G
RTT-EYLVRFVS---CGP----EDDLWLPERN----LV---N---APDI-
LKA----Y---
*
>P1;REM1
--LSV--EALT---G-HRDEP------------------IRGGC-----G
KTRREYLVKYAN---DPT----DCKSYEPERN----LR-------ACPE-
LNK---MV---
*
>P1;Sushi-ichi
--WSV--NKLL--AVRRRG---------------------R--------G
F---QYLVDWV-----GYGP--EDQSWVPPSY----LA---D---PSL--
LE----DF---
*
>P1;Amn-ichi
--FEV--EDIL----DSRFH--------------------RRR------L
----QYLIDWV-----GFGP--EERSWEDAST----VH-------APD--
LTR---RF---
*
>P1;Amn-san
--YEV--EKIL----DSRLS--------------------R--------G
SL--QYLVQWK-----GFGP--EECSWEKDSD----VH-------APR--
LVK---AF---
*
>P1;Amn-ni
--YTV--RRIL----DVRQV--------------------RR--------
TR--QYLVDWE-----GYGP--EERSWVPAKD----IL---D---PKL--
IQ----DF---
*
>P1;Real
--WEI--EDIVAEEVRRR---------------------GR--------G
RKLY-YEVKWK-----GFHQ----TTLEPAEL----LK---D---AEA--
VD----RW---
*
>P1;Pyggy
--V-I--EEIM-SEKKRR---------------------GR--------S
R-LY-YEVKAR-----Y------TLTDLPGEL----LE---E---IEA--
LE----SI---
*
>P1;Grasshopper
--WAV--EAILA-AKNRR---------------------GR--------G
GGRQ-VLVKWQ-----GY----DNPTWEPLEL----MT---D---TRA--
LD----EF---
*
>P1;Cft-1
--FEV--EKIL-----DK----------------------K--------G
QR---YLVKWKG----YDE---SENTWEPRIN----LA---NC--YQL--
LR----QF---
*
>P1;Pyret
--YNV--KQIF-----DH---------------------RRNH------G
KIK--YFIKWEN----YGH---EKNIWEPLNH----LQ---DCQEP----
LR----QY---
*
>P1;Cgret
--YEV--ERII-----DHS--------------------DAF-------G
EELH-FLVKWLG----YGH---EDNTWEPQSN----LT---G---AKEE-
LE----EY---
*
>P1;Skippy
--YEA--EAIR-----DTR---------------------KIN------G
QR--EYLIKWKN----YPE---NENTWEPPKH----LV---N---AQRL-
LK----DF---
*
>P1;Bagy-1
--YLV---CIL--DQAERT--------------------NRRRN-----L
KF---LKVQWSN----HSE---KEATWEREDR----LRL--E---YPA--
F------F---
*
>P1;Retrosat-2
----V---RIL--DTSERR--------------------TRNK------V
TRF--CRVQWSH----HSE---EEATWEREDE----LKA-----AHPH--
L------F---
*
>P1;Legolas
--AWP--VRIM--DRMTKG--------------------TRGK------A
RDL--LKVLWNC----RGR---EEYTWETENK----MKA--N---FPE--
W------F---
*
>P1;Peabody
--TSP--MRIE--NPELKQ--------------------LRGKE-----I
AL---VKVAWGG----PAG---GNVTWELESQ----MK---ES--YPE--
L------F---
*
>P1;Del
--EKP--VQVL--ASESKV--------------------LRNK------I
ILM--VKVLWQH----HSE---EEATWELEAD----MQ---E---FPN--
L------F---
*
>P1;Gimli
--KEP--ARIL----KRKLV-------------------NRH-------G
RAATKVLVQWTN-EDEA------EATWEFLFD----LL---QK--YPT--
FNH---E----
*
>P1;Gloin
--MEP--EEIL----DTRYNEE---------------------------G
YL--EGLIQWK----GLSS---QENTWVIVKE----LLA--Q---FPT--
FA----LG---
*
>P1;Ifg7
--LEP--EAAT----ETRTR-------------------LRNS------I
S---EYLIKWKN----LST---EDSTWEDDNF----IQKHPE---L----
LK----RG---
*
>P1;Reina
--LES---RLL-----RKG--------------------NK--------V
IP--QLLIRWSN----WPA---SLSTWEDEHA----IKQ--Q---FPR--
AP----AW---
*
>P1;CoDi3.1
--YTF--DDIV---DHQKRPRG-----------------GRGRTR----G
WF---LRVKWAN----G------EFTWEPLTS----LK---ESN-PYP--
VA----KY---
*
>P1;CoDi4.4
--VSR--DDMY----AGKDGSNRH---------------LRRTTK----G
WK---LLIQWKD----G------TSTWERLAN----LK---ESN-PVQ--
VA----EY---
*
>P1;CoDi4.3
--VAA--DDLY---YTDKRGVKQ----------------MRRTTK----G
WQ---LLLQWKD----G------SNTWIPLKD----LK---ESN-PVD--
VA----EY---
*
>P1;CoDi4.1
--VTK--DDGF---TVLKNGER-----------------KPQMTTK---G
WK---LSVLWKD----G------TSTWVPLKD----LK---ESN-PLE--
VA----EY---
*
>P1;CoDi4.5
--LTL--EQQK----TNHNGRPS----------------IRKSTA----G
WK---LCCQWLD----G------STSWVRLSE----LK---ESH-PVQ--
VA----EY---
*
>P1;CoDi7.1
--VGG--AHVT------KIV-------------------GHNWMD----G
RLK--LKVTW------ATE----QTTWEELRD----MK---EDH-PKM--
TA----EY---
*
>P1;CoDi2.4
--WSF--KDIV-----AHEGPLLPR--------------DKNYK-----G
SRFN-VLVNWET----G------ESTYEPLDV----IGV--DD--PITC-
AV-----Y---
*
>P1;Tma
--ARP--VRVL--ERRIKE--------------------LRRKK-----I
PL---IKVLWDC---DGV----TKETWEPEAR----MKAR-----FKK--
W------F---
*
>P1;Skipper
--YEV--ESIL-----NHD---------------------K--------V
KKM--YLVKFK-----GYP----EPEW-IRE-----VDT--DC--EEL--
VR----EY---
*
>P1;Maggy
--YEV--EEILDSFWETR---------------------GR--------G
GRRLKYIVRW------AGY---SEPTTEPAD-----YL---EN--AAQL-
VK----N----
*
>P1;Dane-1
--WEV--ESILDSRWERR---------------------GR--------G
GPRLKYTVKW------VGY---DDPTEEPADT----PT-------PNSS-
YR----TS---
*
>P1;marY1
--YEV--KSIL----DSRL--------------------HR--------G
KL--QYLVHWK-----GYGY--EENSWVEESD----I----N---APRL-
IK----EF---
*
>P1;MGLR3
--WEV--ERVI----SSRVL--------------------R--------G
VL--QYQVQWR-----GWDP---DPEFYDAEG----FK---N---AAVQ-
LR----QY---
*
>P1;CAO
--YAVA-ESVI----GKRVGDD---------------------------G
KTI-EYLVKWTD----MS-----DATWEPQDN----V----D---STL--
VL----LY---
*
>P1;CHRassSWI6
--YVV--EKVL----KHRMA--------------------RK-------G
GGY-EYLLKWE-----GYDD-PSDNTWSSEAD--CSG--CKQ---L----
IE----AY---
*
>P1;FYSp
--FAV--EMIL----DSRM--------------------KKD-------G
SGF-QYYLKWE-----GYDD-PSDNTWNDEED---CAG-CLE---L----
ID----AY---
*
>P1;CHRBOXp
--YTV--DRIV----GDRK---------------------KK-------G
VK--QYLVKWE-----GYPD--SENTWEDEKN----IFS-KE---L----
IK----EY---
*
>P1;HaP1-like
--YEV--ENII----GHR----------------------KK-------G
SQI-EYHIQWK-----GYSL--KQATYEPAKN----ILD-KN--------
MLK---KY---
*
>P1;K06A5.1
--WIV--EKIQ----KMRYNG--------------------K-------L
KRV-EFLVLWE-----ADK----SKSWEPIEN----FHSGYDN-------
VEIE--RF---
*
>P1;SD06626p
--EPV--EKIV----AKRFN-------------------PRRKTHE----
-----YLVKWVD----RSH---HENTWEVMAN----L----ER--VPY--
FLQ---MF---
*
>P1;T12E12.2
--DLV--RKAL--NAEAKFSPASVE--------------YDKRRHSK--Y
A----YLVHWRG----YDW---KERTWEPEEN----L---ENCEE-----
LQ----KF---
*
>P1;ZMET5
--FVV--QKLI----GIRYDGTGR-----------------KK------G
VY---FKVQWEE----YGP---EEDTWEPIDN----L---SDC--P----
LKIR--EF---
*
>P1;CMT1
--FEV--EKFV----GIVFGDP-------------------KGT-----G
EKTLHLKVRWK-----GYSP--KYDTWEPYSG----L---GNCKEK----
LK----EY---
*
>P1;CMT3
--FTV--DKIV----GISFGVP-------------------KKL-----L
KRGLYLKVRWLN----YDD---SHDTWEPIEG----L---SNCR------
GKIE--EF---
*
>P1;F13C5.190
--YEV--EKLV----DICFGDHD------------------KT------G
KNGLKFKVHWK-----GYRS--DEDTWELAEE----LRYM-----LQNN-
VKK---RF---
*
>P1;ATCH-DNA-binding
--SQV--ERII----ADRIS---------------------KDGL----G
DVVPEYLVKWQ-----GLSY--AEATWEKDVD----IAF-AQ---V----
AID---EY---
*
>P1;GYMNOS/PICKLE
--TTV--DRIL----ACREED----------------------------G
EL--EYLVKYKE-----LSY--DECYWESESD----IST-FQNE------
IQ----RF---
*
>P1;hrp3
--KQV--DRIV----AKHLNSD---------------------------G
SV--EYLVKWKQ-----LLY--DFCTWEASSI----I----EP--IAATE
IQ----AF---
*
>P1;CG3696-PA
--TEV--DRVL--DMSVHTDETS--------------------------G
ETTKHYLVKWKS-----LPY--EDCTWELEED----V----DNDK-----
IE----QY---
*
>P1;HsCHDNABP5
--VEV--DRIL---EVAHT----------------------KDAET---G
EEVTHYLVKWCS-----LPY--EESTWELEED----V----D---P----
AKVK--EF---
*
>P1;T04D1.4
--VIV--DRVV-----DLITEDD--------------------------G
QEF--VLIKWKS-----LGY--EEVTWEPIEM----IPA--DK-------
VE----LW---
*
>P1;H06001.2
--KKV--ERVV-AHQTSRDRAAD--------------------------G
SMATEYLIKWS-----GLPY--SDCTWEDEKM----VAP--EQ-------
IK----AY---
*
>P1;HsZinc-fingerhelicase
--MTV--HRII----NHSVD---------------------KK------G
NYH--YLVKWRD-----LPY--DQSTWEEDEMN---IPEYEEHK------
Q-----SY---
*
>P1;C15H11.5
--YEV--QDIV----RSRIE-----------------------------G
REI-QYTVKWTN----WN----GGDTEEAERR----LVC-TEK-------
LM----GY---
*
>P1;CHD-1b
--YAV--EADG----DPNAGFERN-----------------KEP-----G
DI--QYLIKWK-----GWSH--IHNTWETEET----LKQ-QN---VRG--
MKKLD-NY---
*
>P1;CHD-2
--YAI--EANG--DPSGDFDTE-------------------KDE-----G
EI--QYLIKWK-----GWSY--IHSTWESEES----LQQ--QK--VKG--
LKKLE-NF---
*
>P1;DmCHDNABP
--YAI-EENGF----DPHAGFDE------------------KQTPD---A
ETEAQFLIKWK-----GWSY--IHNTWESEAT----LR---D---MKAKG
MKKLD-NF---
*
>P1;hrp1
--YEPIIDFVL--NHRKRADAQDDD------------------------P
KSSYQYLIKWQE----VSH---LHNTWEDYST----LSS------VRG--
YKKVD-NY---
*
>P1;CHD-1
--LE---KTVP----DLNN------------------------------C
KENYEFLIKWTD----ESH---LHNTWETYES----IG---Q---VRG--
LKRLD-NY---
*
>P1;T32E20.30
-FVVV-PEAVL----ETRYNED---------------------------G
LL--EALVHWQ-----GLPV--HEDTWEIAKD----LKK--Q--------
FP----GL---
*
>P1;PTEF
--RRV--EALI-----GRQ----------------------K-------L
KKSFQYEIKWF-----GKPH--KYNTW-VSREIL--L----EN--GFQK-
FVQA---F---
*
>P1;histoneacetyltransferase
--YHP--VKVI----ERR-----------------------KNYNG---G
HNDYEYYVHYTE----F---NRRLDEW-IKLEQ---L----D---LDS--
VECA---LDEK
*
>P1;ECp181-carrot
---HP--VKVI----ERR-----------------------RVPSG---G
PNDYEYYVHYTE----F---NRRLDEW-VKLEQ---L----D---LKS--
VETV---V---
*
>P1;A33_PLEWA
--LHA--AEII----KTR-----------------------KTK------
ENAEEFYVHYV-----GL--NRRQNEW-VDKSRV--L----Q---AKQ--
IKTEE--L---
*
>P1;ESA1
--ERL--AEIL----SINT----------------------RK------A
PPK--FYVHYVN----Y---NKRLDEW-ITTDR---I----N---LDKE-
VL-----Y---
*
>P1;VC5.4
--ERW--AEVI-----SRC----------------------RAAN----G
SIK--FYVHY------IDC-NRRLDEW-VQSDR---L----N---L----
ASCE---L---
*
>P1;MOF
--VHR--GQVL----QSRTTEN---------------------------A
AAPDEYYVHYV-----GL--NRRLDGW-VGRHR---ISD--N---ADD--
LGGIT--V---
*
>P1;CSAHP1M31
--LEP--ERII---GATDSS-----------------------------G
ELM--FLMKWKN-SDEA--------DL-VPAKEAN-VKCP-Q---V----
VISF---Y---
*
>P1;CSCG15636-PA
--LEP--LRIL---GACNWS-----------------------------G
KLT--FLMQWK-----GCDEA----GL-VPAEVLN-VRCP-Q---M----
VISF---Y---
*
>P1;CSHP1
--LEA--EKIL---GASDNN-----------------------------G
RLT--FLIQFK-----GVDQA----EM-VPSTVAN-VKIP-Q---M----
VIRF---Y---
*
>P1;CSHP1Ce
--T-L--KTII---GITKAP-----------------------------G
ELH--FLCKFSD--DSV--------HL-IPLREAN-VRFPSQ--------
VIKF---Y---
*
>P1;CSK01G5.2
--Q-L--KCIV---GLTKGP-----------------------------G
ELH--FLCKFSD--DTA--------RL-LPAKE---V----NSR-YPSQ-
VIRY---Y---
*
>P1;CSFYSwi6
--L-V--SSID---TIER-----------------------KDD-----G
TLE--IYLTWKN----GAISH-HPSTI-T------------NKKCPQK--
MLQF---Y---
*
>P1;CSFYSp
--L-V--DCVK---TVQQLDN----------------------------G
KLI--AKIKWKN----GYVST--HDNI-I-------IH---QKC-PLK--
IIEY---Y---
*
>P1;CSPolycomb-like/carrot
--ARRS-DGKE-IIVDNKFL---------------------K-------V
NNPL-MLINFYEK--HLKYNA----DMERRHRSMLKVFGC-EH--GDTLL
LHLLG--F---
*
>P1;CSLHP1At
--I-L--KPMS----FTASVSDN--------------------------V
QE---VLVTFL-----ALRS-----DGKEALVDNRFLKAH-N---PH--L
LIEF---Y---
*
>P1;CSpolycombOs
--I-I--KPVR----FAAAVNND--------------------------V
QQ---VSITFK-----ALRS-----DGQEVMVDDKELKAN-N---P--LL
LISY---Y---
*
>P1;CSHP1Le
--L-V--NPVS-----YKASFSND-------------------------M
LD---VSVTFV-----AKRA-----DGNLVLVDNKFLKMN-N---P--LL
LINF---Y---
*
