>P1;HIV-2

TPYDINQ--MLNCVG--DHQ-AAMQ-IIREI----INEEA-------------------A
EW----DV----------QHPI--PGPLPAGQ----------LRE------PRGS-D-IA
G----------TTST-----VE-----E-Q----IQ----MF---------------RPQ
NPV--------PVGNIYRR------WIQ-I-GLQ------KC-VR-MY-N-PTN-ILD--
-----IKQ--G-------PKEPF--QSYV--DRFYKSLR--------AEQ----------
-----------------------------T-DP-A-------VK-NWMT-QTLLV-QNAN
P--D-C-KL--VLK----GLG-----------MNPT---------------------LEE
MLT---ACQ---GV--G----GPGQKARL--MA-EAL-----------------KE--VI
G---------PAPIPFAAAQ-Q----RK--------------------------A-FK-C
WN----CGK--EGHSARQCRA-------------------------PRRQ-G----CWKC
GK-PGHIMTNC
*
>P1;HIV-1

TPQDLNM--MLNIVG--GHQ-AAMQ-MLKET----INEEA-------------------A
EW----DR----------IHPVH-AGPIPPGQ----------MRE------PRGS-D-IA
G----------TTSN-----LQ-----E-Q----IG----M----------------TNN
PPI--------PVGDIYKR------WII-L-GLN------KI-VR-MY-S-PVS-ILD--
-----IRQ--G-------PKEPF--RDYV--DRFYKTLR--------AEQ----------
-----------------------------A-TQ-E-------VK-NWMT-ETLLV-QNAN
P--D-C-KS--ILK----ALG-----------TGAT---------------------LEE
MMT---ACQ---GV--G----GPSHKARV--LA-EAM-----------------SQ--AQ
H------TNIMMQRGN-FKG-Q----R---------------------------K-IK-C
FN----CGR--EGHLARNCRA-------------------------PRKK-G----CWKC
GK-EGHQMKDC
*
>P1;EIAV

TSEEMNA--FLDVVP--GQA-GQKQ-ILLDA----IDKIA-------------------D
DW----DN----------RHPLP-NAPLVAPPQ---------GPI------P-MTARFIR
G----------LGV------PR----ER-Q----ME----A----------------FDQ
------------FRQTYRQ------WII-E-AMS------E--GIKVMIG-KPK-AQN--
-----IRQ--G-------AKEPY--PEFV--DRLLSQIK--------SEG----------
-----------------------------H-PQ-E-------IS-KFLT-DTLTI-QNAN
E--E-CRNA--MRH----LRP------------EDT---------------------LEE
KMY---ACR---DI--G----TTKQKMML--LA-KAL-----------------QT--GL
A-----GPFKGG-ALK-GGP-L----KA--------------------------A-QT-C
YN----CGK--PGHLSSQC----------------------------RA--P--KVCFKC
KQ-PGHFSKQC
*
>P1;SIVMAC

LPYDINQ--MLNCVG--DHQ-AAMQ-IIRDI----INEEA-------------------A
DW----DL----------QHP-Q-QAPQQ-GQ----------LRE------PSGS-D-IA
G----------TTST-----VE-----E-Q----IQ----MY---------------RQQ
NPI--------PVGNIYRR------WIQ-L-GLQ------KC-VR-MY-N-PTN-ILD--
-----VKQ--G-------PKEPF--QSYV--DRFYKSLR--------AEQ----------
-----------------------------T-DP-A-------VK-NWMT-QTLLI-QNAN
P--D-C-KL--VLK----GLG-----------TNPT---------------------LEE
MLT---ACQ---GV--G----GPGQKARL--MA-EAL-----------------KE--AL
A---------PAPIPFAAAQ-Q---KGPRK------------------------P-IK-C
WN----CGK--EGHSARQCRA-------------------------PRRQ-G----CWKC
GK-MDHVMAKC
*
>P1;SIVAGM

LSYDINQ--MLNVIG--DHQ-GAMQ-IIKEV----INDEA-------------------A
QW----DI----------THPPP-AGPLPAGQ----------LRD------PRGS-D-IA
G----------TTSS-----VA-----E-Q----IE----TF---------------NAN
PRV--------DVGRIYRG------WVI-L-GLQ------KC-VK-MY-N-PIS-VLD--
-----IRQ--G-------AKEPF--KDYV--DRFYQALR--------AEQ----------
-----------------------------T-PQ-D-------VK-NWMT-ETLLI-QNAN
P--D-C-KL--VLK----GLG-----------IHPT---------------------LEE
MLT---ACQ---GV--G----GPGHKAKL--MV-EAM-----------------QQ--MQ
G--------VNMVQGA-PRG-G---RGRGRG-----------------------P-PR-C
FK----CGQ--IGHIQKDC----------------------------PRA-G-PNKCLKC
GK-PGHLAKDC
*
>P1;SIVMND

ISHDLNI--MLNAVG--DHQ-GAMQ-VLKDV----INEQA-------------------A
EW----DL----------THPQQ-QPAQPGGG----------LRT------PSGS-D-IA
G----------TTST-----VE-----E-Q----LA----MN---------------MQQ
NAI--------NVGTIYKS------WII-L-GMN------RL-VK-SH-C-PIS-ITD--
-----VRQ--G-------PKEAF--KDYV--DRFYNVMR--------AEQ----------
-----------------------------A-SG-E-------VK-MWMQ-QHLLI-ENAN
P--E-C-KQ--ILR----SLG-----------KGAT---------------------LEE
MLE---ACQ---GV--G----GPQHKARL--MA-EMM-----------------RT--VV
G-----QSQNFVQQRG-PQR-GPVRQPTGR------------------------K-PI-C
FN----CNK--EGHVARFFKA-------------------------PRRK-G----CWNC
GA-MDHQKAQC
*
>P1;VMV

TSKDILE--VLAMMP--GNR-AQKE-LIQGK----LNEEA-------------------E
RW----VR----------QNPP--------------------G-P------NVLTVDQIM
G----------VGQT-----NQ-------Q----AS----AN---------------MDQ
------------ARQICLQ------WVI-T-ALR------S--VRHMSHR-PGN-PML--
-----VKQ--K-------NTESY--EDFI--ARLLEAID--------AEP----------
-----------------------------V-TD-P-------IK-TYLK-VTLSY-TNAS
T--D-CQKQ--MDR----TLGTR--------VQQAT---------------------VEE
KMQ---ACR---DV--G----SEGFKMQL--LA-QAL-----------------R-----
----------P-QGKA-GHK-GV-------------------------------N-QK-C
YN----CGK--PGHLARQC----------------------------RQ--G--IICHHC
GK-RGHMQKDC
*
>P1;SA-OMVV

TSKDILE--VLAMMP--GNR-AQKE-LIQGK----LNEEA-------------------E
RW----VR----------QNPP--------------------G-P------NVLTVDQIM
G----------VGQ------TN-----Q-Q----AS----AN---------------MDQ
------------ARQLCLQ------WVI-T-ALR------S--VRHMSHR-PGN-PML--
-----IKQ--K-------NSESY--EDFI--ARLLEAID--------TEP----------
-----------------------------V-TD-P-------IK-TYLK-VTLSF-TNAS
T--D-CQKQ--MDR----VLGTR--------VQQAS---------------------VEE
KMQ---ACR---DV--G----SEGFKMQL--LA-QAL-----------------R-----
----------PP-RKE-GKQ-G--------------------------------V-QK-C
YY----CGK--PGHLARQC----------------------------RQ--G--IICHHC
GK-RGHMQKDC
*
>P1;CAEV

TSKDILE--VLAMMP--GNR-AQKE-LIQGK----LNEEA-------------------E
RW----RR----------NNPPP-------------------PAG------GGLTVDQIM
G----------VGQ------TN-----Q-A----AA----AN---------------MDQ
------------ARQICLQ------WVI-N-ALR------A--VRHMAHR-PGN-PML--
-----VKQ--K-------TNEPY--EDFA--ARLLEAID--------AEP----------
-----------------------------V-TQ-P-------IK-DYLK-LTLSY-TNAS
A--D-CQKQ--MDR----TLGQR--------VQQAS---------------------VEE
KMQ---ACR---DV--G----SEGFKMQL--LA-QAL-----------------R-----
----------PG-KGK-GNG-Q--------------------------------P-QR-C
YN----CGK--PGHQARQC----------------------------RQ--G--IICHNC
GK-RGHMQKEC
*
>P1;FIV

TPTDMAT--LIMAAP--GCA-ADKE-ILDES----LKQLT-------------------A
EY----DR----------TNPPD-GPR---------------PLP------Y-FTAAEIM
G----------IGL------TQ-----E-Q----QA----AR---------------FAP
------------ARMQCRA------WYL-E-ALG------K--LAAIKAK-SPR-AVQ--
-----LRQ--G-------AKEDY--SSFI--DRLFAQID--------QEQ----------
-----------------------------N-TA-E-------VK-LYLK-QSLSI-ANAN
A--E-CKKA--MSH----LKP------------EST---------------------LEE
KLR---ACQ---EI--G----SPGYKMQL--LA-EAL-----------------T-----
----------KVQVVQ-SKG-S--------------------------------G-PV-C
FN----CKK--PGHLARQC----------------------------RD--V--KKCNKC
GK-PGHLAAKC
*
>P1;BIV

VQEEIKL--LLNSTP--KWR-LDVQ-LIESK----VREKE--------------------
NA----HR----------TWKQH-H-----------------PEA------P-KT-DEII
G----------KGLS-----SA-----E-Q----AT----I----------------SVE
------------CRETFRQ------WVL-Q-AAM------E--VAQAKHA-TPG-PIN--
-----IHQ--G-------PKEPY--TDFI--NRLVAALE--------GMA----------
-----------------------------A-PE-T-------TK-EYLL-QHLSI-DHAN
E--D-C-QS--ILR----PLG-----------PNTP---------------------MEK
KLE---ACR---VV--G----SQKSKMQF--LV-AAM-----------------KE--MG
I--QSPIPAVLPHTPEAYAS-QTSGPED--------------------------G-RR-C
YG----CGK--TGHLKRNC----------------------------KQQ-----KCYHC
GK-PGHQARNC
*
>P1;HERV-K10

KSFSIKM--LKDMKEGVKQY-GPNSPYMRTL----LDSIA-------------------Y
GH----RL-I--------PYDWE-ILAKSSLSP---------SQFLQFKTWWIDGVQEQV
R-------RN-RAANPPV--ID----AD-QLLG-IG---QNWS------------TISQQ
A-LMQN-----EAIEQVRA------ICL-R-AWE------K--I---QDP-GST-CPS-F
N-T--VRQ--G-------SKEPY--PDFV--ARLQDVAQ----KSIADEKA---GKV---
--------IV---------------------E----------LM--AY--------ENAN
P--E-CQSA--I-K-----PLKG--------KVP-----------------------AGS
DVI---SEY----V-KA----CDGIGG-A--MH-KAM-----LM----------------
--------AQAITG--VVLG--GQVRT--------F------------------G-GK-C
YN----CGQ--IGHLKKNCPVLNKQN-------------ITIQATTTGRE-PP-DLCPRC
KK-GKHWASQC
*
>P1;MPMV

NGFDFAV--IKELKTAASQY-GATAPYTLAI----VESVA-------------------D
NW----LT----------PTDWN-TLVRAVLSG---------GDHLLWKSEFFENCRDTA
K-------RNQQAGN-----WD-----F-DMLT-GS---GNYS------------STDAQ
M-QYDP-----GLFAQIQA------AAT-K-AWR------K-----LPVK-GDP-GAS-L
T-G--VKQ--G-------PDEPF--ADFV--HRLITTAG---RIFGSAE-A---GVD---
--------YV---------------------K----------QL--AY--------ENAN
P--A-CQAA--I-R-----PYRK--------KTD-----------------------LTG
YIR--LCSD----I--G----PSYQQGLA--MA-AAF-----SG----------------
---------QTVK---DFLN-NKNKE---------K------------------G-GC-C
FK----CGK--KGHFAKNCHEHAH------------------NNAEPKVP-G---LCPRC
KR-GKHWANEC
*
>P1;MMTV

PLP-LKT--LKELQSAVRTM-GPSAPYTLQV----VDMVA-------------------S
QW----LT----------PSDWH-QTARATLSP---------GDYVLWRTEYEEKSKEMV
Q---------KAAGKRK---KV----SL-DMLL-GT---GQFL------------SPSSQ
I-KLSK-----DVLKDVTT------NAV-L-AWR------A--I---PPP-GVK-KTV-L
A-G--LKQ--G-------NEESY--ETFI--SRLEEAVY---RMMPRGE-----GSD---
-------ILI---------------------K----------QL--AW--------ENAN
S--L-CQDL--I-R-----PIRK---------TGT----------------------IQD
YIR--ACLD----A--S----PAVVQGMA--YA-AAM-----RG----------------
---------QKYSTFVKQTY-GGGKGG--------QGAE---------------G-PV-C
FS----CGK--TGHIRKDCKD---------------------EKGSKRAP-PG--LCPRC
KK-GYHWKSEC
*
>P1;SERV

TGFDFTI--IKELKTAASHY-GATAPYTLAI----VKSVA-------------------N
NW----LT----------PTDWN-TLVRAVLSG---------GDHLIWKSEFFENCRDTT
K-------KNQQAGN-----WD-----F-DMLT-GS---GNYA------------NTRAQ
M-QYDP-----GLFSQIQA------AAT-K-AWR------K--L---PVK-GDP-GAS-L
T-A--VKQ--G-------PNEPF--SDFV--HRLMTTAG---RIFGNAE-T---GVD---
--------YV---------------------K----------QL--AY--------ENAN
P--A-CQAA--I-R-----PYRK--------KTD-----------------------LTG
YIR--LCSD----I--G----PSYQQGLA--MT-AAF-----SG----------------
---------QTVR---DFLI---NKGKD--------------------------K-GG-C
FR----CGK--RGHFAKDCHENQN------------------KNPEAKIP-G---LCPRC
KR-GRHWANEC
*
>P1;SRV-1

NGFDFTV--IKELKTAASQY-GATAPYTLAI----VESVA-------------------D
NW----LT----------PTDWN-TLVRAVLSG---------GDHLLWKSEFFENCRETA
K-------RNQQAGN-----WD-----F-DMLT-GS---GNYS------------STDAQ
M-QYDP-----GLFAQIQA------AAT-K-AWR------K--L---PVK-GDP-GAS-L
T-G--VKQ--G-------PDEPF--ADFV--HRLITTAG---RIFGSAE-A---GVD---
--------YV---------------------K----------QL--AY--------ENAN
P--A-CQAA--I-R-----PYRK--------KTD-----------------------LTG
YIR--LCSD----I--G----PSYQQGLA--MA-AAF-----SG----------------
---------QTVK---DFLN-NKNKE---------K------------------G-GC-C
FK----CGR--KGHFAKNCHEHIH------------------NNSETKAP-G---LCPRC
KR-GKHWANEC
*
>P1;JSRV

SL-PFKQ--LKELKIACSQY-GPTAPFTIAM----IESLG-------------------T
QA----LP----------PNDWK-QTARACLSG---------GDYLLWKSEFFEQCARIA
D-------VNRQQGI-----TS-----Y-EMLI-GE---GPYQ------------ATDTQ
L-NFLP-----GAYAQISN------AAR-Q-AWK------K--L---PSS-STK-TED-L
S-K--VRQ--G-------PDEPY--QDFV--ARLLDTIG----KIMSDEKA---GMV---
--------LA---------------------K----------QL--AF--------ENAN
S--A-CQAA--L-R-----PYRK--------KGD-----------------------LSD
FIR--ICAD----I--G----PSYMQGIA--MA-AAL-----QG----------------
---------KSIK---EVLF--QQQA---------RNKK--GLQKS-------GN-SG-C
FV----CGQ--PGHRAAVCPQK---------------------HQTSVNT-P--NLCPRC
KK-GKHWARDC
*
>P1;SMRV-H

-RLNLKT--IEKIKTAVANY-GPTAPFTVAL----VESLS-------------------E
RW----LT----------PSDWF-FLSRAALSG---------GDNILWKSEYEDISKQFA
E---------RTRVRPPP--KD-----G-PLKIPGA---SPYQ------------NNDKQ
A-QFPP-----GLLTQIQS------AGL-K-AWK------R--L---PQK-GAA-TTS-L
A-K--IRQ--G-------PDESY--SDFV--SRLQETAD---RLFGSGE-S---ESS---
--------FV---------------------K----------HL--AY--------ENAN
P--A-CQSA--I-R-----PFRQ---------KELST--------------------MSP
LLW--YCSA----H--A----VGLAIGAALQNL-APA-----QL----------------
--------LEP-R---PAFA--IIVT----------NPA--IFQET--------A-PK-K
IQ----PPT--QLPTQPNAPQA----------------------SLIKNL-GPTTKCPRC
KK-GFHWASEC
*
>P1;LPDV

TPLDPKM--VKQLKEA-IQE-EGTTGPLASVLLDQVHQIA--------------------
------LT----------PSDLR-QLARIVLSP---------VMAALWKSEWTER-LQAR
-V--------TTATHDRRDPLHG--------VTVAV-LKG-SDPAMA--------TPQLQ
AARMRG-----REIQASCQ---A--SVS-I-CGG------RT-VG--KRT-D-P-WTK--
-----VTQ--G-------LGEPF--LSFA--ERLLNAYE----KSQLPE-A---AKNA--
--------VF---------------------R----------DC--VK--------QQGN
M--L-TQQY--M-L-----GAPSTEN-----TAEL----------------------VKY
LLK--RENE----G--A-------AQGNA-AAI-VAA------L----------------
------------K---EARA----------------------------------G-AN-C
FK----CGA--VGHMRRDCPSL------------------------NKRD-GG-ARCWSC
GG-AGHLARDC
*
>P1;RSV

TPLEPKL----ITRLADT---VRTKGLRSPIT--MAEVEAL-----------------MS
SP----LL----------PHDVT-NLMRVILGP---------APYALWMDAWGVQ-LQTV
-I--------AAATRDPRHPANG--QGR-GERTNLDRLKGLADGMVG--------NPQGQ
AALLRP-----GELVAITA------SAL-Q-AFR------EV-ARLAEPA-G-P-WAD--
-----ITQ--G-------PSESF--VDFA--NRLI-------KAVEGSDLP---PTARAP
--------VI---------------------I----------DC---F--------RQKS
Q--PDIQQL--I-R-----AAPS--------TLTT----------------------PGE
IIKYVLDRQ--KTA--P-----LTDQGIA-AAM-SSA------I----------------
---------QPLV---MAVV-NRERDG----QTGSGGRA---------------R-GL-C
YT----CGS--PGHYQAQCPKKR-------------------KSGNSRER------CQLC
DG-MGHNAKQC
*
>P1;STcLV2PP1664

TAKDLQD--LLQYLC--------SSLVVSLH-----HQQF--------------------
HT---LIT------------------------------------E------A-ET-RGMT
G-----------YNPM----AG-----P-L--R-MQ----ANN-------------PAQQ
-----------GLRREYQN------LWL-A-AFS------AL-P-GNTRD-P-S-WAA--
-----ILQ--G-------LEEPY--CAFV--ERLNVALD-----NGLPE-----GT--P-
-----KEPIL---------------------R----------SL--AY--------SNAN
K--D-CQK---LLQA---RGH-----------TNSP---------------------LGD
MLR---ACQ----A--W----TPKDKAR---VL-VV------------------------
---------QPRKPP--PTQ------------------------------------P--C
FR----CGK--TGHWSRDC-------------------------TLPRPP-PG--PCPLC
KD-PSHWKRDC
*
>P1;HTLV-2

TAKDLQD--LLQYLC--------SSLVVSLH-----HQQL--------------------
NT---LIT------------------------------------E------A-ET-RGMT
G-----------YNPM----AG-----P-L--R-MQ----ANN-------------PAQQ
-----------GLRREYQN------LWL-A-AFS------TL-P-GNTRD-P-S-WAA--
-----ILQ--G-------LEEPY--CAFV--ERLNVALD-----NGLPE-----GT--P-
-----KEPIL---------------------R----------SL--AY--------SNAN
K--E-CQK---ILQA---RGH-----------TNSP---------------------LGE
MLR---TCQ----A--W----TPKDKTK---VL-VV------------------------
---------QPRKPP--PTQ------------------------------------P--C
FR----CGK--IGHWSRDC-------------------------TQPRPP-PG--PCPLC
QE-PSHWKRDC
*
>P1;HTLV-1

TAKDLQD--LLQYLC--------SSLVASLH-----HQQL--------------------
DS---LIS------------------------------------E------A-ET-RGIT
G-----------YNPL----AG-----P-L--R-VQ----ANN-------------PQQQ
-----------GLRREYQQ------LWL-A-AFA------AL-P-GSAKD-P-S-WAS--
-----ILQ--G-------LEEPY--HAFV--ERLNIALD-----NGLPE-----GT--P-
-----KDPIL---------------------R----------SL--AY--------SNAN
K--E-CQK---LLQA---RGH-----------TNSP---------------------LGD
MLR---ACQ----A--W----TPKDKTK---VL-VV------------------------
---------QPKKPP--PNQ------------------------------------P--C
FR----CGK--AGHWSRDC-------------------------TQPRPP-PG--PCPLC
QD-PTHWKRDC
*
>P1;BLV

TPADLEQ--LCQYIA--------SPVDQTAH-----MTSL--------------------
TA---AIA------------------------------------A------A-EAANTLQ
G-----------FNPQ----NG-----T-L--T-QQ----SAQ-------------PNAG
-----------DLRSQYQN------LWL-Q-AWK------NL-PTRPSVQ-P---WST--
-----IVQ--G-------PAESY--VEFV--NRLQISLA-----DNLPD-----GV--P-
-----KEPII---------------------D----------SL--SY--------ANAN
K--E-CQQ---ILQG---RGL-----------VAAP---------------------VGQ
KLQ---ACA----H--W----APKVKQP---AI-LVH-----TP---------------G
PKMPGPRQPAP-KRP--PPG------------------------------------P--C
YR----CLK--EGHWARDCP-----------------------TKTTGPP-PG--PCPIC
-------KRSF
*
>P1;HFV

TGEPPRN--PREI--PI--WLGRNAPAID---------GV--------------------
---------------------------------------------------FPVTTPDLR
C-------RIINAIL-----GG-------NI---GS---LTP----------------GD
--C----------L-TW------DSAVAT--LFI------RT-H---GTF-PMH-QLGNV
IKG--IVDQEG-------VATAYTLGMML----SGQNYQ---LVSGIIRGY--LPGQ---
-------AVVTALQQ----------------RLDQ--EIDDQTRAETFI-----QHLNAV
YE-I---------------LG---------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------
*
>P1;SFV-1

TGNAPSN--PREI--PM--WIGRNASAIE---------GV--------------------
---------------------------------------------------FPIPTSDIR
S-------RVINALL-----GR-------QL---GN-------------------L-DPQ
H-C----------I-TW------ASAIAT--LYV------RT-H---GSY-PLH-QLAEV
LRR--VSNSEG-------AAAAWQLGMML----TNQDYN---LVWGMVRPL--LPGQ---
-------AVVTAMQH----------------RLDQ--EVSDAARIVSFV-----NHLNAV
YE-L---------------LG---------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------
*
>P1;MuERV-L

SPHEEIN--FAESDKPA--M-TFTTDVSQ---------G---------------------
---------------------------------------------------PPIVSSRPV
T--------RLKAKQ-----AP-------RGEV-ES--VVHEEIRYTTKELNEFANSFKQ
K-P--------GEY-VW------E-WILR--VWD------KG-----GRN-IKL-E-AEF
-----IDM--G-------PLSRD--SRFN----TEARI----VKKGVKSLF--EWLA---
-------EVFIKRWP----------------TGNDL-EMPDIPWLSVDEG-ILRLREIAM
LE-W---------------IY---------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------CV-----K--HNC---------------------------PQWE-G-PEDMP--
-F-TSSIRRKL
*
>P1;KoRV

TWDDCQQ--LLQVLF-TTEE---RE-ILL---------EA---------RKNVL-----G
VN----GA----------PTQ---------------------L--------ENLINE-AF
P----------LNRPQ----WD-----H-N--T-AE---------------------GRE
------------RLLVYRR------TLV-A-GLK------G--A---ARR-PTN-LAKVR
E----VLQ--G-------PTEPP--SVFL--ERLMEAYR------RY-TP-----FDP--
------SSEGQ----------------KAAVA----------MS--FIG-------QSAP
---D-IKKK--LQR---LEGL-----------QDHS---------------------LQD
LIK--EA-E---KV--Y-----HKRET-EEEKQEREK-----------------------
-----KETEERERR-RDRRQ-EKNLT--------------------------KIL-AAVV
SE----KGF--RGRQAGNLSNRAMRA----------------PREGRPP-LDKDQ-CAYC
KER-GHWAREC
*
>P1;REV

TWDDCQQ--LLRTLF-TTEE---RE-VRT---------ES---------RREVR-----N
DQ----GV-Q--------VTD------------------------------EREIEA-QF
P----------ATRPD----WD-----P-N--T-GR---------------------GND
------------NLERYRQ------ILL-R-GLR------A--A---ARK-PTN-LSKIT
E----VRQ--G-------ADESP--TAYL--ERLYQAYR------TW-SP-----IDP--
------RAPEN----------------QAAIV----------IQ--FVS-------QSAP
---D-IRKK--IQK---IDGF-----------QGKS---------------------LSE
LVA--IA-Q---KV--F-----DQRED--PAK----------------------------
----------------ATHE-LTQK-------------------------MAKVL-LAQE
SR----AER--GSKKTPPG-K------------------------GRPP-LGKNQ-CAYC
KEE-GHWKKNC
*
>P1;HERV-E

TWADCHQ--LLMFLFKTDE----RRVQAA---------TK---------WLEEH-----A
LA----DY-Q--------NPQ-------------------------------EYVRT-QL
P----------GTDPQ----WD-----P-N--R-ED---------------------MQR
-------------LNRYRK------ALL-E-GLK------R--R---AQK-ATN-INKVS
E----VIQ--G-------KEESP--AKFH--ERLCEAYC------MY-TP-----FDP--
------DSPEN----------------QRMIN----------MA--LVS-------QSTE
---D-IRRK--LQK---KAGF-----------AGMN---------------------TSQ
LLE--IA-N---QV--F-----VNRDA-ASRKE---------------------------
--------TTRM----NVRP--GE-T--------------------------RLL-AAAI
RGV---PPK--EARQKGGPGKETQ--------------------PGCQS-LQCNQ-CAYR
KEI-GYWKNKC
*
>P1;RTVL-Ia

SVGLLWQ--FGNMTL---L------VTFL---------LW---------TKH--------
----------------------------------------------------------LL
P-----------QDSW----WD-------N--S-NA---------------------AHE
------------NMQDLRE------III-K-GIS------E--S---IPR-TQK-LSKAF
D----IQQ--E-------KDEGP--IRFL--DRLKEQMK------QY-TG-----LNL--
------EDPLG----------------QRMLK----------IH--FVT-------KGWP
---D-VSKK--LQK-AQKVYVRRDREK---QKQKSK--PMLS--------------TFQQ
VAPNPYA-T---KG--F-----------QGARNYK-R-----------------------
-----SQASQTQFR--ETKP-SARGP--------------------------KST-FPRP
PK----EHR--KARPKNP--KTER---------------------GE---GQ-DK-CYKC
GRT-APFKREC
*
>P1;MdEV

TWDDCQQ--LLQVLF-TTEE---RERILM---------EA---------RKNVL-----G
ED----GT----------PTA---------------------L--------PNLVDE-AF
P----------LNRPN----WD-----Y-N--T-AE---------------------GRG
------------RLLVYRR------TLV-A-GLR------G--A---ARR-PTN-LAKVR
E----VLQ--G-------QTEPP--SVFL--ERLMEAYR------RY-TP-----FDP--
------SSEGQ----------------KAAVA----------MA--FIG-------QSAP
---D-IKKK--LQR---LEGL-----------QDYT---------------------LQD
LVK--EA-E---KV--Y-----HKRET-EEERQER-EK----------------------
-----KEVEERENR-RDRRQ-ERNLS--------------------------KIL-AAVI
ND---RQSE--KGRTGFLGNRAVKPP------------------GGRKTPLEKDQ-CAFC
KEK-GHWAKDC
*
>P1;PERV-MSL

TWDDCQQ--LLQTLF-TTEE---RERILL---------EA---------RKNVP-----G
AD----GR----------PTR---------------------L--------QNEIDM-GF
P----------LTRPG----WD-----Y-N--T-AE---------------------GRE
------------SLKIYRQ------ALV-A-GLR------G--A---SRR-PTN-LAKVR
E----VMQ--G-------PNEPP--SVFL--ERLLEAFR------RY-TP-----FDP--
------TSEAQ----------------KASVA----------LA--FIG-------QSAL
---D-IRKK--LQR---LEGL-----------QEAE---------------------LRD
LVK--EA-E---KV--Y-----YKRET-EEEREQRKER----------------------
-----EREEREERR--NKRQ-EKNLT--------------------------KIL-AAVV
EGK--SNTE--RERDFRKI-RSGPRQSGN---------------LGNRTPLDKDQ-CAYC
KER-GHWARNC
*
>P1;FeLV

TWDDCQQ--LLQALL-TGEE---RQRVLL---------EA---------RKQVP-----G
ED----GR----------PTQ---------------------L--------PNVIDE-TF
P----------LTRPN----WD-----F-A--T-PA---------------------GRE
------------HLRLYRQ------LLL-A-GLR------G--A---ARR-PTN-LAQVK
Q----VVQ--G-------KEETP--AAFL--ERLKEAYR------MY-TP-----YDP--
------EDPGQ----------------AASVI----------LS--FIY-------QSSP
---D-IRNK--LQR---LEGL-----------QGFT---------------------LSD
LLK--EA-E---KI--Y-----NKRET-PEEREER-------------------------
-----LWQRQEER---DKKR-HKEMT--------------------------KVL-ATVV
A-----QNR--D-KDREES-KLG---------------------DQRKIPLGKDQ-CAYC
KEK-GHWVRDC
*
>P1;RCHO-K1

TWDDCEQ--ILQVLL-TSEE---KQRVLL---------EA---------RKNVP-----G
AN----GQ----------PTQ---------------------L--------PNEIDA-AC
P----------LERPE----WD-----F-T--T-EA---------------------GRT
------------HLRLYRQ------LLV-A-GLR------G--A---GRR-PTN-LAQVK
Q----VIQ--G-------AEESP--ATFL--ERLKGAYR------MY-TP-----YDP--
------EDPGQ----------------ATTLA----------LS--LIW-------QSAP
---D-IRNK--LQR---LENL-----------QGYT---------------------LQD
LLK--EA-E---RI--S-----NKRET-QTEREERW------------------------
------RKEARRR---DRKR-NREMS--------------------------RLL-ATVV
T-----GQR--QNRQRDG--RRG-------------------------PHLDRDQ-CAYC
KEK-GHWAKEC
*
>P1;BAEVM

TWDDCQQ--LLQVLL-TTEE---RQRVLL---------EA---------RKNVP-----G
PG----GL----------PTQ---------------------L--------PNEIDE-GF
P----------LTRPD----WD-----Y-E--T-AP---------------------GRE
------------SLRIYRQ------ALL-A-GLK------G--A---GKR-PTN-LAKVR
T----ITQ--G-------KDESP--AAFM--ERLLEGFR------MY-TP-----FDP--
------EAPEH----------------KATVA----------MS--FID-------QAAL
---D-IKGK--LQR---LDGI-----------QTHG---------------------LQE
LVR--EA-E---KV--Y-----NKRET-PEEREARLIK----------------------
-----EQEEREDRR--DRKR-DKHLT--------------------------KIL-AAVV
T----EKRA--GKSGET---RRR-------------------------PKVDKDQ-CAYC
KER-GHWIKDC
*
>P1;MuLV

TWDDCQQ--LLGTLL-TGEE---KQRVLL---------EA---------RKAVR-----G
ND----GR----------PTQ---------------------L--------PNEVNA-AF
P----------LERPD----WD-----Y-T--T-TE---------------------GRN
------------HLVLYRQ------LLL-A-GLQ------N--A---GRS-PTN-LAKVK
G----ITQ--G-------PNESP--SAFL--ERLKEAYR------RY-TP-----YDP--
------EDPGQ----------------ETNVS----------MS--FIW-------QSAP
---D-IGRK--LER---LEDL-----------KSKT---------------------LGD
LVR--EA-E---KI--F-----NKRET-PEEREERIRR-ETEEKE---------------
---ERRRAEDEQREK-ERDR-HREMS--------------------------KLL-ATVV
S-----GQR--QDRQ-GG-ERRR-------------------------PQLDKDQ-CAYC
KEK-GHWAKDC
*
>P1;GALV

TWDDCQQ--LLQILF-TTEE---RERILL---------EA---------RKNVL-----G
DN----GA----------PTQ---------------------L--------ENLINE-AF
P----------LNRPH----WD-----Y-N--T-AA---------------------GRE
------------RLLVYRR------TLV-A-GLK------G--A---ARR-PTN-LAKVR
E----VLQ--G-------PAEPP--SVFL--ERLMEAYR------RY-TP-----FDP--
------SSEGQ----------------QAAVA----------MA--FIG-------QSAP
---D-IKKK--LQR---LEGL-----------QDYS---------------------LQD
LVK--EA-E---KV--Y-----HKRET-EEERQER-------------------------
---EKKEAEEKERRR-DRPK-KKNLT--------------------------KIL-AAVV
SR----EGS--TGRQTGNLSNQAKKT-----------------PRDGRPPLDKDQ-CAYC
KEK-GHWAREC
*
>P1;WdSV

DEADVEQ--LARVIF-PTPV---RQIAGV---------IN---------GHAAA------
-N---TAA----------KIQ-N-Y-----------------V-T------A--CRQ-HY
P-----------AVCD----WGTIQ-AF----T-YK---------------------PPQ
------------TAHEYVK------HAE-I-IFK------N--N--SG-L-EWQ-HATVP
FINM-VVQ--G---------L-P--PKVT--RSLMSGNP------DWSTK-----TIPQ-
-----IIPLMQ-------------------------------H---YLL-------QSRQ
---D-AKIK---QT---PLVL-----------QLAM--PAQT---------------M-N
GNK--GY-V---GS--Y-----PTNEP-YYSFQQQQ------------------------
------------------------------------------------------------
-------------RP-AP--RAPP------------------------GNVPSNT-CFFC
KQP-GHWKADC
*
>P1;Calypso5-1

KFKVPDFDKS-KGTTY--PKNHL--KVY------------C--------RK-MGAY---S
KD---EKL----------L-H---------------------F-F------ES-----LS
G----------AA-FT----W------Y-T--N-LEP--------------------SRV
-----------HSWKDLMS---A--FI--R-QYQ------Y--N---SDM-ASN-RMHLS
MC---KKEH-----------ESF--KEYV--QRWKHLA--------AQVA-----PP-MT
----DREMITI-IV--DTLPM--LYYE-KM-V----------GYTPSSF-------ADLV
FIGERIE---VGIRRGKFDYA--DFMNGKPGANGENEKEGGTHA--ATIIPTWPNFPPDQ
QYQY-SANISPSH---Y----PPPYQPRTPNHPQRP--PLNQPQS-QPAAHLIPNATFNT
---NQNTNRGRNFP--EKKP-I-EFTP----------------------I-PVSY-ANLL
SY----LLD--NEMVAITPAKVP------------------QPPFFGYYDA--T--CGYH
GGDPGHSIEHC
*
>P1;Bagy-2

NPFTG------DGSSH--PDLHL--IYVD---------EVCGLF-----KL-AGF----P
ED---EVK----------K-E---------------------V-F------PLS----LK
D----------KA-LT----W------Y-R--L-CDD--------------------TGS
-----------WDYNRLKL---E--FHQ-K-FYP------M--N---LV--HRD-RNYIY
K----FWPRDR---------KSI--AQAW--GRLKSML--------YSCP-----NHELS
-----REIITQNFY-DRLSHEDRTMLDTSC-T----------GS--FVK-------KDID
H---KWN---LLER-----IKR----------NSEDWE---------LEEGKESGMNFQF
DCV-KSFVETNTSRD-F--SAKYGLDSEIIPSLCESAAHVDLPKEKWFKYHPPVEVNIVK
PSLVEEKVIAYNDP-IVPCV-YTEK--------------------------PPYP-ARKK
DYSK-APTV--VIRR--GYIRPLSPL--------------EEIRVEPSV-AIIKD-LLAE
DID-GHVIKFC
*
>P1;Diaspora

PKFHGLA--G-E---D--PHKHL--KEFH---------IVCS-------TM-KPPDV--Q
ED---HIF----------L-K---------------------A-F------PHS----LE
G----------VA-KD----W-----LY-Y--L-APR---------------------SI
-----------TSWDDLKR---V--FLE-K-NFP------A--S---RTT-A-I-KKDIS
G----IRQLSG---------ESL--YEYW--ERFKKLC--------ASCP-----HHQIS
----E-QLLLQ-YFYEGLSNMERSMIDAA-SG----------GA--LGD-------MTPA
---EARN---LIEK-----MA-----------------------------------SNSQ
QF---SARN--DAIV-I----RGVHEV---------------------------------
---ATNSSSSSET---KKLE-------------------------------GKLD-A-LV
NLVTQLALN---QKSV--------------------------------PVA--RL-CGLC
SSA-DHHTDLC
*
>P1;Athila4-1

NKFHGLP--M-E---D--PLDHL--DEFD---------RLCNLT-----KI-NGV----S
ED---GFK----------L-R---------------------L-F------PFS----LG
D----------KA-HI----W-----EK-N--L-PHD---------------------SI
-----------TTWDDCKK---V--FLS-K-FFS------N--A---R-T-ARL-RNEIS
G----FSQKTG---------ESF--CEAW--ERFKGYT--------NQCP-----HHGFT
----KASLLST-LY-RGVLPRIRMLLNTA-SN----------GN--FQN-------KDVE
---EGWE---LVEN-----LA---------------------------------------
-----QS-D-------G-----NYNEDC--------------------------------
---DRTVRGTADSN--DKHR--KE-----------------------------IK-A-LN
DKLDRILLS--QQKH----VH---------------------------FLVDDEQ-YQVQ
-DG-EGNQLEE
*
>P1;Cyclops-2

SPFTGMD--H-E---D--PFAFL--TKFY---------ETA--------LA-AGVDQ--A
QE---LPL-F--------K-R---------------------L-F------PHA----LL
G----------KA-KD----W------Y-L--D-QTP--------------------AVM
-----------TDWNVLEE---K--FIE-R-FFS------H--N---R-F-MES-KTAIS
V----FSQGTN---------ASL--NEAW--ERFKSML--------RKCK-----GHGF-
----D-ELTQIHIFKNGFQPNCKTLLDAT-PG----------GS--LLS-------KNAQ
---EATD---IINR-----MA------------------------------------LND
LQS--QS-R-------G-----NSL-----------------------------------
----------------KKPR-VLELGT-----------------------NDAIL-A-QN
KLISPQVELLTQQIKE---LRE-------------------------PSKAKQITCCELC
-KG-DHDTGFC
*
>P1;Ogre

KFKAPSFDKY-NGTSC--PRTHV--QAYY---------RKI--------SA-YTD-----
DE---KMW----------M-----------------------Y-F------FQ-----LS
G----------AS-LD----W------Y-M--E-LKS--------------------DSI
-----------RCWRDLGE---A--FLR-Q--YK------H--N---MDM-APS-RTQLQ
S----LCQKSN---------ESF--KEYA--QRWRELA--------ARVQ----------
------PPMLER---ELTDMIGT--MGSC-PF----------GS--F---------SDVV
ICGERTES---LIKTGKIQDVGSSSSKKPFAGAPRRRE-------------------GET
NAVQHRRDQNR--IE-YRQAAAVTIPAPQPR-----------------QQQQQRVQQPQQ
QQ-QQRPYQPRQRMP-DRRF-DSL---------------------------PMSY-AELL
PELLR-L----GLVELCTMAPPT--------------------VLPPGYDANV-R-CDFH
SGAPGHHTEKC
*
>P1;Grande1-4

KVSNVDK--Y-EPKQD--PGGWL--AVYT---------TAA--------RA-VG-----A
SE---DVM----------T-A---------------------Y-L------PI-----VL
G----------QD-AL----W------L-R--D-LPR--------------------HNI
-----------DDWGDFSR---R--FTA-N--FQ------Y--L---SDK-PAQ-PWDLK
S----IKRR-GD--------ETL--RSYL--KRFQTMR------NGIPEV----------
--------T-E------------AAVIED--F----------YR--GS---------N--
---DSAFVRAILQK-----APT----------TSE------------------------E
LFR--EA-D----L--YI----TADEAQDLI-------------------GGAKPAP---
---AAPRRDANQQP--DKRW-EKRPRE----------------------E--VHA-ARPP
A-----SRA--RGGPR-GGER-----------------------TLDDI-LD-AQ-CPYH
KDM-RHTLRNC
*
>P1;B1147A04.5

RPTITEK--Y-DGSVN--PAEFL--QVYK---------TGI--------EA-AG-----G
DD---RVM----------A-N---------------------F-F------PMA----LK
G----------QA-RG----W------L-M--N-LPP--------------------ASV
-----------HSWEDLCQ---Q--FTM-N--FQ------G--T---YPR-PGE-EADLH
A----VQRR-DD--------ESL--RSYI--QRFCQVR------NTIPCI----------
--------P-A------------HAVIYA--F----------RG--GCA-------AQPH
ARKDR------LQR-----AP-----------DYR----------------------GAF
SARGPSG-S----K--GR---GMDLEPLRF-RCGS--------------FGRPRI-PCSD
---RAAQEEEEEVSL-FRRR-GSCPRR----------------------R--GRF-AGHP
K-----GEA--CERQKEGGRRSP---------------------SRERP-TG-KW-CIVH
NTS-LHDLADC
*
>P1;RIRE2

KPTGIEK--Y-DGTTN--PESWL--TVYG---------LAI--------RA-AG-----G
DS---KAM----------A-N---------------------Y-L------PVA----LA
D----------SA-RS----W------L-H--G-LTR--------------------GTI
-----------GSWAELRD---H--FIA-N--FQ------G--T---FER-PGT-QYDLY
N----VIQKSG---------ESL--RDYI--RRF-SEQR-----NKISDI----------
------TDDVI----------------IA--A----------FT--KG---------IRH
---EELVGK-FGRK-----PPK----------TVK------------------------L
MFE--KA-N----E--YA----KAEDAVTASKQSGPS------------WKPNKG-----
---TPA-KGGGGSN--NHKD-RK-----------------------------RKP-EELV
A----TATH--SSRQRS---RVN---------------------TFDKI-MN-SQ-CPHH
PNS-NHVAKDC
*
>P1;Tat4-1

KI-KLKS--Y-EGNTD--PQQFL--SAFS---------VATQRAHFHPSEAEAG-----K
CQ---LFS----------E-H-------------------------------------LM
G----------AA-LN-----------F-S--D-LPA--------------------NSI
-----------GSFLELSI---A--FLK-H--YS------M--Y---IER-GTT-HADFW
T----MAQ--G-------PKEPL--RTFI--DRFKAVV------SRIA-V----------
------PD--E-------------AAISALRN----------AVS-HE---------SRF
C--DDLL----LNR-----PV-----------YL------------------------ED
ALH--KA-T----R--YI---EMEEEKLAFSRKHTS-------------NKQSKEKVQD-
---DYYEPRQHYNQ--EYRQ-ETE----------------------------RKA-ASYL
VSEV--DPV--AQPANLEKARRT---------------------DEEGG-LD--QYCDFH
KRS-GHSTAAC
*
>P1;Tft2

KL-NLEP--Y-NGLED--PKGYL--AAFL---------IAAGRVDLNEADEDAG-----Y
CK---LFS----------K-N-------------------------------------LC
G----------LA-LM----W------F-T--Q-LEP--------------------GSI
-----------RNFNELSA---V--FLK-Q--YS------I--L---MDK-SIS-IPTSG
I-----YLK-GR----------M--RHFG---LL-SPN-----LKT--C-----------
------FQ-SS----------------QGSHN----------SR---L---------YRL
CK-KDYVM-IRGLR----KII-----------LHKPDT-------------------IQD
ALF--RA-N----N--WM---EVEDEKEIFAKR----------------NKQAKLAVTFP
P--KKFEPRENQGP--------------------------------------RKF-GSQP
F-----NNN--VGKQF--QGKGR---------------------SNTWVRDE-TSYCDIH
RVT-RHLTKDC
*
>P1;RetroSor1

KPITLPK--F-SGKAD--PRQFL--MSFE---------AAV---------ASAG-----G
NE---TVM----------A-S---------------------FV-------IA-----AE
G----------DA-LA----W------Y-S--M-LRP--------------------GSI
-----------YSWENLRD---K--ILA-N--FQ------G-FA---VES-LTS-T-DLF
Q--CRQNQ--GEA-----LREYF-QR-FV-QTKARAP---------GV-P----------
-----KEVAIE-------------AAIKGLRI----------GP--FAA-------HLAR
---EKPASMHELYH----EFE--------------------------------------K
YCR--SD-N----D--YRK--RLEDQNSQKRQSNDRNSQK-----KDLSRDERRPQRE--
---AGGQMMNIEQP-KNDRP-ENNRP--------------------------PVE-ARSS
ERVPNQAGR--GGRNA--GWRKN---------------------QSQRP-RK--QYCFFH
GEEKGHSTRDC
*
>P1;CsRN1

VESAIGI--R-LP--DYNPR-NP-RVWFH---------KLE--------AVFTT-----R
RI---TSQ-A--------TRFS--------------------YV-------VQH----LS
CD---------VATEVED--LL-------------------------------ED---IP
---------KENPYDALRA---A--VIS-R-TGK------SE-K---EML-RDL-FTTEL
GDRS-PSQ--LLRHM--RSLLCGRKLAVE---IMAQLWLN----KLP--------PSMSR
VIS----AFVDDHS--------------LEQ----------LAQ--MA------D---KI
H-ET-------YP----SNPVN---------SVSRSAPTAS------------TDSDPIL
ASI-SQLQ--------------AKFDTLTDRLQ--------------------------R
LE-------------------INRLS------------RAR---------------PSWC
-----------WYH--------------------------------QTFGPQARK-CQPP
CS--FKPRSNT
*
>P1;Kabuki

MAISLST--R-IP--EFWTE-QP-RAWYI---------RIE--------SILAP-----Q
KL----GD-E--------VKFD--------------------IV-------VSK----LP
KE---------VIIQLTD--FL-------------------------------AK---PP
---------DTGKFLALKT---K--LLS---TFE------ES-K--SRQI-ERL-IGEEL
GDQK-PSQ--LLRRM--RELA-RDKVPDD---TLRVLWQG----HL---------PTTLR
AIL----TVTETKD--------------LDN----------LAM--IA------D---NV
TEAT-------RV-NHISEVVN----------QQASNMERS-----------TSDTTLIL
AEI-AKLS--------------VR---MTNMEQRS------------------------R
QNYF-----------------DRNSS------------RRRTPQ----N-----P-NWLC
-----------YYH--------------------------------YKFRQNAQK-CVQP
CA--WKPSSEN
*
>P1;Cer2

NASASSN--G-NV---RRPR-INMLRLRP---------AV-------QLTPYRGT----M
AE----------------DF-SS-F-----------------IRS------FN-----DQ
CE----------ASER----------MD---D-DIRLKF-FLTC------LVDRARNVAE
-----DEMKLN-PTIKLKE---L--VEK---M-K------ST----FE-N---P-VLIK-
---HKENQLRLCKQ----KKD-ESVEAFH--LRIEE-LER-------AAS----------
----------------------------------------TTESAVWTKR----IVLDA-
-----------FLL----GLNKHI---------QE-KVR------------------LEW
PDT----------MVKA----LEVA------LRVEAL--------D--AE--LHKP-SRE
AAE--------------ALA-PKR-------------NE---------------------
-----------RFK---------------------------------GE-------CFFC
NKV-GHKAADC
*
>P1;Cer3

E-EATNS--I-RG---ISPS-IGVIGFKT---------AA-------TLPPFNGN----L
TE----------------DF-TT-F-----------------VRK------F-K----DR
LA----------ASTE----------MD---N-DQKRST-FLLF------LDNRARSTAD
------GIIGAQPAITLED---L--ITK---M-S------AV----FE-N---A-AVQE-
---HREEQLRYCTQ----QKG-ESVELFF--QRIDK-LQR-------LAS----------
----------------------------------------TGPRSEEMKK----VAFRA-
-----------FLE----GLGEHL---------NY-AIR-----------------SRRP
KD-----------MAAA----LDEA------LHEEML-------VN--AN---VAR-RAV
PTA--------------AAQ-GKKQ--------Q---QQKQ-------------------
------SQSP-KFL---------------------------------GE-------WHYC
HKK-GHKLADC
*
>P1;Cer1

-PDQSCED-Y-CLLIDDIAR-IA-FRRVS-------------------PEELSSMKYVKL
LD----------------EV-TDMH-----------------LR-------C-SI---DN
K-----------IMD-----------TD---E--INH---YDVC------REMIIRHEWN
------VSKI-NEKQCLNS---K--L-S---E-K------R-----G-------------
-----KVQ------------NAE---NFV-NQNTQNNFKPFS--PNKAA-----------
--------------------------------------------DNSR------------
---------------------------------NS------------------------W
NN-----------NSQ-----NNSA-----------------------AS---QNI-SRE
QSWK------------TISVPQKHQ-NPSDRCSDC--QQRGWHMFWCSKKSKDNA-SQKC
DE----CQQS-GWHMA-SCFKL-----------------------KNRA-------CFRC
NEM-GHIAWNC
*
>P1;297

QLKDIMP--F-KGD---PET-LH--TFIS---------RVD---------YVIS-L----
-Y----QT-N--------DVRQQRIL------L---------G--------A-IER-NLD
G-------Q---ITR---S-L------------------------------------GLP
---------NVEDWPTLKA---R--L-I-A-EF----------K--IQTPNYKL-LENFR
E---TPYR--GS-------LRAF-CEEAE--RRRQLLI------SKLH-------LEGNQ
---SDFLIYIQ----------------GIKES-------IKI---LI---------R--K
---LP------IQL--FTILA-----------HHD---------------------IT-D
LRS---------LITIA----QNEG------IYEE--------HIN--FE-------FYE
KP----------------------------------------------------------
------------------------------------------------------------
-----------
*
>P1;Tom

QLKDVPP--F-RGE---PET-LF--TFIS---------RVD--------YILSL------
-Y----HT-N--------DVRQQRIL------L---------G--------A-IER-NIE
G-------H---VTR------------T----L------------------------GLP
---------TIEDWPTLRS---R--M-I-N-EY----------K--PQAPNYKL-LENFR
E---TPYK--GN-------LRAF-CEEAE--RRRQILI------SKLH-------LEGNQ
---SNLIIYLQ----------------AVRDS-------MKT---LV---------R--K
---LP------IQL--FTILA-----------HHD---------------------IP-D
LRS---------LINIA----QNEG------IYEE--------HIN--FE-------TNK
NI----------------------------------------------------------
------------------------------------------------------------
-----------
*
>P1;17.6

QIGNVEK--F-NGD---PGS-LY--TFVS---------RID--------YILAL------
-Y----AT-G--------DERQQQII------F---------G--------H-IER-SIS
G------EV---MRC-----I------------------------------------GAY
---------DMYTWQQLRR---Q--L-V-L-NY----------K--PQTPNHVL-LEEFR
K---TPFR--GN-------VRAF-LEEAE--SRRQTLT------SKLE-------LEQDL
---EEKTFYLK----------------LIKSS-------IES---LI---------E--K
---LP------THI--YLRIN-----------NHN---------------------IP-D
LRS---------LINLL----QEKG------MYEQ------INHTS--TH-------VQK
Q-----------------------------------------------------------
------------------------------------------------------------
-----------
*
>P1;Gypsy

IIKSVPE--F-SGT---QDE-YV--AWRQ---------SAI--------YAYEL------
-F----KP-Y--------NGSSAHYQ------A---------V--------AILRN-KIR
G-------A---AG----A-L-----LV----S-------------------------HN
---------TVLNFDAILA---R--L-D-C-TY----------S--DKTS-LRL-LRQGL
E----VRQ--GD-------LPLM--QYYD---EVEKKL------TLVT--------NKI-
----VMTHEQE-----------------GADL-------LNA---EV---------R--A
---DA------LHA--FISGL-----------KKA------------LRAVVF-PAQPKD
LPS---------ALALA----REAE------ASIE-------RSMF--AN-------SYA
K-----------------------------------------------------------
------------------------------------------------------------
-----------
*
>P1;Burdock

ILKSLPD--F-DGK---SET-YV--SWRK---------AAH--------VAFKV------
-F----KD-Y--------EGSSTFYQ------AL--------G--------I-MRN-KIK
G-------P---ANT---V-L------A----S-------------------------FN
T---------PLHFKAMIS---R--L-D-F-TY----------S--DKRPIYLI-EQELS
T----LRQ--GD-------MTLT--EFYD---EVEKKL------TLLT--------NKT-
----IMTFDSA-----------------LAMS-------LNE---KY---------R--T
---DA------LRV--FVTGA-----------KKS------------LSDILF-AKGPKD
LPT---------ALALA----QEVE------SNHE-------RYQF--AL-------IYS
K-----------------------------------------------------------
------------------------------------------------------------
-----------
*
>P1;Gypsyvir

IIKSVPD--F-SGV---QDE-YV--AWRQ---------AAI--------YAYEL------
-F----KN-Y--------PKSTAHYQ------A---------V--------QFIRN-KIK
G-------P---AG----A-L-----LV----S-------------------------HN
---------TVLNFDAILA---R--L-D-C-TY----------S--DKTS-LRL-LRQCL
E----VTQ--GE-------MCLM--QYYD---DVEKKL------TLVT--------NKI-
----VMSHDQE-----------------GADL-------LNR---EV---------R--D
---DA------LHA--FISGL-----------RKP------------LRAVVF-PAQPKD
LPS---------ALALA----REAE------ASIE-------RSMF--AN-------SYA
K-----------------------------------------------------------
------------------------------------------------------------
-----------
*
>P1;Nomad

CVKELQA--F-EGR---QEA-YL--SWIN---------RAQ--------SILTE------
-Y----DL-I--------KTRPLYRA------I---------V--------LHIRQ-KIR
G-------H---ADM-----A-----LA----A-------------------------YG
V--------QDDDWDDIKR---V--L-A-L-HY----------A--DKRDLRTL-EHELG
A----MCQ--GS-------RPLD--RFYM---DVNGHL------SLIL--------NNL-
---KARNHPRE-----------------VVNA-------LIE---TY---------R--D
---KA------LDV--LFRGV-----------GRD------------CSKHLL-VRSRRI
LPE---------AYSFCMG--LQNV------MSRN------FTVQN--YQ-------PSG
------------------------------------------------------------
------------------------------------------------------------
-----------
*
>P1;Springer

AVKCLPD--F-MGT---QET-YV--SWRQ---------AAN--------AAYHM------
-F----RK-Y--------EDSSRHYQ------A---------V--------VIIRS-KVK
G-------P---AD----A-V-----LS----S-------------------------FG
---------TILNFDAIIS---R--L-D-F-TY----------S--DKRPIHVI-EQELG
T----LRQ--GS-------LTLL--QYYD---EVEKKL------TLLT--------NKA-
------TMSYE----------------ASAAT-----V-LCE---KF---------R--D
---DA------LRV--FVSGL-----------RRN------------LTDVLF-AAKPKD
MPS---------ALALA----QEVE------SNHE-------RYTF--AT-------SFA
R-----------------------------------------------------------
------------------------------------------------------------
-----------
*
>P1;HMS-Beagle

IVKSIRE--F-SGN---PAE-FG--SWKK---------SVD--------RIMET------
-Y----TP-F--------VGTPKYYG------I---------L--------HTIRN-KIV
G-------S---ADV---A-L------E----S-------------------------YS
---------IPLDWKAMSR---C--L-T-L-HY----------A--DKRDITTL-EYQMS
T----LVQ--GH-------QQSV-EDFHQ---DVYKNL------SLIL--------NKV-
---GCMQMSRE------------------SEH-----F-VTK---MY---------R--E
---KA------LDT--FIRGL-----------RGD------------LPRLLA-IKEPAD
LPS---------ALHYCLK--LENQ------TFR--------SNHA--AN--------KG
Q-----------------------------------------------------------
------------------------------------------------------------
-----------
*
>P1;Yoyo

VVRSLRE--F-GGN---PAE-YS--SWKK---------SVE--------RILKI------
-Y----EP-N--------MGSPKYFG------IL--------N--------V-IRN-KIV
G-------S---ADA---A-L------E----S-------------------------YN
---------TPLNWKAISK---C--L-T-M-HY----------A--DKRDLSTL-EYQMT
C----LLQ--GR--------RTV-HEFYA---EVYSHL------SLIL--------NKI-
---ACMDINEE----------------AMRI--------LTH---TY---------R--D
---KA------LDT--FVGGL-----------SGD------------LSRLLG-MKEPAD
LPE---------ALHLCIK--LENQ------NFRT--------IHA--NN----------
------------------------------------------------------------
------------------------------------------------------------
-----------
*
>P1;Zam

FVKELPT--F-DGT---PGQ-LD--KYIT---------SVE--------EIIML------
-I----RG-T--------DQTPYGLL------TL--------R--------A-IRN-KIV
G-------R---ADE---A-L------N----L-------------------------AN
---------TKLIWDDIKS---N--L-L-R-LY----------S--SKKSEATL-LGELQ
S----LPD---N-------LTLG--QLFF--GLSRIRS------QLIS---------IT-
------SNSGQ----------------SATIIEA-----KKT---LY---------D--E
---VC------LNA--FISRI-----------REP------------LKTVIR-LKDPKT
IET---------AYELCQ---GER--------------------AR--YQ----------
------------------------------------------------------------
------------------------------------------------------------
-----------
*
>P1;Ted

ALRLVPE--F-NGN---PNI-LT--RFIN---------ICD--------KLVEQ------
-Y----AS-A--------EPGSELGN------LCLLN-----G--------I-LN--KVT
G-------T---AAS-----T------I----N------------------------ANG
---------IPETWVGIRS---S--L-I-N-NF----------S--DQRDETAL-YNDLS
L----ASQ--GN--------KTP-QEFYE---QCQTLF------STIM-------TYVTL
---HETLPTT-------------------IEA-------KRA---LY---------K--K
---VT------VQA--FVRGL-----------KEP----------------LGSRIRCMR
PET----------IEKA----LEY------------------VQEE--LN-------VIY
L-----------------------------------------------------------
------------------------------------------------------------
-----------
*
>P1;Idefix

QIKELNY--Y-DGA---PGK-LS--GFVN---------QVE--------QLLSL------
-Y----PT-Q--------EARQAHVI------Y---------G--------A-VKR-LLV
D-------S---ALE-----V------V----T-------------------------QE
---------RANTWLDMKK---A--L-A-M-AF----------K--DHRPYVTL-IRQLE
D---ISYP--GS-------ICKF-IEKLE--TQYWIMF------DKLE-------LESDH
---VDKSNYTE-----------------MLNK------TVKSV--ID---------R--K
---LP------DRI--YMSLA-----------RKD-----------------------ID
TIY---------KLKQAS---MELG------LYDA---------IP--EN-------H-R
S-----------------------------------------------------------
------------------------------------------------------------
-----------
*
>P1;Tv1

QLRQVPS--F-DGS---TDQ-LN--AFIK---------RID--------YILHL------
-Y----PT-R--------DVRQHSIL------Y---------G--------A-IEL-QVT
G-------D---AQR------------I----S------------------------QRT
---------AANTWQELRN---A--L-I-E-EY----------K--VQTPFEEL-LRRLY
N---TNYQ--GN-------VRKF-IEELE--NKSFVIL------NKLA-------LENIP
---SNTTLYTN----------------AMNN-------TIKDV--IT---------K--K
---LP------DRL--FMMLA-----------RHD---------------------IT-S
TQK---------LKQVA----QREG------LYENS-----VTEKP--KN----------
N-----------------------------------------------------------
------------------------------------------------------------
-----------
*
>P1;Mdg1

ISSTIPE--F-DGK---KL-NLN--RFLT----------AL--------RLIDL------
-T-----K-G--------DQ-EM-LA------V---------E--------V-IKT-KIL
G------PLSHKVENEKTI-I-----GII--NLLK--------------------ASVKG
--------ESPDVIKA-KM------L-S-T-QQ----------R--GKTA-AQY-TTEIE
N----LR---GL-------LEAA---YID---DGLDS-------NNAD--------KFA-
---TKEA-IS-----------------AMTKNC------GHD---KLKT------ILEAG
-NFNT------MNS-VIEKYI-----------HCS------------------TEMTG-N
SNS---------LF-Y-----NNRG------HYR----------GN--NY-------RGN
Y-----------------------------------------------------------
------------------------------------------------------------
-----------
*
>P1;412

VACTVPE--F-DGQ---KI-HLQ--RFIK----------AI--------KLVDL------
-A-----K-G--------PF-ED-IA------V---------E--------V-IKS-KIV
G------TILNSVDNETTI-P-----AII--NKLQ--------------------KVVVG
--------ETSSNVKA-KL------A-T-V-QQ----------R--GKTA-TQF-TAEVD
S----LR---KL-------LEAS---YID---EGIPL-------EHAT--------GLS-
---TKEA-IE-----------------TMIHRA------EHE---SIKT------VLEAG
-TCTT------MDA-AISAYI-----------RTS------------------TRVTG-D
INK-V-------YFRGNR---PNRG-------Y-----------GN--AN-------RGS
N-----------------------------------------------------------
------------------------------------------------------------
-----------
*
>P1;Cer4

-INDL-----------KKAV-TKYQ-FSL---------EE--------PDSFR------R
WW----D-----------RHHLI-F-----SED---------AAE------L-SE-R-ER
T-----------RLLL----SC----LE---E--GT----F--------------RRFVD
--TQRNICD---IYEVPFV---TT-VEA---LEK------A--L--GSHR---S-LMI--
-----RRQ--TCLHL--SRTNCTS-LDPL---KWTNQISE-------AVLD---------
-----------------------------A-EL-AKM----STS-DW---------GIFL
-----------FLK----GLDAPG-------DAQA-KAYL-----------------MQF
YET---SDRK--GE-KL-----TLSNM----HD-EWV-------RF--LQT--KSQ-TKI
VSHS------SPKT---SADVN-----KI---------------SVKY---PPKK-P--A
YI----AAD---AKSDPPK---------------------------TSKNV---ITCYRC
GAA-GHMQYDC
*
>P1;Cer5

----------------------SVP-SKS---------SS--------STSPS------L
RL----S-----------RDKLT-F-----VED---------GKN------L-SE-R-ER
T-----------RLLL----GC----LE---E--ST----F--------------HRYED
--SQREISD---IYSISFD---DT-VTA---LTK------I--F--GSTK---S-LMM--
-----RRQ--QCLQI--CRANGLS-QDYL---DYTNSISD-------AVLD---------
-----------------------------S-KL-S-S----MTSDEW---------SIFL
-----------FLR----GLNSPG-------DEKA-KLYL-----------------MQY
VEA---SEKK--NE-KL-----KLSDV----HD-EWM-------KF--IQM--HQQ-SKI
VSVK------PSKS-SQQVDVN-----KV---------------DTNRSK-KKKK-P--I
PR----KPE----KSSQDS---------------------------KKKGEI--PTCFYC
NKK-GHYATNC
*
>P1;Cer6

RVQNNAR--I-MSDLIKRV--PKFQ-YSV---------TE--------PDTFK------R
WW----S-----------RYQLT-F-----TED---------GKD------L-TE-R-ER
N-----------RMLL----EC----LE---E--SA----Y--------------HRYVD
--SQRDVTD---FLGIPFT---ET-LQN---LTK------A--F--GSHR---S-MMM--
-----RRQ--QCLQI--SRANGES-LDPL---EYSNRVGD-------AVLE---------
-----------------------------A-KL-A-S----MSTDEW---------SVFI
-----------FLR----GLDAPG-------DNPA-KAYL-----------------MQF
CET---AEKK--GE-KL-----KLSDI----HD-EWI-------RF--IQM--KQQ-TKV
VSAL---PVKPTP--QQAVEVN-----KV---------------DPRTP--KKKK-F--K
QK----QKH---SKSGNEK-----------------------------KEFI--PTCFTC
KKS-GHTAPNC
*
>P1;Mag

VTDDLNY--P---HLISI---MGEE--------------------------S-------V
RF----------------------------------------IID------I-SQ-PFEA
VTINIC------PLWV----RKA----Y---D--L-----L--------------STLAS
-PSKPSQLT---YANAVAM---LA-AHL---QPK------PS-I-LAERY---K-FRQ--
-----RRQ-----------LN-ESIADYL-----TE-LKKL------SKNC--E------
-----------------------------F-G---------SSLDEN-------LRDQM-
-----------VC-----GLKSEI-------IRQ--RLFA-----------------EEK
LEY------------KR-----AVTL------A-LSL-------EA--AE---RDA--IA
VERT------PIEE------VN-----KI---------------NFNE-----------C
SR----CGD--RRHQAKDC---------------------------IYKD----YVCSSC
HET-GHLRRMC
*
>P1;SURL

-PLDL-----------------KGN-------------------------IS-------E
NW----K-----------RFKQK-FTL---YNV---------ASG------M-SE-K-DE
KSQTSMLL----HIIG-----DA---AL---E--L-----Y--------------NTFVF
-AEGESMKLEK-VLDKYEE------YC----MPK------RN-L-TYERH---R-FFT--
-----RSQ-----------LEHES-VDQY----ATE-LRSR------AQSC--E------
-----------------------------F------S----SLKDSL-------IRDRI-
-----------IC-----GILDAG-------LRE--RLLR-----------------QDD
LTL----DKTL-QVCRA-----AEQTRT---QA-QAL-------SS--AG---ENA-SIP
VDVD------SFSK-TKKKFSGSKS--K--------SKQSKPQDHTNN------K-T--C
SR----CGN---RHSKDKC---------------------------PAQG----KTCKKC
GKQ-NHFAKCC
*
>P1;Gulliver

--------------G------LETQ-----------------------------------
--------------------------------------------T------V-TS---EA
WCICAE-----ILLYP----SEV-PRLY---T--V-----FR-------------HSMYD
--T-HIWRKV--ISFSYST---HLLAAS---QKL------NNDYLTYA-----S-LV---
-----NSQ---C--------EQFR-LSEM----ATDQF-----------KC--L------
-----------------------------V------SV----CGKSP-------ADADA-
-----------RT-----GILTRI-------EADL-HITLQSV--------------SED
CQR------IV-NL-KH-----DI-------QL-SEC-------RD-SIE---INA-SHE
FTLL--------KR----IVTNDQV--K---------------HRKDR----RLR----C
RR----CGD---YHIYRVC---------------------------RFKK----NDYFKC
NEK-GHIQK-C
*
>P1;Cigr-1

-MDQ---------KILRPKE-LSVEPSSV--------DAA---------KVF-------K
FW----L-----------RTVED-F-----------------ISS------L-SES--QS
SSSAINKK----RIVI----SCL---SP---D--V-----Y---------------PYVE
--EAES------YEEIIRT---LRSVYI---KKK------NN---IYSR----Y-LLLS-
-----RQQ---S-------PE-ESIPEYI---QELKSLSR---------QC--E------
-----------------------------FTAVEAN------QYREE-------LTRDA-
-----------FID----GLSSSV-------IRQ--RLLE-----------------VDS
LDL----------M-KA----FELADS--LDRA-QKY-STSMG-RN--AA---PTP-SYA
ASAPQHQ--HEPKR----SAPQ-----H-------QYEET-VC-RQQVR---G-K----C
IF----CGG--FAHSRTNC---------------------------PARN----EDCFKC
GRR-GHFSRAC
*
>P1;Micropia

S-YDVK---LPKFN----PD-AACV-------------EA-------------------A
KWCSTTDI-ILT-PLKGSEHPL--KGSKLIT-----------A--------L-SN-C-ME
G----------TASQ-----WLT------Q----IS----------------------YQ
-------------GMTWQE------FQE-L-FLQRFETEETP-AA-TF---L-N-LLN--
-----SRP--TAAEC---YAVYA--SRLV--TQLTTKWRN-----MEIE-----------
---------------------------------------------EIA--VTTVLAHMAN
I--D--SR---LQR----VLFTSNVRTRS--KLQA------------------------E
LK----A------F-TF------DKKRH----ARD-------------------DN---L
----------GP-----DQK-N----RK--------------------------ASPVVC
HF----CSK--PGRRIAECRSKMRQD----------------RRAKPQREKSNVT-CYRC
GQ-PGHFSNQC
*
>P1;Blastopia

MLAKSKQ--EGQ-----VII-AA-E-------------KF-------------------E
KVV--SDCDGKSIPIKKWFEIFE-KNAEA-YELSEKQKY-VQA--------R-SK---MI
G----------SA-E----LFLES-----EC---VS------------------------
-------------------------GYT-E-LKE-LLIEE-------FSGSY-NSAVI--
----HKKL---Q-DRKK-KREET----L---HDYLLQMKK------IAA-----------
-------------------------------------------LGEVE-----TVALITH
IV-N--GLD--IK-----KEY----------K-GAM--LRCKT--------------LKE
L-----KQE----F-EI-----YESLNI----VDK-------------------PN---I
Q---------PKP----KQITQ-----G--------------------------VKADHC
FN----CGS--REHKRKDC----------------------------TL--PTK--CFSC
NQE-GHISSKC
*
>P1;Mdg3

SNERAE---SQRF-P---VD-AL-A-------------LA--------------------
KETI-TDYDGKTCA-RAWITVV--KNIARTFNIDD-NHLRILL--------I-TK---LK
G----------NA-Q----VWLHA---------HPA------------------------
-------------------------RLI-E-PID-NLLDQLS--L-TF-GEQSSKAEI--
-----RRK----FESRK-WKTEE---NF---CSYYDE-KM-------ALS----------
------------------------------------------NGINID-----DDELLDQ
MI-E--GIP--LQ------NF----------RTQAR--IQCFST-------------PSE
MLR---A------F--S------NIRLP----A-R-------------------RE----
----------PP-----VQPTD-----Y--------------------------KDAIRC
AN----CNS--RGHKADICKK-------------------------PKRE-PGS--CYAC
GQL-GHLVAQC
*
>P1;Ulysses

-PEEAYAN--VRE----TAYMKL-ERWN---------------------VK---------
-FDG-EDAMNS---VED-FVFRLEFLQRQ-------------YQC------P-WK-EVLR
GFHLL---LTGRARE-----WY------------W-----MH-----------VRHSRVD
---------------SWMQLRHA--L-L-D-RFR------------GYQTE-HE-VMQEL
L----QRE-QQ-------ASEGV--DDYI-------HHM-----RQLAA-R----FQK--
-----------------------------------------------PLRDR-ELVR--I
IK-RG-LKE---------SLAK---------YIYA---MDVLT--------------VDE
LRQ---ECLEV-ER-HM---GRRSRTGYL--QPS------RC--PQGTRPVVHEVE-VPP
HLTETP----PGELEEAFVR-T----RNSSELYAGTRDS---------------STTSLE
TA----CPR--SGK-Y-----------------------------SAIG----VESRTRS
ARS-VKTVRET
*
>P1;Circe

NKLRKTHMLGLHQTF--VAIEVI-FLWI----------------------D---------
-LIGFPILYRIK--FSGSANDIAIFIYR--------------VNC------L-TS-QSLN
GNLEL---LSHFANLM----FAGP---A-L---AFY----WR------------VHRSVD
-------------NMNWNVLCRR--L-K-K-RYQ-----------D-QRSD-RE-IKIAM
R---RRKE--G-------STENF--DDFL---DA--MLS--------IADS----LSE--
-----------------------------------------------PMQDI-EITVEDR
HNLKPEIKH---------ELLHIDT------PNLAILRKECHR--------------HED
FFR---STRT--KP--IQR-SNTSKR-FV--NAI-----LH---EDD-SEDQSEEE--QD
----------VED-EICVVR-T--------------------------------SEKIKC
WN----CDE--SGHGYQNCLKT------------------------RRI------ICYGC
GTP-EVYKPNC
*
>P1;Osvaldo

-GPSSSEQEYPK-----VA-KHV-REWNF--------RFDGT----SKPLE---------
-FL--EQVEW------SADTYGL-DLDL--------------IPR------A-MP-ELLK
G----------MALK-----W-------------YV----AN------------NRHWRT
----------------WGTFVRS--F-Q-E-FFF----------AEDYLEDLKD-EVK--
----RRKQ--MV------DEP-F--KIYM--VEM-QTLMR----PLRYG-----------
-----------------------------------------------PDHEMKLIYNNSI
----PDLRA--YARP-YQFQSLM------ELMKLA----DE----------------FEE
LER---DRERL-RR--LQ---RPART-RL--MAMEE-DDGH---EEE-MLRRGALE--ES
----------PRPAPRTGA--T----------GQRTHIP---------------NPSRAC
RV----CGQ--EGHRAVRCRN------------------------RALD------FCWQC
GRIGVRTVACC
*
>P1;Woot

SGVLRSLLD-RRPLP---APER--PSFEG---------LKR-----QNPVK---------
-FLR-AIEEY------GRF-FGL-DSQRL-------------LGV------A-M--DCLK
G----------NAKH-----WTGI--FQ-K---KWRG---Y-------------EDFRRD
-----------FLRTYWSAKRQ---R---DIRFQ-------------IATGRYD-ET---
-----RGT--M-------LSH-F---AYY----VD--M---------ANM-----LT---
----------------------------------------------TPLSE--EV----L
L--DELLRH--FPER-IQSLWVLEKIC---TTTDA----AE----------------F--
----------------------------------------------------LAAQ--EI
----------PGQ--NPGEK-T-------------NIAP------------------RE-
------RPRA-TDH-------------------------------------------QRR
NEP-KRPRPNI
*
>P1;Reina

APSMTFPV-F-DGNN---P-----KLWWQ---------RCE--------TYFNF-----Y
SV----AR-G--------MWIR----------M---------A--------IM-----FV
G----------TATF-----W------L---Q--SVE--------------------NRL
---------GEMSWEEFCG----CLN-A-R-FG----------R---DQH-SML-IRQFY
H----IHQ-----------TNSM--SEYV--EQF-DVL-----LHQLLA------HEG--
------QLTPA----------------MIT------------AR--FLD-----------
-------------------GL-----------KEEVRSVVV-----------IQRPNNLD
AAC-SLA-L-LQEDVLMHSGRREHRR------QDG--------------------GGFSK
PLQ-----------KGT--T-MAGSS---------------LSATTNR------V-AY--
-----PVSASRLEDSKLTA----------------------LK---AYRKAKGL--CFKC
GGK-WGHAHRC
*
>P1;Gloin

---------------------RC-RHLQL---------DC-----------PRR-----A
FF----PD-G--------GFLEL-------------------VS-------VS-----LT
G----------DALS-----W------Y--NW--AVN--------------------RQG
----------FTSWPQFKV---R-LL-L-R-FGN---------L----KS-R-G-PSQSL
LC---IKQ-----------TGFV--VEYI--HQF-EDL-----SSQ---------VSG--
--------LDD----------------IKLEE----------I---FLN-----------
-------------------GL-----------SLKMQEIVH----------MWNLQNLPE
MIG--VA-R-DME-SSL-----IHRV-VLKELQSGKG----GSKI----------QSESR
ALVP----YQPLV--WK--S-RPFIT--------------EPSGTKER------A-TP--
-----IIS--RPRKHFTDV-----------------------E-L-DEKRRKGL--CFKC
DAH-YFKGHVC
*
>P1;Ifg7

-GSLMAR--I--PQH---G---Y-YRWSN---------FSI--------SIMCK-----T
HK----RY-V--------LQVY----------I---------WNQ------ISLY--GIN
G----------FALV---------------------------------------------
---------NKLSLGQLLR---KNQH-I-M-RIQ------K--A-----T-S-F-FSQ-F
IS---LKQ-----------KDSIMEHEKA----FRLVR---KMESKIMA-------TG--
-----KHTTHI----------------YKDGS----------V---FA------------
-------------------PS-----------LPQP-IMLT-------------PQ----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------K-L-EEKRAKGL--CYSC
DSK-YTKGHKC
*
>P1;Gimli

VTRLGKL--D-FPRF--SGE-KV-KEWLF---------KVD--------QFFAV-----D
PI----PE-E--------MRVS--------------------V--------VSI---HLD
G----------LAAT-----W------H--QN--MIE--------------------DEV
---------QVPEWGVYKA---R-IR-E-R-FEM---------V-----G-EDP-IAE-L
KK---LQE----------TAASI--DDYH--AKF-EAI---------RTRV-R--MTE--
----------D-----------------YLVS----------A---YLV-----------
-------------------GL-----------RIETQMHIR----------MFQPQTVRQ
CLM--LG-----RL--Y-----ETAH-PV---QNNATSWKNNKAT----------SKGQF
SFKKDME-QQGNKPAFQ--E-KPRDT----------------------------------
-------QQNQPRRFLSTE-----------------------E-M-SARRAKGL--CYFC
DEQ-YTSEHYK
*
>P1;marY1

PSP-PAE--F-NG-ARAQG--RA-FLNSC---------ELY--------ISLQS-----H
QF----V-----------DEAAK-I-------Y---------W--------AFT---YMK
S---------EHAYL-----YV-----D-R--I-LRQ--------------TKEL--GSL
---------PFSTWGDFRA---E--F-V-R-HF-------C--P---LNE-RHR-AVTRL
ESST-YHQ--G--------RRSV--DDYI--DEFKDLV--------DMA------GYG--
--------SG-----------------LP-------------VVK-FRR-----------
-------------------GL-----------NREIQDQIAQ--MLEGRPADDDILAWYE
AAS--LC-D-EN----------RLTNAAF---NAAF-----------------------H
A-P----------TTTH--T---PYT------FNRSLPRPNPIPTRQT-PTP----AVN-
-----V-----PVPM----------------------DVDAAR---SRARKLDL--CYRC
GEP-GHRAGAC
*
>P1;MGLR3

-VKDPPT--F-SN-NPDKDEVTF-EVWHR---------RIE--------NKLLL-----D
GA----HY-P--------TDADK-RA------Y---------V--------ES----RLG
G----------DAAD-TLL-P------Y-------LN----------------DT--HPD
---------QITTYDGIMG---H--L-R-E-EY-------K--D---TKL-EDT-ARDEL
DK---LIM------------STK--DKFM--I-FKNKF----------------------
---------------------------VK-------------A---GQ------------
------------------SGL-----------PKRSWKREL---------HRRLPTNLRV
AMV--IYHQDTNVS--F----DAYVR-TA---DGISY----DLTK----------AYASR
TED-----KNKT-KTTS--I-K-KTT-------------GGSVIPRAGGP----A-RTT-
-----GGAVDEGQKGK--------------------LSVEEMR---GLIRT-GK--CFQC
REP-GHISRNC
*
>P1;Pyggy

KFPHPEP--F-DG-DRSKYL-AF-R-YKT---------KAK--------LRHEY-----E
GA----LS-I--------AQDRV---------P---------V--------GV----GVS
G----------KAAD-VLL-P------W-------AE--------------------TYQ
---------DYSSIDELWH---F--M-D-Q-QYD------D--P----HQ-KSK-ALDRL
LN---LRQ--G--------KLSV--RDYH--MEF-NRL---------EIQS----GER--
--------FGEA--------------AKKS------------M---FL------------
------------------KGL-----------HTKLQE-AL--------ATVDEDLSYEQ
LIN--KA-I---RT--S----DNLYRVSL---TARARQ-------------------G-H
T-L-----AE-----QS--T-P-KTT-------------QRE-AS----P----E-AMD-
-----W----EPTKVG---------------------QARPDK-S-KQEKHQFK--CYNC
GKS-GHMARQC
*
>P1;Real

KFPDPER--F-DG-TR--GN-YP-G-WKF---------ECE--------GKLEY-----D
CA----MF-P--------TEDAR-V-------R---------Y-V------L-----SRT
K----------DKAN-QVL-P------W------VLE--------------------HK-
----------ERTVVGLWE---H--M-D-T-HFQ------D--V----HQ-QQR-ALNKL
RH---LKQ--G--------RRPI--RDYV--SEF-NQL---------RVE----SRQQ--
--------FSPV--------------VARE------------M---FS------------
------------------EGL-----------REELQKLML--------HTPKN-GSLKE
YMD--KA-I---EL--S----DDLYR--I---QLHGR-----NQR----------STA-H
DG------AQNH-PRAV--Q-R-EAS-----------------------P----E-AMD-
-----W----EPSKVS---------------------QARESR-V-KTKRAPLT--CYSC
GKP-GHIARDC
*
>P1;Maggy

RLPDPDK--F-TG-ARSDLRRFA-TQIRG-----------K--------MTSNK-----D
RF----PN-P--------ESRLI---------Y---------I--------AG----RLS
G-----------KA------Y------N--LIL-PKMV----------------G--GTP
---------QFGDYTDLLQ---Y--L-E-E-AFG------D--P----DH-VQN-AQNKL
YA---LKQ--R--------NVDF--AEYL--SEF-QRL---------SLE-----GEM--
--------PED---------------ALPP------------LL--FQ------------
-------------------GI-----------SEELQD-ML----------------LHN
PAP-----S---R---Q---YHEFTR-HL---QSLDN-------------------RY-R
Q-H-----QQ---YKNR--Q---TRTPRAAAPPARAA--PRTQPD---IPRA--A-PKP-
-----NAE--LPLND-------------------PMDLSSQRR---HNRKENML--CYRC
GSQ-EHFVAKC
*
>P1;Dane-1

------------------------------------------------------------
LF----PD-P--------TELGC-T-------Y---------V--------NN----RLK
G-----------AL------Y------A--QIL-PYVK----------------K--GIC
---------QLKDYEDILD---I--L-D-Q-AFG------D--P----NC-VNN-ARNEL
FR---FQQ--N--------NKEF--GLFF--AEF-QHL---------ALE-----GEM--
--------PEE---------------TLST------------LL--EQ------------
-------------------LI-----------NRELKGMLM----------------YNQ
PPT--DY-H-------------EFAK-FL---QELEN----------------------R
RRH----YEINLQSASRNYP-AITRT----ATSQLLRTNYTTLPRTIENP----A-LQR-
-----TQPD-VHNNAMD-------------------LLSICQH-N-PTHRERGE--CFHC
GSP-EHMVRNC
*
>P1;Grasshopper

AEALQAT--A-LPKRKPLRD--P-P-LYD---------GVP--------ASFTA------
-W----RC-A--------MEYKL---------R---------R-D------A-----DFI
GDHR------DQYEY-L---W------A-GLET-SVQKVVRSYYEV--------G--GRD
--------GAYR-YTDFLD---Y--L-E-R-TYD------D--P----HK-RAQ-ALAEL
ETLK-MKP--G---------QSF--AQFI--AIF-ERTL--------ATA-----GGLA-
-------WADE---------------VRTN------------FLR-FRVS----------
-------------------PR-----------IREACVGRG----MGDGTYLGAVAIYRQ
VAQ--DL-EA--IE--L-----DRR--FG---P--------------------------H
R-A-----GAATAPRPPKDE-DTPMTGVAAMGS-----RPNGGARGRRRP----------
-----GQT--QPSDTNRRD-----------TRPRAQWVPSDEY---QRRRETGA--CLRC
GNS-GHQVADC
*
>P1;Cgret

KLNTPAT--F-DG-TP--GQLKG-HLVQI---------RTY--------QAFHM-----G
TF----QN-D--------TERVV---------H---------A--------AT----FLR
GR----------ALA-----W------F----E-PLQQEWLDNPVE----K-YSQ--EVR
--------NIFFSFDGYVK---A--L-Q-S-LFL------D--P----DE-KRQ-AERDL
SN---LRQ--N---------KSA--TLYA--AEF-RRL---------AAR-----LDM--
--------TDE---------------SKVF------------A---FY------------
------------------QGL-----------KDDVKDEMA-----K-VDTPPSFLDYVE
YAI--KI-DN--RL--F-----ERRKEKG---EKRQN----PNSG----------RKY-Q
WQP-----QQR---FNN--Q-R-NDN---------R---PRNNWN--STRQS--T-SYG-
-----QHS--GPMDLSAT-------------QKTSSWRNNNQK-N-DNWKKDKQ--CFNC
NQK-GHLAYEC
*
>P1;Cft-1

QGWQPEF--F-YG----DRV-KF-DTWVS---------QMD--------MYFLF-----N
SM----TE-N--------LKPI--------------------F--------ATT---FLR
GR----------AQH-----W------V----K-PFLRKYLDS-------N-GED--NAD
G--------VFKSYNHLKH---A--M-K-S-VFG------V--S----NE-IAT-AVRVI
QH---LTQ--K--------TSTA---EYA--AKF-QEY---------AQL-----TDW--
--------DDE----------------ALQ------------VM--YR------------
------------------RGL-----------KE-HVKDEL----MRDGRKIDGLGDLVQ
VTI--DL-DD--KL--Y-----ER----A---ME-------------------------R
R-Y-----DSK---VSG--K-A-GYT--P-GYDNRN---RGFNDN-YNKPKD--K-PYY-
-----GP---QPMELDVTE----------KGRKIRNSKGN-RR-P-PSSRETRT--CYGC
GKP-GHIARDC
*
>P1;Pyret

----------------------V-RIY----------------------QTFHL-----E
IF----RS-K--------TKKVV---------H---------A--------AI----FLR
GRTLSW---FEPLLQ-K---W------L---NI-PPEK------------R-RQK--VTD
---------IFSTFAGYKR---T--F-R-S-LFQ------E--P----DK-KRQ-AERNL
AN---LRQ-----------TKSA--SAYT--TEF-KRL---------AT-----RLDI--
---------TE---------------KTKI------------LQ--FY------------
------------------QGL-----------KLRIKDEVS-----K-LDRPEDFLEYVE
LAI--KL-DN--RI--Y-----ERRQEKQG-GQRIFV------------------TLI-R
QTN-----TGR---KYQ--H-P-QPT------YHRNNGGWQQPRHMAPQTY---N-TAY-
-----STHN-GPMDLS--------------------ATQHKKP-R-KDPKS-GK--CFKC
GKT-GYIAKNC
*
>P1;Skippy

KPSPPEY--F-DG----TPS-KL-PTFLT--------------------QSRAF-----I
TY----YP-N--------QFRND---------S---------AK-------VM----YMA
GRLIK------TAAQ-----W------F---QP-IMNDYMTNPPY-----K-LQP--RTA
LL------FGENGRHEMEE---A--L-K-M-AFG------T--I----DE-KGQ-AERKI
KT---LKQ-----------TGSA--STLG--VEFLQL----------ASK-----L-P--
-------WDQD---------------VLMS------------F---FF------------
------------------DAL-----------KEQVQQELW----EK--DRPRTLVEYIN
MAV--KI-D-------------DR--------QFAWR-----TRN----------SRGNK
G-------RQ---------D-N-KPR------YHAN---QGRTRQ----TDT--S-YGT-
-----EA---GPMAIG------------------------MTK----RDKSKVT--CYNC
GKK-GHYEREC
*
>P1;Sushi-ichi

NLASPRV--F-GG-DF-DLG-KG---FLH---------Q----------CELLFRHQP-S
RF-----V-S--------DEAKV---------G---------F--------IT----SLL
AD---------KALS-----W------A---IA-AVD---------------LDP--RLS
S-------DYSAFRREFKA---V--F-E-H-------------P----TY-GED-AASRL
LA---LQQ--G--------SRSV--AEYT--LEF--RIL--------AAE------SR--
--------WGET--------------ALRS------------A---YR------------
------------------RGL------------SEAIKDLI-----V-RDRPSSLNELIT
LSL--QM-DE--RL--R-----ERRQERA---QRAGG------ST----------RQLSH
RTS----------SAPD--F-SL-TS------TAAP--PPHILLQ---SPA---H-PSP-
-----RVGE-EPMQIG------------------RSRLSRQER-E-QRLRD-QL--CLYC
GNN-GHFIQAC
*
>P1;Ty3-1

-IQPSLT--F-RG-RN-DSHKLK-N-FIS---------EIM--------LNMSM-----I
SW----PN-D--------ASRI----------V---------Y--------CRRH--LLN
P-----------AAQ-----W------A--NDF-VQE----------------QG--ILE
--------ITFDTFIQGL-------Y-Q-H-FYK------P--P----D------INKIF
NA---ITQ--L---------SEA--KLGI--ERLNQRF---------RKI-----WDR--
-------MPPDF--------------MTEK-----------AAIMTYT------------
------------------RLL-----------TKETYNIVR-----MHKPETLKDA-MEE
AYQ--TT-----AL--T-----ERFFPGFELDADGDTI-----IG----------ATT-H
LQ------EEYDSDYDS--E-D-NLT------QNGYVHTVRTRRSYNK------------
-----------PMSNHRNRR----------------NNNPS-R-E-ECIKN-RL--CFYC
KKE-GHRLNEC
*
>P1;Skipper

THNESVK--N-ND-KI-EGETLK-KLIHR---------NFR--------SKT-L-----V
PF----KT-D--------YEAAN-TK------V---------VE-------AINHRNCYS
AQDVIK----NIEAI-MS--Y----HNV-INPV-YLIHGTA------------EV--QLE
--------YLRSILDNNIL---A--L-L-K--MV------V--P----DW-LQ--TDVAI
KL---NTQ--T--------DITEC-REAI--TELVLNN---------ADK-----FSRRR
PS----DSASN-----------------ND------------EK--F-------------
-------------------PL-----------KKNH--ATP-----NHNSH------NRN
SF---DA-Q---A---------DKIR-AA---I---------------------------
--------------LPE--I-R-KDS----------------------------------
------KV--DLKKI-----------------------RSSFI-VYRQSK--GY--CLNC
GKS-NHSTSTC
*
>P1;Tse3

FKDSMPI--I-LGKDNSTPPDNY-DAWEA---------MVQ--------RRLEQ-----Y
GY----DD-E--------I-ATE---------C---------ML-------M-----VMK
G---------QCAI------W------F-HSYLTTYRNIHGKSPSTQEACAACRE--QYG
----------NESFDEEN-------I-Q-N-LLD------L-QI----NF-SN--REPGI
TK---FLQ--Y---------RHL--LERMNSHELILHI---------YIH---TLPPA--
--------IRN-----------------Y-------------I---FSQ-----------
----------------KAKGL-------------------------------------DE
AM---AL-T---RR--------EGIR-NG---QN--------------------------
-------------------R-K-L------------------------------------
-----------PSEFRKDKV----------------NSKKVFK-SKFKQKA-GK--CGYC
GFT-GHSENEC
*
>P1;Cereba

LKLNIPT--F-DGRYV--PD-IY-LTWEL---------ETE--------QRFTC-----L
QF----PE----------DRRV----------V---------AA-------VC----YFT
S----------FACV-----W------W---C--EYCR----------------I--HHA
N--------IPTTWAALKT---A--M-H-T-RWV---------P---PYY-QCE-LLQNL
QR---LRQ--G--------KKSV--EEYY--QEL-QTG---------MIRC-G-IVED--
---------NE----------------AML------------AR--FMG-----------
-------------------GL-----------NRDIQ-SIL---------------KYKD
YNT-HSF-I-S-SCLQ------STSA-----GTG-----IARTNF----------SAG-H
TSSW----TPGIT-STS--T-CPSTS-------APPTSAANSTRD--TRKQA--P-AT--
-----TFANSTPSRPAY--------------------SSSSSM-AFTGQTHEVI--CHCC
KGG-GHHAREC
*
>P1;Beetle1

IKLDVPE--F-DGNLN--PD-AY-LEWVS---------RCN--------RIFEL-----K
EY----DD----------SKSF----------K---------LA-------IT----KLK
G----------YASL-----W------W---ENVALARE---------------R--KHK
P--------KIKSWKKLKK---K--M-E-A-KFL---------P---STY-TLD-LYNQL
SD---LFQ--G--------TKNV--ETYI--HEY-EKL---------MMKL-D--VQE--
--------REE----------------QTM------------AR--FVK-----------
-------------------GL-----------DRDIQKKLEL-Q-----SYSTLDELFRL
A-----L-KV-EKH-QK-----DKKKKVF--SKGTS---YAKGGS----------SSYVK
PTS-----TSPFT----------PKS--------EAGSKFLD------KGKK--V-AE--
-----S-----TSKKDD------------------------IK-------------CFKC
HGY-GHYQAQC
*
>P1;CRM

VKFKIPP--F-DGKYD--PD-AY-ITWEI---------AVD--------QKFAC-----H
EF----PE----------NARV----------R---------AA-------TS----EFT
E----------FASV-----W------W-----IEHGK----------------K--NPN
N--------MPQTWDALKR---V--M-R-A-RFV---------P---SYY-ARD-MLNKL
QQ---LRQ--G--------TKSV--EEYY--QEL-QMG---------MLRC-N--IEE--
--------GEE----------------SAM------------AR--FLG-----------
-------------------GL-----------NREIQ-DIL---------------AYKD
YAN--VT-----RL--F-H-LACKAEREV---QGRRA--SARSNV----------SAG-K
STPWQQRTTTSMT-GRT-----LAPT----------PSPSRPAPPPSSSDKP--R-AS--
-----ST--NSATKSAQ------------------KPAGSASSVASTGRTRDVL--CYRC
KGY-GHVQRDC
*
>P1;Cereba_Cter_reverse

VNVSIPS--F-NSRFR--PA-LY-IEWEF---------EIN--------DIFAS-----H
NF----AE----------HKKV----------T---------IA-------VG----SFT
G----------YALV-----W------W---S--GYCR----------------L---HP
D-------YILTTWDDLKL---A--M-R-HTFV----------P---SYY-TRD-MIKKL
QH---LKQ--G--------SDTV--TKYY--DNF-QTT---------LLH-----VES--
---------EE----------------DFM-----------DR---YW------------
------------------GGL-----------NHDIREILIH-EKC-----YPMDHLFRL
AC--KAEQEIKQRV--A------HKEK-----ECK----VLIPRV----------DMV--
VPS-----TIGRMITTTSIV-VRDIS----------PS-PCDTLP-----SR--V-AT--
-----SS--ELIIRGND---------------------KGT-Y-LPPP--H-V---YDDC
LVN-CNVTCDE
*
>P1;Galadriel

KIPDPKA--F-SGARSAKELENF--IW-----------DME--------QYF--------
TA----AR-V--------PDADK-L-------N---------I--------TTMY---LS
G----------DAKL-----W------W-RTR--NAD--------------DVSA--GRP
R---------IDTWDKLIK---E--M-R-D-QFL---------P---SNA-SWL-ARDKL
KR---LRQ-----------TGSV--REYI--KEF-TSV---------MLD-----IQN--
------MSDED-----------------KL------------HN--FIS-----------
-------------------GM-----------QGWAQNEL----RRQNVKDLPGAIAAAD
SLV--DF-----------------RTTRP------ST--DVPSTS----------KN--K
KKNE----K-----KG---E-WRKDS----------RKENANDK----------G-KA--
------QMK-DGKDRPKS------------------------K-D---GNSKG---CWTC
-GG-PHLAKSC
*
>P1;Monkey

------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------VDTWEDLKR---E--L-R-T-QFL---------P---ENT-EFV-ARRKL
RQ---LHQ-----------STSI--RDYV--KQF-SAL---------MLD-----IQD--
------MSEKD-----------------KL------------FS--FLD-----------
-------------------GL-----------KPWAQQELN---RRN-VTEVVGAIAAAE
RLT--DF------VSSE-------DPTRRK--Q--SS------SN----------LPP-K
HSRG----KE---LGGK--Q-KKKSS-------------------------------H--
------KGP-NPKGKA--------------------------------AKPGG---CFLC
-GG-PHMVREC
*
>P1;Tntom1

---------------------------------------TI--------LRY--------
-C----GG-L--------EEAKK-V-------A---------Y--------VTMY-----
G----------DAKL-----W------W--RV--KYEA--------------IKA--DED
---------ASETWTELKA---A--I-R---QSS---------P---ENV-EYN-ARRKL
R----LCQ-----------TKSV--RYYA--REFSCSY---------VLII-L-TIH---
-------DMGDK---------------AKV------------FT--FLE-----------
-------------------GL-----------KPYARMDLQ----RQRVDMLPKVIQVAE
CLE--DY------QVET-------RKDRP---Q---------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------
*
>P1;Legolas

SRLGTRH--F-MG-ST-DPI-VA-DEWRS---------RLK--------RNFKS-----T
RC----PE-D--------YQR-----------D---------I--------AVH---FLE
G----------DAHN-----W------W---L--TVE-------------------KRRG
D--------EVRSFADFED---E--F-N-K-KYF---------P---PEA-WDR-LECAY
LD---LVQ--G--------NRTV--REYD--EEF-NRL-------RRYVGR---ELEE--
----------E----------------QAQ------------LRR-FI------------
------------------RGL-----------RIEIRNHCLV-RTFNSVSELVERAAMIE
EGI--EE-E---RY--L-----NREKAPIRNNQS-------TKPA----------DKK-R
KF------DKVD---NT--K-SDAKT-GECVTCG-----KNHSGTCWKA-----I-GA-C
GR----CGS--KDHAIQSCPKM------------------EPG-QSKVLGEETRT-CFYC
GKT-GHLKREC
*
>P1;Tma

QRIGTGY--F-SG-GT-SPE-VA-DSWRS---------RVE--------RNFGS-----S
RC----PA-E--------YRI-----------D---------L--------AVH---FLE
G----------DAHL-----W------W-RSV--T--------------------ARRRQ
---------ADISWADFVA---E--F-N-A-KYF---------P---QEA-LDR-MEAHF
LE---LTQ--G-------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------SG-RFGE--CYHC
RER-GHLRPNC
*
>P1;Peabody

QRENPPV--F-KG-KH-DPD-AA-LGWLK---------EIE--------RIFRV-----M
DC----TP-A--------QKV-----------R---------Y--------GTH---MLA
V----------EADD-----W------W-L-E--THE--------------------RLT
VA------GEVITWDVFRR---E--F-M-T-KYY---------P---EDV-RGK-KEIEF
LE---LKQ--G--------NMSV--TDYA--AKF-VEL-------SKF-Y-----PHY--
-----TGAGAE---------------FSKC------------IK--FEN-----------
-------------------GL-----------RSEIKKAVGYQKIRIFTELVDSCRIFEE
-D---NN-A-HYKI--VS----DRRGKQH---QNRGK--PYDAPV----------GKG-K
QGAA----PAQRTSRGG--A-PAGYSLFPMLVRLVHKNNVMHCLK---------I-KK-C
FP----CGK--LVHAIADC----------------------KH-------KEMI--CFNC
GEE-GHIGSQC
*
>P1;Bagy-1

VKLNPPK--F-HR-SV-DPL-DA-DDWLC---------TIS--------RKIRS-----A
NV----SE-A--------DKVT----------F---------A--------AY----FLE
G----------PANL-----W------W---E--SFE------------------AMRPA
E--------PTATWAEFTA---A--F-R-L-HHI---------P---EGL-MDR-KREEF
CA---FTQ--G--------KLTL--DAYS--REF---G-------NLARYT----TEE--
-----VST--D---------------AKKQ------------AR--FRK-----------
-------------------GL-----------SPELRRDLC----------RHECTSFQA
-LV--NK-A--IS---ADT---GHTDFEA---TK-------------------------K
HSRD----F-----GSS--S-GSAFS-KCRLWVPN-SSMPPRYTP--RPS----Y-VA-P
QM----NHT-NPPAKTNGG-------------------PASIV---APRANEVI--CYMC
GEP-GHY-SEC
*
>P1;Retrosat-2

LRVRPPT--F-SS-TT-NPM-EA-NDWLH---------AIE--------KKLNL-----L
QC----ND-Q--------EKV-----------A---------F--------ATH---QLQ
G----------PASA-----W------W---D--NHM------------------ATRPP
G--------TEVTWAEFCR---S--F-R-K-AQV---------P---DGV-VAQ-KKREF
RA---LHQ--G--------NRTV--TEYL--HEF-NRL---------ARYA----PED--
-----VRTDAE-----------------KQ------------EK--FMA-----------
-------------------GL-----------DDELTNQLI----------SGDYADFER
-LV--DK-A--I-----------RQEDQR---NKMDR----KRKA----------AQF-R
APQGSHQ-RPRFT--PG-QQ-GGPTTMIVRQHRPFNSS-NFHQGS--SGS----Q-NH-H
GS----QPN-RGAAPRPPM------------APAQSGQPAQAK-K-ETGVKPGS--CFNC
GEL-GHFADKC
*
>P1;Del

KGLNPPI--F-KG-DP-DPL-EA-HRWIR---------HVT--------KILDT-----L
GV----TD-E--------QKVI--------------------L--------ASF---QLQ
G----------EAEF-----W------W---DA-KVR-------------------SRED
D-------TTQIKWDEFVE---V--F-T-E-KFF---------P---DTV--RD-DLERF
MT---LVQ--GS--------LTV--AQYE--AKF-EEL---------SRYA----PYQ--
-------VDIN---------------IRKV------------KR--FEQ-----------
-------------------GL-----------KLSITKQLS----------SHLIKDYRE
-VI--TR-A--LS---V-----EKREQREA--QIM-A----------------------K
RSKK--------------------------------NRGHNHPYTR--------------
------------------------------------------K---EPHRQSND--KSQC
PNP-LSPGKVC
*
>P1;TF2

HVPEIGK--F-DPN----KD-VE-SYISK------L--D----------QHFTEYP----
SL----FP-N--------EH-TKRQ-----------------YT-------LN----HLE
ELEQQ------FAERM----F------------------------------------SEN
-----------GSL-TW------QELLRQTGKVQ-------------GSNKGDR-LTKTF
EG---FRN--QL-------DKV---QFIR-KLMSKANVDDF--HTRLFILWM--LPYS--
-------LRKL----------------KERN-----------Y---W-------K--SEI
---------SEIYD--FLEDK---------RTASYG-KTH--------KRFQP-QN-K-N
LGK-ESLS---------------KKNNTT---N-S------------------------R
N-L----------------R-KTNVS----------------------------------
------------------------------------------------------------
-----------
*
>P1;TF1

HVETYRK--G--------MD-ME-EFIVK------L--R----------TFFGEHS----
DR----YS-T--------EQ-SKRL-----------------YA-------IE----RLE
SRDQN------YANKI----F------------------------------------CQD
-----------SSL-TW------DELLRRMVNLV-------------GSDEEER-LTKTF
LK---LKN--DK-------DKV---LFIK-KVLYEDNLSEK--RVRLYLLWM--LPPY--
-------LIKQ----------------RGDS-----------Y---W-------D-MDKN
---------ID-KI--FNFVP------------DKG-ETII------ERYTKPRNLLKTK
TGS-N-W-----------------KNNKFLKENDT------------------------K
DRL----------------K-KTNVS----------------------------------
------------------------------------------------------------
-----------
*
