>P1;Real
IE----------------PEV-G-------SRASNQTEGLSDVQKAQVIA
SK---L--QQAIELAQ-ASMA----------ESQQ---EQERQAN---KT
RREAQN----------FRVG----DKVWLK-LDQQYSTGR------SS-K
KLDWK-N--AKYTVIRVVD-----SHSV-----ELDTP
*
>P1;Grasshopper
IE----------------AVP-N-------AAPPSKAPASSPKARATRFL
EH---L--REGSELAQ-AAIA----------YNQQ---RQEAGAN---ES
RRPAER----------FRVG----DEVFLN-LRN-IRTNR------PC-R
KLDYI-Y--GKYRVVAVPT-----PLTV-----TLDVP
*
>P1;Pyggy
YN----------------------------VDPLQLEIPQEAD-------
--------------------------------------------------
--------------------------------------------------
--------------------------------------
*
>P1;Cer7
EM--RMTIPLQVTKDMMDEYIPP---------EEINLTKQETIEALQS--
SV---A----IIED---IWKIWNKTYLS--ELRE----THK-LRM-D-NK
REINDS----------PFVG----QVVLIC---------------DP--N
LPRNNWK-MGKITETKPST-----DGIL-----REAHL
*
>P1;Mabel
N-----AHLIMPAKNKNEMDDFI---------PHKLDSREKLIQYWSN--
TL---K----ALDA---FWEIWKEEYLN--TLKE----AQR-EHS-S-PR
DVVKRT----------PHEG----EIVLLN---------------EP--E
IPRGMWK-IARIREIKTGK-----DGEV-----RSVSI
*
>P1;Tas
HG--NSSPGVFRSLENDAREPTY---------RDPSDIHQKLLKYWEE--
TR---A----KLDN---FWTIWREEYLT--M-------------------
--------------------------------------------------
--------------------------------------
*
>P1;Cer10-1
G----------VMIETPRTPADS---------PTTSTTETRTRAHLEK--
FE---S----ALER---LWTIWTFGVML--ILRE----VSH-KHK-R-CC
D---LK----------PEVG----DVVIIN---------------PN--N
VSRHRWP-LALVVQVNQSK----RDGE----IRTAVVR
*
>P1;Spirobel
T-------HYTDIPEVTKDEDEW---------VPKAQSTSHLMKNWNL--
RQ---R----LIAQ---WWKRWKTEYVT--NLNV----RQK-WYN-S-G-
----NA----------PNIG----DIVLVS---------------EN--N
VPRRNWK-LGKIVQLYPGQ-----DGIV-----RTVKV
*
>P1;Hydra3-1
HK--------------LKLESSL---------SACNDIEQDVHIRNSM--
LS---N----TLNH---FRSRFKSEYLT--ELRE----YHK-SKR-S-NG
---CNG----------IRVN----DIVLIE---------------ND--N
CKRQLWK-LARVEELLYSD-----DGVV-----RVAKV
*
>P1;Ninja
VA--N---------LPDTPGLDA---------ECPRRVLRESSGGLLA--
CS---E----TVSG---GGGSWSTCLRL--CAAR----SGA-AER-S-PS
TR--VI----------WSSS----AILPWP---------------DE--S
GARASWR-RSTA-ELMES------SDAL-----RCA--
*
>P1;Tamy
R---------------SCGSAIL---------GTFNEYNLIGKADWKT--
TQ---H----LADH---FWKRWLREYVP--TLMP----RKI-EGK-E-V-
----RQ----------PQPG----DIVIIA---------------DA--S
LPRNTWP-RGEVIACHPGP-----DGRT-----RVVDV
*
>P1;Cubel
S---------------SSGSKPL---------VAFDNGHTALRNNWKA--
SQ---I----YANL---FWKKWVKEYLP--TICR----RTK-WHQ-P-V-
----KP----------IQVG----DVVVIA---------------DP--D
HPRNSWP-MGRVVSTNTSK-----DGQV-----RSAVV
*
>P1;Gloin
RP----------------PPT-L-------LKY-EEHS--TTNVD-LERL
LKD--S--DMMLGRIK-DQLT----------LTQQ---LMKNNAN---KH
RGDVE-----------FKVG----DFVYLK-LRPYRQHSV-TR--RVC-Q
KLATKYY--GLFEVLERIG-----KAAY-----RLKLQ
*
>P1;Ifg7
YQ----------------QPS-I-------TSY-LRIS--KVQA--VEHH
IEH--Q--QQVLQLLK-DNLV----------LAHN---RMKQQAD---QH
RIKRS-----------FDVG----DWVFLR-LQPYKHMSL-KKA-KKD-N
KLSPKYY--GPYKVLQKIG-----TMAY-----KLELP
*
>P1;Reina
HT----------------PSQ-L-------GLS-TIEQ--CQSAD-LQTY
LAT--R--QLMLQRAK-LHLQ----------RAQD---RMKKQAD---KG
RSERV-----------FQVG----QRVFLK-LQPICQSSM-GS--RLN-T
KLSFRYF--GSFLITKQVN-----PVAY-----KLALP
*
>P1;Gimli
QP----------------PPQ-H-------LPY-VPGE--SKVAVVAQNL
QE---R--EKMLLILK-FHLL----------RAQH---RMLQSAN---KK
RSDRS-----------FQIG----DFVFVK-LQPHRQGSV-VM--RSN-Q
KLAPKYY--GPYKILDTCG-----KVAY-----KLALP
*
>P1;Monkey
QQ----------------PST-P-------HTMAIGYT--GSSPSAYHFA
KE---W--HRNADIAR-AYLE----------KATK---RMKK-AN---LG
RRPQE-----------FKVG----DLVLVK-LS--ASLQF-FR-NRVH-K
GLVRKYE--GPFPIISRVG-----NVSY-----KLQLP
*
>P1;Tntom1
QQ----------------LLL-P-------RTVNAPNM--SKSPAAS-FS
KE---W--KRNLEIVQ-SYL-----------VAQK---RMKRHAD---QN
RRFVE-----------YQVG----NKVMVK-I-P-MWYLF-AG--VHD-P
RLLQKNI--GPLSIERHIG-----KVAY-----RVDNP
*
>P1;Galadriel
KQ----------------PMT-P-------LDVAKSKN-QGKCPAAYRVA
RD---R--LEMLSEAQ-DSLR----------KAQQ---RMKKYAD---QH
RRSVE-----------FSVG----DKVLLK-LTPQIWKQI-VS-KTRH-R
GLIPKYD--GPFEVVKRVG-----EVAY-----RLKLP
*
>P1;Del
RP----------------CRS-P-------TCW-AEIG--EHHLIRPELI
QQ---T--TNAIEVIK-RRLK----------AAQD---RQKSYTD---IR
RHPLE-----------FSVG----NHIFLE-VSPRKGTSY-FV---FK-G
KLSPRYT--GPFEILEIIW-----PVAY-----RLALP
*
>P1;Peabody
RR----------------CRT-P-------LCW-YESG--ESAVVGPEIV
QQ---T--TEKIKMIQ-EKMR----------IAQS---RQKSYHD---KR
RKSLE-----------FQEG----DHVFLR-VTPITGVGR-AL---KS-K
KLTPRFI--GPYQILERIG-----EVAY-----RIALP
*
>P1;Retrosat-2
RK----------------CRT-P-------LFW-DQTG--ERQLFGTEVL
AE---A--EEKVRIIR-ERLR----------IAQS---RQKSYAD---NR
RRELT-----------FEAG----DYVYLR-VTPLRGVHR-FQ---TK-G
KLAPRFV--GPYKILERRG-----EVAY-----QLELP
*
>P1;Bagy-1
RR----------------CRT-P-------LNW-SETG--ERQLFGPDMI
QD---A--EE-VRIIR-EKLK----------TAQS---LQKSQYD---RH
HKAVT-----------SEVD----EKAYLR-VTPLKGTHR-FG---IK-G
KLAPRYI--GPFRILAKRG-----VVAY-----QLEHP
*
>P1;Tma
RP----------------CRT-P-------LCLTQV-G--ERSIYGADYV
QE---T--TERIRVLK-LNMK----------EAQD---RQRSYAD---KR
RRELE-----------FEVG----DRVYLK-MAMLRGPNR-SI---SE-T
KLSPRYM--GPFRIVERVG-----PVAY-----RLELP
*
>P1;Legolas
RA----------------CRT-P-------LCWTPV-G--ERRLFGPTIV
DE---T--TERMKFLK-IKLK----------EAQD---RQKSYAN---KR
RKELE-----------FQVG----DLVYLK-AMTYKGAGR-FT---SR-K
KLSPRYV--GPYKVIERVG-----AVAY-----KLDLP
*
>P1;Cereba
FL----------------PRA-P-------IHLLPLPSSEKVNFDAKECA
DL---I--LNMHELTK-ENIE----------CMNS---KYKLAGA----H
KKWSS---------------------------------------------
--------------------------------------
*
>P1;CRM
LL----------------PRA-P-------IDLMPLPSSEKLNFDATRRA
EL---M--LKLHETTK-ENIE----------RMNA---RYKFASD---KG
RKEIN-----------FEPG----DLVWLH-L---RKERF-PEL--RK-S
KLLPRAD--GPFKVLEKIN-----DNAY-----RLDLP
*
>P1;Beetle1
VN----------------PLS-P-------IDLLPIPVEVRQSKDAEEKA
KE---M--KKLHQQIR-ARIE----------KVNE---AYKVQAN---KH
RKEVI-----------YKPG----DLVWLH-L---RKERF-PSR--RK-N
KLMPRSD--GPFRVLEKIN-----NNAY-----KIELP
*
>P1;G-Rhodo
RQ----------------PAM-P------VASLHKT-----PSPAAEDFI
MN---L--QNRIAMAR-DHI-----------RQRQ---GERADRNV--DS
TQPAN-----------YKVG----DKVLLS-TE-HYNLQL------PS-E
KLAPRWL--GPLEILEVRG-----PNTV-----RIEVP
*
>P1;Zebel
R---------------RDASLPQ---------VLYDSNNLLGRRRWRH--
SQ---V----LADN---FWTAFIRHHLP--SLQD----RQR-WRK-D-G-
----KE----------LTMG----QVVLIV---------------DP--Q
LPRALWP-VGTVSETLPGA-----DGKI-----RTVRV
*
>P1;Sinbad
R---------------ERYR------------------------TYRS--
-----------IQV---FQEMEASELLS--TS------------------
----------------FLET----LVGICF---------------AF--A
AXIQMDP-TR-----EEHK-----GGXL-----NDMFV
*
>P1;Saci-6
R---------------ENVTELT---------NVLS-NDRYS-KRWKQ--
AN---Y----LAQV---FWRRWSKEYVS--LLQR----RYK-WTQ-L-E-
----RN----------IREG----DLVMIC---------------SE--F
SEKNKWP-LGLVQRVLPSK-----NGLV-----RQVEL
*
>P1;Kobel
R---------------ARALSSP---------GVFEKSDMYARKRWRQ--
SQ---Y----LIDV---FWCRWRKEYLV--TLQQ----RPK-WQR-K-R-
----RN----------VQVG----DIVLVV---------------DK--S
VPRNSWL-MGVVETTFKDK-----KGDV-----RSCRV
*
>P1;Purbel
R----------------SSSKVP---------HGPFRETRNPRHRVEF--
VQ---Q----IVNS---FWKSWNRDVFP--LLVP----RRK-WNT-E-R-
----RN----------VRVG----DIAMLA---------------DA--N
AVRGKWT-IARVVQVYPGV-----DGTV-----RNVKV
*
>P1;Suzu
R----------------ASNSGD---------FNSFDFESYSYKRLQV--
IQ---C----EVNN---FWKSWSQLVGP--NLFI----RNK-WHT-L-H-
----RN----------VSEG----DIVWVC---------------DQ--N
SLRGQYK-VVK---ANPDA-----RGIV-----RDVDV
*
>P1;Gabel
Q----------------ASSSGD---------WKTFVFTSYPYKRLQE--
MQ---H----QVNK---FWRSWSQLAGP--NLFV----RSK-WHT-T-Q-
----RN----------VADG----DIVWLC---------------DQ--N
ALRGNFK-AWEGYKCQPRL-QRHSTGCESQSCDKLLYP
*
>P1;Moose
N---------------NLKVILE---------PDLKEVPMNRLGRYQL--
LH---G----YTQN---FWIHWKQDYLK--NLTV----LHR-SAK-Q-S-
----KQ----------LSVG----DIVILK---------------DE--Q
LPAVQWP-LARVVEIHPGA-----DGIS-----RVATL
*
>P1;Max
G---------------PLLSTAE---------PEIKGEAKSIINRWQH--
LK---A----QHQQ---FSARWKEEYLK--ELHK----RSK-WQF-P-T-
----RN----------LQAD----DMVVVK---------------ED--N
LPPNEWR-LGRIVSAFPGA-----DERI-----RVVEI
*
>P1;Tribel
R---------------PLTTIPS---------DNHLDTPMKRLNRFEY--
QE---K----ICQD---FWQRWHQEYLS--YLQQ----RKK-WTQ-S-T-
----RQ----------IRPD----DLVVIR---------------DQ--N
LPPMRWK-MGRVEEVYPSP----NDGVV-----RVASV
*
>P1;Nabel
D---------------SLKSLPE---------QNYTKIPDNRLSAWEI--
MS---K----LKQQ---FWERWNKEYLN--ELNI----RHN-KSA-A-E-
----PK----------LTKD----LVVLIK---------------ED--N
TPPMQWN-MGIITDVHPGA-----DKII-----RVVTV
*
>P1;Roo
R---------------PPLEIVE---------P-MEDEKIGNLDRWRL--
IQ---K----IKKD---FWVKWKSEYLH--TLQQ----RNK-WKK-E-I-
----PN----------IEEG----QIVLLK---------------DE--N
CHPARWP-LGKVEKVHKGN-----DDKV-----RVAKV
*
>P1;Bel
S---------------PYTALPE---------PCRLDMQVNRLERWNQ--
LQ---A----MVQG---FWKRWHMEYLT--SLHE----RTK-WHL-E-T-
----EN----------LKID----TLVVLK---------------EP--N
LPPSKWI-LGRITAVHAGI-----DNKV-----RVVTV
*
>P1;Mag
RS----------------LRM-R-------LDN-----------LKPERQ
-S----------RV-----------------IAQQERSEQNA------GG
VQRQ------------LEPG----TKVWYR---------------DYR-G
L--DKWV--PGT-ILKQLG-----SRDY-----CVRSS
*
>P1;Gulliver
RS----------------MRI-F-------SDI-----------VHP-RD
------------KV------------------KV---TSNNDGND---YK
RARD------------FNVG----DYAHAS---------------DYR-P
GR-PKWI--NGT-IVARRG-----KMLY-----EVRVG
*
>P1;DRM
RH----------------VRT-R-------LDF-----------VHPDVT
-V----------AV----------------RRKQYL---QKFHHD----K
RSVERS----------FSEK----DAVYLR---------------NTT-G
KG-NKWV--PGV-IVKQTG-----PVSY-----NVQGQ
*
>P1;CFG1
RK----------------LRT-K-------LDL-----------VKPDVR
-E----------RV----------------VKRQQT---QKNYHD----S
RAKERV----------FAEG----DKVFVK---------------NF--Y
SG-PKWK--SGE-IVSKNS-----PASY-----TVEGQ
*
>P1;Hydra2-1
RK----------------LRS-A-------FQG-----------LKPDLN
-N----------SV----------------KEKQER---AEKLSN----R
KAHLRK----------FDCG----DQVMAK---------------NF--G
NG-PKWI--PGR-IIKQKG-----PVNF-----E-ILT
*
>P1;SPM
FA----------------PRT-R-------FSL-----------LKPDLN
-T----------RV----------------TQKQEK---TRQYHD---TP
GMKLRQ----------FESG----EQVMVK---------------NH--R
GGKERYV--LGV-IVKRLG-----FYSY-----LVRIG
*
>P1;SURL
RR----------------LRS-N-------LPM-----------LDTLLD
NQ----------QIDTKSVRGRK---------EEQK-VKQKERFD----K
HAHDLSN---------LKPG----DHVILQ---------------DMK--
T--NTWS--KRG-IIKSVL---NRNRSY-----QVETE
*
>P1;Cer4
RK----------------IRT-K-------MSL-----------LVPSRE
IV----------EGP-LS-------------DCQNRMKFQYDSRN---AA
RAKT------------FELG----QYVYVR---------------VQK-G
NV-WSWE--HGE-VIKRLG-----EVLY-----EVQVG
*
>P1;Cer5
RK----------------IRT-T-------MSL-----------LMPTDR
VL----------KVPKLT-------------QYQQNMKHHYDLRN---GA
RAKA------------FQVN----QKVYVQ---------------VHH-G
NK-SQWK--HGV-IRRKFG-----GVLY-----EVQVG
*
>P1;Cer6
RS----------------IRT-T-------MSL-----------LMPKPD
AN----------HQADLS-------------EYQKKMKQQYDSRN---GT
RAKH------------FQVG----QQVYVK---------------VQH-G
NK-SEWD--YGV-VSRKIG-----SVLY-----EVQVG
*
>P1;HMS-Beagle
RIA---------------TVA-P-------------------------EK
YE---Q------ARLD-NIDR-------LRQKQET---DIEYHNR----T
RK-PIK-------T--YIKG----QEIFVR----------------VN-T
R---LGS--KLSSRFRKELV----KEDR-----STTIL
*
>P1;Yoyo
RSV---------------YSD-P-------------------------SL
LE---K------DRLD-NIKK-------IVNKQEK---DLTFHNK----K
RT-EVK-------A--YSSN----DIIYVK----------------IN-K
R---IGN--KLTPRYKKEIV----LEDN-----GNTVT
*
>P1;Gypsyvir
--------------------A-A---------------------------
-S---D------RRGN-VKNR-------LIKAQQD---NIKRCNA----S
RQ--NR-------V--FEVG----EKVFQK----------------NN-K
R---LGN--KLTPLCSEQKV----EADL-----GTSVL
*
>P1;Burdock
--------------------T-P---------------------------
-P---E------LANE-IVEM-------VNEAQEK---QLRRENV----T
RR--DR-------T--FEVG----ETVMVK----------------QN-N
R---LGN--KLTPRYREELI----EADL-----GTTVL
*
>P1;Nomad
RSSR-----------VKLSGF-D--------------------------F
RR---Q-------TLE-DI-K-------LIEYKQI---RGNMRNK----N
RD-EPK-------S--YGPG----DEVFV-----------------AN-K
Q-IKTKE--KARFRCEKVQE-----DNK-----VTVKT
*
>P1;Gypsy
--------------------G-A---------------------------
-H---E------RCLE-IKAR-------LVKAQQD---SIGRNNP----S
RQ--NR-------V--FEVG----ERVFVK----------------NN-K
R---LGN--KLTPLCTEQKV----QADL-----GTSVL
*
>P1;297
------------------AGH-P---------------------------
IL---D------TQKI-KEKK-------IEKINED---RREFNID----T
NY--RKG------P--LQKG--KLENPF-K---------------PTKNV
EQTDPDH-YKIT-NRNRV------THYY-----KTQFK
*
>P1;17.6
------------------AGQ-P---------------------------
IL---D------TQQN-KENK-------INKINND---RVEYEVD----T
RY--RKG------P--LQKG--KLENPF-K---------------PTKNV
EQTDSDH-YKIT-NRNRI------THYY-----KTQFK
*
>P1;Tv1
------------------AGT-P---------------------------
EY---D------TQAN-KEKL-------INNLNKK---RTNYEID----T
RY--KHS------P--LVKS--KTTTPFKK---------------TGE-L
RQIDDKH-FEET-NRGRKI-----TH-Y-----KTKFK
*
>P1;Ted
HFD---------------PRD-P--------------------------L
DI---D----LTEHIL-QQYA-------QNHRQQM---KQVYEII----N
ET-SLAV------E--YIPQ----QQVFIK--------------NPLA-S
RQKVAPRYTQDT-VLADLP-----IH-I-----YTSKK
*
>P1;Zam
RTHL-----------FEKTII-P---------------------------
-----N------NEHD-YLNK-------LNTFQDK---L--YS-E----I
KEKLSTN------T--QQRI--EKLNTSRV--------------EPTT-V
QPNSTIF-RKEN-RRNKL------TPRF-----SLHRT
*
>P1;Idefix
------------------AGS-P---------------------------
DF---N------VQQN-KIDR-------IEYLNKN---RHDFEVD----I
KY--RQA------P--LVKS--KITNPFKK---------------TGR-I
GQVDDKH-FEET-NRGRKI-----VH-Y-----KSKFK
*
>P1;Tom
------------------AGQ-P---------------------------
TL---D------AQKI-KEQK-------INKLNDD---RQEYDID----T
KF--RKG------P--LQKG--KLENPF-K--------------ENKN-V
EQTDPDH-YKIT-NRNRT------TNYY-----KTQFK
*
>P1;Springer
--------------------D-P---------------------------
-D---D------PHTD-VQEK-------IKNAQIL---TRKRENA----S
RQ--NR-------V--FQVG----DKVLVK----------------SN-R
R---LGN--KLTPLCEEKTI----EADL-----GTTVL
*
>P1;Athila4-1
KL----------------CHL-P-------VELEYKAMWAVKLLNFDIKT
AE---E--KRLIQLSD-LDEIRLEAYESSKIYKE----RTKLFHD----K
KIITKD----------FQVG----DQVLLF-----NSRLK-----LFP-G
KLKSRWS--GPFCITEVRP-----YGAV-----TLAGK
*
>P1;Diaspora
KA----------------CHL-P-------VEIEHKAYWAVKTCNFSMDQ
AG---E--ERKLQLSE-LDEIRLEAYENAKFYKE----KTKKFHD----S
MIVKKD----------FMVG----QKVLLY-----NSRLG-----LMS-G
KLRSKWI--GPFVVTNVFP-----YGTV-----EIKSD
*
>P1;Cyclops-2
KT----------------CHL-P-------VELEHKALWALKINNFEKDL
AG---E--KRKVQLLE-LEEIHNAAYHSSCLYKE----KVKKYHD----K
KLRKKE----------FVPG----QLVLLF-----NSRLK-----LFP-G
KLKSKWS--GPFRVKEVNE-----YGAI-----VIEDM
*
>P1;Bagy-2
KA----------------CHL-P-------LELEHKAYWAIKELNFDFKL
AG---E--KRLFDISS-LDEWRAQAYENAKLFKE----KVKRWHD----K
RIQKRE----------FNVG----DYVLLY-----NSCLR-----FFA-G
KLLSKWE--GLYVVEEVYR-----SGAI-----KINNT
*
>P1;Calypso
KS----------------CHL-P-------VEMKYKTYWALKLLNFDEAE
SR---E--QRRLQLLE-LEEIKLTAYESSQLYKE----KIKKYHD----K
KLLKRD----------FQQG----QQVLLF-----TSRLK-----LFP-G
KLKSKWS--RPFTIKKVRT-----YGAV-----ELCDP
*
>P1;Sushi-ichi
YQ----------------PPL-F-------PQQELEIAVPSTRAHLRRCR
RI---W--KT-ARKAI-LRAT-----------EQS---RR--SAN---RR
RRPAPA----------YRPG----QKVWLL-ARD-LPLQ--TS-QTSS-R
KLNPRDI--GPYTICSIIN-----PSAV-----HLDLP
*
>P1;Amn-ichi
FH----------------PRF-F------PPVIET-SEVPAAEDWLQELT
AV---Q--QL-LLQQL-DQAK-----------EDY---KR--HAD---KH
RQPGPE----------IKVG----DRVFLS-TRF-LPSHR------PC-R
KLDARFI--GPYPVVAQLN-----PVTF-----KLQLP
*
>P1;Amn-san
QH----------------PLA-F-------PQDLLLSEVPAADDLAAHMS
VI---W--AA-TKSNL-EKSS-----------LVH---KT--FAD---RR
RKPSPP----------YKVG----EKVWLS-SRN-IRLKV------PS-P
KLGPKFL--GPFSISEVIN-----PVAV-----RLQLP
*
>P1;Amn-ni
FP----------------PPL-F-------PEQEVEVAVPSALQFVRRCR
QT---W--RK-ARLKL-LKVS-----------QQY---KH--QAN---RR
RRPAPT----------LRPG----QRVWLS-TRN-IPLRV------DS-R
KLSQKFI--GPFKIARKVN-----PVTY-----KLYLP
*
>P1;Dane-1
FH----------------PRM-G-------FEPVP-VPDCPASQDAENFA
QK---M--QAISDYVR-SQMT----------SAQA---RYEEQSN---KT
RQPARQ----------YKAV----SVCGWM-PAT-SVP-R------PS-K
KLIGS-L--GPFTIKGIIN-----AHTY-----ELDLP
*
>P1;Maggy
FH----------------PRM-G-------FEPVPLNQPLPAQRDAEKLA
AR---M--EAILEQAR-AEMT----------AAQA---RYEEQAN---RH
RTPARR----------LTVG----QYVWLD-ARN-IQTAR------PQ-K
KLDWKNL--GPFRISEVIS-----PYAY-----RLDLP
*
>P1;marY1
RH----------------PRM-G-------FEPRQTPSHIETVNEFTERM
RD---S--LEEARAAL-AKAK-----------DD----MARFY-N---QR
HSPTPQ----------YKVG----DRVYLD-SSD-ISTTR------PS-K
KLAHRFL--GPFPIVKCVG-----THAY-----RLRLP
*
>P1;Cgret
FE----------------PTA-Y-------GEP---RAGPEAVK-AVASV
KQ---I--KDIQANAR-RELE----------FVRK---RMTHFSN---QR
RIEGPT----------LREG----DSAYLI-RRN-IKTKR------PS-D
KLDYKKL--GPFKILKQIS-----PVNF-----KLDLP
*
>P1;Cft-1
RT----------------LTY-P----EH-LDPTHR--PREQSVTTETLK
EV---H--KEA-RKAI-EDAQ------------QR---LSQRRQD---ER
K-MAPL----------LKEG----DKVYLL-TKN-LKTRR------QT-K
KLDHVKV--GPFFIDKVVG-----PVNY-----RLRLP
*
>P1;Pyret
FN----------------PTA-Y-------GEP---RTTITAPR-ADKQA
SE---L--RQLYKKLQ-QELK----------FVRK---RIMKYAN---HR
-IKGPS----------FKKG----NSVYLI-RRN-IKTQR------PN-N
KFDFKKL--GPFKISKKIS-----DTNY-----RLSLP
*
>P1;Skippy
FT----------------PNA-Y-------HNARPEKSINPA---AIIKS
ED---M--QDLHEYLK-TELE----------FVRK---RMKNYYD---PK
RLKGPT----------FSEG----DMVYLA-TKN-IKTDR------PS-H
KLDYKFI--GPYKVLQKIS-----ENNY-----KLDLP
*
>P1;MGLR3
YP----------------AHM-H-------FDWTQRTELKGLPTRERLTR
TE---A--QAITKKLE-SYVEAARTHLQ---MAQ----QRMCDQA---NK
HRREPD----------FGVG----SAVYII-KKHWV-TDR------PS-D
KLDYPLT--RCSYVIKEKR-----GHSY-----RLELP
*
>P1;Tse3
YH----------------PRL-P-------GFYHLITSGGQSEKEARGTE
LG-DLD--DRIIQQNN-IFLIIQERIAA----AQQ---KQALQYN---KK
HR-HAE----------FEVG----DKVLVHQQAYWPGYHK-------G-L
KLHHIWY--GPFPV-TAA------DGAN--L--TLDLP
*
>P1;Ty3-1
YL----------------PNT-P------AIKSDD-EVNARSFTAVELAK
HL---K--ALTIQTKE-QLEH-----------AQI---EM-ETNN---NQ
RRKPLL----------LNIG----DHVLVH-RDAYFKKGA-------Y-M
KVQQIYV--GPFRVVKKIN-----DNAY-----ELDLN
*
>P1;Skipper
FN----------------PPT-P------VNHFNSLTKTRIPMSNIKKIV
RD---N--ILD---------------------AQI---NAPKYYN---RG
RGDVI-----------FVVG----EKVMVKRKFFQTNLSK----DLIS-H
KLESKNC--GPFII-TAVH-----GNNV-----TLDLV
*
>P1;TF2
YS----------------P-A-L--------SPLEL--PSFSDKTDENSQ
ET---I---QVFQTVK-EHLN----------TNNI---KMKKYFD---MK
IQEIEE----------FQPG----DLVMVK-RTKTGFLHK-------S-N
KLAPSFA--GPFYVLQKSG-----PNNY-----ELDLP
*
>P1;TF1
YS----------------P-A-L--------SPLEL--PSFSDKTDENSQ
ET---I---QVFQTVK-EHLN----------TNNI---KMKKYFD---MK
IQETEE----------FQPG----DLVMVK-RTKTGFLHK-------S-N
KLAPSFA--GPFYVLQKSG-----PNNY-----ELDLP
*
>P1;Tor4a
--------------------A-E--------CPHNI---FDNNYRNYNLD
-R---K---TKFEDI--QKL-----------IEEE---KNKRMAK---FS
NPKFNA----------YNLG----DLVLIK----NFESKK----------
---PAFL--GPFKITSKST-----AGTW----YTVESD
*
>P1;Tor2
RD----------------PSFNGIAI--DNVAAANPASY--AQNTAE-LL
-----D-RAHKF-VKL--SQE----------AAD------RDA-----LE
R---------------GKSKIQ--PEEITA-GHSIMLKREVSAEAKE---
GRN-KWV--GPYKVLASD------GLIL-----QIDVD
*
>P1;Tor1
WT----------------LAE-P--------LFSKKVDGSE-IQSDVRLW
VQ---ESGARMCAALA--LLT----------AKQ----AVPLTPI---PV
ESDDNA----------LEPGT---H-VLL------KTMTP----PGVS-A
KLYSPWK--GGYVVRKRCD-----HFTY------LITP
*
>P1;Cer1
RD----------------VMG-PLEMSGEDAVG-INYA--DMDEYKHLLT
QE----L-LKVQKIAK-EHAM----------REQES-YK-SLFDQKYASK
KHRF------------PQPG----SRVLLE-I-PSEKLG------AQC-P
KLVNKWS--GPYRVISCSE-----NSAE----ITPVLG
*
>P1;Cer2
RD----------------PVF---AV--DRILDPSPPKE--AGKSDVKIW
K----E-HLVEI-LRE-AWKN----------TAE----IALKAQL-A-YQ
KQANQ-----------GAKGSE--IRPGDR--VMFKNFKSKINLSRK---
LVKP-WI--GDYRVLEVNH-----PKAL-----ILDLD
*
>P1;Cer3
RD----------------PVF---AI--DKIMHPSPPKE--GEEVDIPAW
K----E-HLITT-LRL-ARKE----------AAE----RSLKEQE-A-RQ
KVANV-----------GAKGSK--IVVGDR--VFFQNHKSKANLSRK---
MVLP-WI--GEFEVISIDH-----PKAV-----IKDLE
*
>P1;Cigr-1
FS----------------RRS-M-------TGT-----------TLPTWL
LT----------KG----------------PVLLRR--FVRTKGD-----
-----------------PLC----DQVELL---------------D---A
N--PTYA--N---IRHPDG-------------------
*
>P1;CsRN1
TT----------------LRL-P-------GEL-VSTS-GAQPES-PVTF
VTRL-K--Q-HMSELR-ATPT-----------RRSTR-KEHISTD----L
SSTP---------------------FVFVR----HDATRK----------
PLQPCYD--GPFKVIERH------SKYF----VLERSG
*
>P1;Kabuki
KN----------------IRL-P-------GDF-YDVS-KEENLCEPLSL
VNKI----QKIIKSFR-PVRE-----------NQTSR-SIFVHPD----L
HKCS---------------------FVFVR----DDAVHK----------
SLKPPYD--GPFRVIERG------PKVF----LVQLFD
*
>P1;Boudicca
TT----------------LRL-P-------GEF-VDPS-ASSLNMDLNSY
TSRL-T--NAMRSVKP-AHTR-----------SQST--DVFVQPE---LR
HST----------------------HVFVR----RD-SHR----------
PLESAYE--GPFKVLQRE------PKYY----VVDKNG
*
>P1;Osvaldo
RE----------------PRL-P----KTMFDAQTLGT--GQEAQSPIER
AAK--M--REVLEIVRRNLER----------AAQD---QARITI------
------------------CG----GGSGSR-LLGTKCGRR-NA---TC--
-PMPRTDLQRSW-HRDTEG-----HIRW-----SSLYR
*
>P1;Woot
RT----------------PPN-P-------LDAVTSGL---LPVRPPLT-
-----R--EEIHEKARENLKH----------HANL---RQKNQ-----KG
E-VTV-----------LEIE----DWVLLK-NKVTSDTRT-HQ---FA--
KFMPLYS--GPYKIIAKPH-----PNTY-----QIADP
*
>P1;Ulysses
--------------------------------------------------
--------QQMYLNGSSYK------------LAR----KLS-LAD-----
----------------------------------HSISDL-DA----K-D
RLAVIR----SQ--VKDHL-----HTAY-----ERSRQ
*
>P1;Circe
---------------------------------------------KHMIS
HG------NDYKLLRK-LN-------------------------------
-------L--------LTEG----D-VKLS------------R---TD--
-EFQRI---RSN--IARHL-----NKAY-----ETNQK
*
>P1;Gmr1
RR----------------PRG-ILDLA--KEAWESHPSPHRTTIEHVELV
RD---RM-AKVWPIVR-DHLT----------RAQQ---AQARVYN---RG
ARVRN-----------FRPGD---R-VLV--LVPTSE------------C
KFLAKWQ--GPYEVVEAVG-----PVNY-----KVRQP
*
>P1;rGmr1
RQ----------------PRG-LLDVA--RQAWEQEPAPQRSLIEHVQDM
RQ---RI-ERVMPLVR-QHLT----------EAQH---AQRRLYD---RP
AQARE-----------FQPGD---Q-VLV--LVPTAT------------S
KFLASWK--GPYVVVEKVG-----PANY-----RVRQP
*
>P1;RetroSor1
EE----------------AML-P-------EEIKHQSLRS---MKQQLAE
DE---E--Y---CKET-LESIRLEAVENITRYQQ----ETKNWRD----R
KVVRKD----------IQNG----D-LVLR-----KKGDH-----PNA-G
KLQPKWE--GPYTAIQAGR-----SGSF-----YLKDL
*
>P1;Cinful-1
DE----------------AIT-P-------EEAKTGSIRV---VASAASG
SE---A--DYSVEKDA-LEGIRLQAVENINKYQA----ETIKWRD----R
KVRLKN----------IEPD----TWCFRR-----VA-NP-----ETV-G
KLQLKWD--GPFLVASSSR-----PGSY-----RLKDM
*
>P1;B1147A04.5
AE----------------AVL-P-------SELTLRSPRA---TMYCEAD
QD---Q--FRRDDLDY-LEEQRRRAALRAARYQQ----SLRRYHQ----R
HVRARS----------LCVD----D-LVLR-----RVQTR-----ARL-S
KLSPMWE--GPYRVIGVPR-----PGSV-----RLATG
*
>P1;Ogre
ME----------------AVL-P-------VEVEIPSLRVLLDVKLDEAE
WI---R--TRFNELSL-IEERRLAVVCHGQLYQR----RMKRAFD----Q
KVRPRS----------YQIG----D-LVLK-----RILPP---GTDNR-G
KWTPNYE--GPYVVKKVFS-----GGAL-----MLTTM
*
>P1;Grande1-4
--------------------------------------------------
--------------------------------------------------
---THL----------FSVG----L-VLLR-----RILTG-----EGR-H
KLSPLWE--GPFMVAEVTR-----PGSY-----RLTQM
*
>P1;Tat4-1
IE----------------AMA-P-------AEVSVGSLRR--TMLVNNPL
NN---R--MLLSNIDD-AEEFRDSALLRIQNYQQ----AAARHYN----T
KVKPRS----------FTVG----D-LVLR-----KVYENT--AELNA-G
KLGAKWE--GPYLVSKVVR-----SGVY-----ELLTM
*
>P1;Tft2
ME----------------AVV-P-------AELNVPGLRR--TAPLNEEE
NS---A--MLHDSLDT-INERRDQALIRIQNYQH----AEARYYN----S
KVKSRP----------FFVG----D-YVLK-----RVFDNK--KEEGA-G
KLGINWE--GPYIVIEVVW-----NGVY-----KLKDL
*
>P1;RIRE2
AE----------------AML-P-------SEVEFESLRF---RNFREER
YE---E--DRVDDLHR-LEEVREAALIRSARYLQ----GLRRYHN----R
NVRSRA----------FLVG----D-LVLR-----KIQTT-----RDR-H
KLSPLWE--GPFIISEVTR-----PGSY-----RLKRE
*
>P1;412
RT----------------SNL-P-------KHFNKLHSIEPIYNIDDYAK
ES---K--YRLEV-----------AYARARKLLEAHKEKNKENYD-L--K
VKDIE-----------LEVG----DKVLLR------NE--------VG-H
KLDFKYT--GPYKIESIGD-----NNNI-----TLLTN
*
>P1;Mdg1
RL----------------PRQ-F-------IDFNRIDRIDPIYNMDDYSK
EV---K--LRLEI-----------AYRRAKNMLDKAKADRKIKYD-R--N
ISNFE-----------LKIG----DKILLK------NE--------TG-H
KLDNNYL--GPYLVSEIGD-----NDNI-----TIIGN
*
>P1;Blastopia
TK----------------MYTRV--------EDRLLELLQEEVVCQ-FN-
E-------DRYEMRQ---------LVKRNIEQAQ--KDYKRNY-D-K--K
RRAEYK----------YKAG----DLVAIK----RTQF-------VAG-R
KMASGYL--GPYEVTGVKD-----NGRY-----DVKKA
*
>P1;Micropia
KQ----------------AR--P------------LGLVPPCETECEIDL
A----T--VR--------------A-HATENMNSLASYD-KSRFD-S--S
RAAVDK----------HHVG----DYVLLR------NE------ERHQ-T
KLDPKFR--GPFLVTEVLE-----GDRY-----TLKSL
*
>P1;Mdg3
LQ----------------QK--G-------QIMD--ELKEKIEEIGETIE
E-------RDLES-----------IRNKGEASQKIAQAYNKEYVD-K--K
RKRSGV----------FTKG----TTSWLK---ILTQQ-------QAA-K
KLIPKHK--GPYVISKVLK-----NDRF------LLED
*
>P1;HFV
ID----------------SNT-P-------------------------FA
NQ---D----TLDLTR-EEEL------SL--LQEI-----RTSLY----H
PST-PPASSRSWSPVVGQLV----QERVAR---------------PAS-L
R--PRWH--KPS-TVLK-------VLNP-----RTVVI
*
>P1;SFV-1
VD----------------SNT-P-------------------------FA
NS---D----TLDLSR-EEEL------SL--LQEI-----RSSLH----Q
PTS-PPASSRSWSPSVGQLV----QERVAR---------------PAS-L
R--PRWH--KPT-AILE-------VVNP-----RTVII
*
>P1;EFV
VD----------------CNL-P-------------------------FQ
DL---S----TLDLTR-EEQL------AV--LQEI-----RTALE----Q
PA--QHPTLPKWTPCPGLLV----QERVNR---------------PAQ-L
R--PKWK--KPT-PILK-------VLNP-----KTVVI
*
>P1;BFV
AD----------------CNL-P-------------------------FE
NL---D----TLDLTR-EEQL------AV--LKEV---RDGLLDL----Y
PSP-SQTTARSWTPSPGLLV----QERVAR---------------PAQ-L
R--PKWR--KPT-PIKK-------VLNE-----RTVII
*
>P1;FFV
ID----------------CNL-P-------------------------FA
NK---D----TLDWTR-EEEL------AL--LQEI-----RESLQ----H
PV--QPPTCSGWSPYVGQLV----QERVYR---------------PSQ-L
R--PKWR--KPT-KVLE-------ILNP-----RTVII
*
>P1;DrFV-1
KV----------------GDI-V------------------------YIQ
KR---V----RGHRFK-ENLG------T---EDKV-----K-SI------
PS---NTTVE--LEANG----------------------------IWS-L
R--DIIK--KPE--------------------------
*
>P1;HERV-K10
KKNS--------------PHE-----------------------------
-G--------KL--------------------------------------
--------------------------IWWK----------------DN-K
N--KTWE--IG-KVI-TWG-----RGFA-----CVSP-
*
>P1;MPMV
-NN---------------PKK-----------------------------
QF--------AM--------------------------------------
--------------------------VKWK----------------DP-L
D--NTWH--GPDPVL-IWG-----RGSV-----CVYS-
*
>P1;MMTV
------------------PIS-AD--------------------------
PK--------PM--------------------------------------
--------------------------VMWK----------------DL-L
T--GSWK--GPDVLI-TAG-----RGYA-----CVFP-
*
>P1;SERV
------------------PES-QK--------------------------
QF--------AM--------------------------------------
--------------------------VKWK----------------DP-L
D--NSWH--GPDPVL-IWG-----RGSV-----CIFS-
*
>P1;SRV-1
SN----------------PRK-----------------------------
QF--------AM--------------------------------------
--------------------------VKWK----------------DP-L
D--NTWP--WPDPVI-IWG-----RGSV-----CVYS-
*
>P1;JSRV
ERS---------------SCK-----------------------------
-K--------PL--------------------------------------
--------------------------VRWK----------------DP-L
T--NLWY--GPDPVL-IWG-----RGHV-----CVFP-
*
>P1;SMRV-H
------------------PQT-SQ--------------------------
QH--------AT--------------------------------------
--------------------------VMWR----------------DP-L
T--SVWK--GPDPVL-IWG-----RGSA-----CIYD-
*
>P1;K-HERV
-KNS--------------PH------------------------------
EG--------KL--------------------------------------
--------------------------IWWK----------------DN-K
N--KTWE--IG-KVI-TWG-----RGFA-----CVSP-
*
>P1;PyERV
SQ----------------PAA-DH--------------------------
QR--------PL--------------------------------------
--------------------------VYYR----------------CL-P
D--PAWR--GPAQLI-TWG-----RGYA-----AIQL-
*
>P1;LPDV
--------------------------------------------------
HQ--R------LP-----IGP---A-------------------------
--------------------------VLVR----------------DH-L
G---AWQ--GGWHLM-TVG-----RGYA-----VG---
*
>P1;RSV
--------------------------------------------------
PT--V------LT-----EGP---P-------------------------
--------------------------VKIR----------------IE-T
G---EWE--KGWNVL-VWG-----RGYA-----AVKN-
*
>P1;STcLV2PP1664
PR------------------------------------------------
LR--P------IP-----ETP---RP----SRA---PTNW----------
--------------------------YYYK--------LP------GL-T
N--QRWK--GPLQSL-QEA-----AGAA-----LLSI-
*
>P1;HTLV-2
PP------------------------------------------------
LP--P------IS-----EAS---TP----PKP---PPKW----------
--------------------------FYYK--------LP------GL-T
N--QRWK--GPLQSL-QEA-----AGAA-----LLSI-
*
>P1;HTLV-1
PR------------------------------------------------
LQ--P------IP-----ETH---SL----SNK---QTHW----------
--------------------------YYFK--------LP------GL-N
S--RQWK--GPQEAL-QEA-----AGAA-----LIPV-
*
>P1;BLV
PP------------------------------------------------
LA--V------IS-----EGG---ET----PKG---SDKL----------
--------------------------FLYK--------LP------GQ-N
N--RRWL--GPLPAL-VEA-----SGGA-----LLAT-
*
>P1;HIV-2
MI-----------------------------------------T---T--
EQ--E------IQ-----FLQ---AK----NSK---LKDF----------
-------------------------RVYFR----------------EG-R
D--QLWK--GPGELL-WKG-----EGAV-----LVKV-
*
>P1;HIV-1
II-----------------------------------------A---T--
DI--Q------TK-----ELQ---KQ----ITK---IQNF----------
-------------------------RVYYR----------------DS-R
D--PIWK--GPAKLL-WKG-----EGAV-----VIQD-
*
>P1;EIAV
TN----------------Q------------------------A---Q--
VI--H------EK-----LLL---QQ----AQS---SKKF----------
--------------------------CFYK-----I----------PG-E
H--D-WK--GPTRVL-WKG-----DGAV-----VVND-
*
>P1;SIVMAC
MI-----------------------------------------T---T--
EQ--E------IQ-----FQQ---SK----NSK---FKNF----------
-------------------------RVYYR----------------EG-R
D--QLWK--GPGELL-WKG-----EGAV-----ILKV-
*
>P1;SIVAGM
MI-----------------------------------------T---T--
QL--E------IQ-----HIQ---TQ----QQK---ISNF----------
-------------------------KVYYR----------------EG-R
E--PVWK--GPATLL-WKG-----EGAV-----VIKE-
*
>P1;SIVMND
MI-----------------------------------------N---T--
EL--E------YQ-----YQQ---NQ----ISK---NLNF----------
-------------------------KVYFR----------------EG-R
D--QLWK--GPGILL-WKG-----EGAV-----VLKY-
*
>P1;VMV
FN-----------------------------------------K---E--
QQ--R------IQ-----QQS---KS----KQE---KIRF----------
--------------------------CYYR-----T--RK------RG-H
P--GEWQ--GPTQVL-WGG-----DGAI-----VVKD-
*
>P1;SA-OMVV
FN-----------------------------------------K---E--
QQ--R------IQ-----QQS---TR----NQS---KFRF----------
--------------------------CYYR-----V--RK------RG-H
P--GEWL--GPTQVL-WEG-----EGAI-----VIKD-
*
>P1;CAEV
YN-----------------------------------------K---E--
QK--R------IN-----NKY---NK----NSQ---KIQF----------
--------------------------CYYR-----I--RK------RG-H
Q--ESGK--DQPRYC-GKG-----KEPI-----VVKD-
*
>P1;FIV
Q----------------------------------------QES---L--
RI--Q------DY-----FSA---IP----QKL---QAQW----------
--------------------------IYYK----------------DQ-K
D--KKWK--GPMRVE-YWG-----QGSV-----LLKD-
*
>P1;BIV
ES----------------E-----------------------HT---K--
YQ--D------QL-----EQQ---FS----KQK---IEKW----------
--------------------------CYVR-----------------N-R
R--KEWK--GPYKVL-WDG-----DGAA-----VIEE-
*
>P1;KoRV
GP----------------PPV-L-------ASGEVVGSN--GDFFPVLFT
HL---K----ALEV---VRTQ---IWDQ---IKE----AYRPGT------
----------VAIPHPFQVG----DRVLVR-----R--HR-S----GS-L
E--PRWK--GPYLVL-LTT-----PTAV-----KVDG-
*
>P1;REV
LK----------------PPV-V-------PRVGCDKLA--SITNQTLLK
SL---Q----ALQA---TRSL---ARAA---LRD---QLPQKEAQ-----
----------QDRTPLFQPG----DLVFVK-----K--HD-F----QQ-L
G--PRWD--GPYTVV-LST-----PTAV-----KVAG-
*
>P1;HERV-E
RP----------------PPI-L-------RGLPGTPRELGEIELQRLQA
SG---K----ITQT---I--S---AW-----VNE-----RCPVNL-----
----------FSPVHPFSPG----DLVWIK-----D--N--V----AC-L
C--PRWK--GPQTVI-LST-----PTAV-----KVEG-
*
>P1;RTVL-Ia
LP------------------------------YLYSTAN-----IP--TF
KI---K-----DQF---LK-N----Y-----ILG----PYST--------
----------FSSLKT--KG-----------------------------L
---LAQA--PPLEFP-AHR-----QPGD-----HVLI-
*
>P1;MdEV
GP----------------PPL-I-------KDGGTLVPDSGSVLPSSLLI
HL---K----ALKV---IRTQ---IWDQ---LKT----AYTPGT------
----------TAVPHEFQVG----DQVLVR-----R--HR-T----GS-L
E--PRWK--GPYLVL-LTT-----PTAV-----KVDG-
*
>P1;PERV-MSL
GP----------------PPL-V-------EIASVHSAD-VLLSQP-LFS
RL---K----ALEW---VRQR---AWRQ---LRE----AYSGGGD-----
----------LQIPHRFQVG----DSVYVR-----R--HR-A----GN-L
E--TRWK--GPYLVL-LTT-----PTAV-----KVEG-
*
>P1;FeLV
AP----------------PPM-A-------HFFDTDISS--FATSPTMQA
HL---R----ALQL---VQEE---IQRP---LAA----AYREKLE-T---
----------PVVPHPFKPG----DSVWVR-----R--HQT-----KN-L
E--PRWK--GPHIVL-LTT-----PTAL-----KVDG-
*
>P1;RCHO-K1
VP----------------TPI-I-------NFLDQDVSD--FANSPSLQA
HL---Q----ALQL---VQRE---IWKP---LAQ----AYKDQRDH----
----------PTIPHSYQIG----DTVWVR-----R-SPR-P----RT-L
N--PTGR--DPTSFC-LPL-----PPHS-----K-DG-
*
>P1;BAEVM
GP----------------PPL-S------TLLNSFSPSN----SKTDLQA
RL---K----GLQA---VQAQ---IWAP---LAE----LYRPGHS-----
-----------QTSHPFQVG----DSVYVR-----R--HR-S----QG-L
E--PRWK--GPYIVL-LTT-----PTAI-----KVDG-
*
>P1;MuLV
AP----------------PPL-V--------NFHDPEMS-KLTNSPSLQA
HL---Q----ALQA---VQRE---VWKP---LAA----AYQDQLD-Q---
----------PVIPHPFRVG----DAVWVR-----R--HQ-T----KN-L
E--PRWK--GPYTVL-LTT-----PTAL-----KVDG-
*
>P1;GALV
GP----------------PPI-L-------ESGETLGPD--DRFLPVLFT
HL---K----ALEI---VRTQ---IWDQ---IKE----VYKPGT------
----------VTIPHPFQVG----DQVLVR-----R--HR-P----SS-L
E--PRWK--GPYLVL-LTT-----PTAV-----KVDG-
*
>P1;WdSV
RP----------------MKTTY-----LSDMSPLWATD--TLVT--YMN
KL-TRQL--SAYHQ---QVVD---Q------W-------PST--------
----------SLPP-GPEPG----SWCMLR-----N-PKK-------S-S
N----WE--GPFLIL-LST-----PTAV-----KVEG-
*
>P1;XEN1
CA----------------PRL-G------CYFPQTLQLQFDVLNEYVCQL
SN---E-----LSK---VHGQ---V------FSS----IPDPTS------
----------VEGSHSLVPG----DWVLVK-----KFLRK------SS-L
E--PRFD--GPFQVL-LTT----ATSV------KLDG-
*
>P1;ZFERV
RQ----------------FPG-P--------VAPLHAGD---TDSP-QMY
HD-KVC---AVINM---FSPQ---KS-----W-------PTESE------
----------ASRP-AENTT----LWVRLK-----Q-HKR------KW-S
S--PRWS--EPLRVTARTS-----HCV------QLAG-
*
>P1;ASSBSV
RV----------------MPG-P-----PREGGHMPALDVHQIGMTDYVR
KL-TELS--AALSI---Q-IQ---------RVAEG---ELTDD-------
----------QDQP-RVKVG----DWVRIK-----V-HKR------KW-A
D--PRWT--GPYEVKEVTS-----HSV------QVKG-
*
>P1;ZFERV-2
CP----------------MPV-P----FCRGPYKEPPLEQLQMELRSYMK
NL---T---AIHKA---IYVQ---ET-----RKG-----VREE-------
----------VETPGPVVPG----DQVYLK-----V-FRR------KW-N
E--ARRE--GPYRVIRATP-----TAV------QVEG-
*
>P1;SnRV
RV----------------PHL-G--------GYHPHPLETAKEEEVRIFL
RATHDC---MQNKK---WEEQ---LEKV--TKAE----AHSHW---T---
----------QRSP-NLEPG----CIVLVR-----K-FTG------DA-F
S--PKWE--GPYVIT-ETT-----KYAA-----KVQA-
*
>P1;MuERV-L
RN----QGVEKGIVPLTITHSDPLGKFLLPVPITLGSAGLEVLA---P--
EA--G------VL-----LPG---AT----TNI---PLNW----------
--------------------KL--RLPPGH----FGLLMPLN--QQAK-K
G--ITVL--GGVIDPDYHG-----EIGL-----SLHN-
*
