>P1;NEF_SIVMAC

MGGAISKKRSKPPRDLRQRLLRARGENYGRLFKGVEDGSSQSLGGLDKGLSSLSCEGQKY
NQGEYMNTPWRNPAEERKKLPYRKQNIDDIDEEDDDLVGIPVEARVPLRTMSYKLAIDMS
HFIKEKGGLEGIYYSARRHRILDIYLEKEEGIIPDWQIHS-GPGIRYLKMFGWLWKLIPV
NVS--DEAQEDEEHYLVHPAQTSQWDDPWGEVLAWKFDPTLAYTYEAYIRYPEEFGSKSG
L
*
>P1;NEF_HIV-2

MGASGSKKHSRPPRGLQERLLRARAGACGGYWNESGGEYSRFQEGSDREQKSPSCEGRQY
QQGDFMNTPWKDPAAEREKNLYRQQNMDDVDSDDDDQVRVSVTPKVPLRPMTHRLAIDMS
HLIKTRGGLEGMFYSERRHKILNIYLEKEEGIIADWQNYTHGPGVRYPMFFGWLWKLVPV
DVP--QEGEDTETHCLVHPAQTSKFDDPHGETLVWEFDPLLAYSYEAFIRYPEEFGHKSG
L
*
>P1;NEF_SIVAGM

MGGSNSKREQQGLLRLWRALRKAPVVRYGMLADPLIGQSSNIQEECDKN-----WNGGST
RRG-------KSTPEGRK--LAADDTWDDWEPEEEE-VGFPVRPRVPLRQMTYKLAVDFS
HFLKEKGGLEGIYWSPKREQILNLYALNEWGIIDDWQAYSPGPGTRKPRCFGFCFELVPV
DVS--QEAQD-ERHCLLHPAQIEWESDPWKETLVWKFNPLLAVQYN-----PDSFKDMHG
L
*
>P1;NEF_HIV-1

MGSKWSKSSKEGWPQVREKIKQTPPAAEG------VGAVSQDLD----------------
----------KHGAITSSNINNAACSWLGAQEEDEEEVGFPVRPQVPLRPMTFKGAFDLS
FFLKEKGGLDGLIHSKRRQDILDLWVYNTQGYFPDWQNYTPGPGIRYPLCFGWCFKLVPV
DPGEVEEDNKGENNCLLHPMSQHGIEDADREVLMWKFDSSLARKHIARELHPDYYKDC--
-
*
>P1;NEF_SIVMND

MGSSQSKKRSEAWVRYSSALRQLVGGPVTPDGYKQIE-SSQGAEK-QSL-LRGRAYG-TY
SEG-------LDKVQNDPLTKDEKLDLTQQDPEEEEEVGFPVCRQVSLRVPSYKDLIDFS
HFIKEKGGLGGIYYSRRREEILDLYAENEWGFEPGWQQYTTGPGTRYPKTFGFLFKLEPV
SRAIGDEYAA--NNHLLHSSQLCPQEDPEGETLMWSGTLILPMTLQH-------------
-
*
