>P1;ORFW_SA-OMVV

MHTGRNSEAHRAKELATLSIIAYSKKPCISDNAALESKESNSAKVPMVRDRRVIRYLGLY
RIAGTWN-QYIING-GSTKKKARRQQRS
*
>P1;ORFW_VMV

VYTRGDSE-YKSKKLTTLSFIAPSKRPCISSNAIVESQESHSAEVSMV----VTRYLGLC
RNAGKWN-PSLNNG-RSTKKTARRLSRS
*
>P1;ORFW_CAEV

LCSRRSSKAYN-KKSGKTSTATDGRTACVSSIAIVESQEKSTTDFPWCRDT--TGYTHAW
SVQECWLMEYLLEDERTASKKGDTSRRT
*
