>P1;REV_HIV-1

MAGRSGST---------------DEELLAAVRIIKILYQSNPEPSPEG-TRQSRR-----
-------NRRRRWRARQRQI-RALSERILSSCL--GRSTEPVP---------LQL--PPI
ERLHLDCSEDCGTSGTQQ
*
>P1;REV_SIVMND

MLVQEM-----------------LLSLYALLSKE-GFRNKVPCLQETWLSTCLFTGLPAE
PIPQTARQRRRR-KQQLRTR-RAQ-LRELEGRILKQILDRGPD----------QL-CQGV
TNLALAEKSESSN-----
*
>P1;REV_SA-OMVV

MASSKN-----------------MPSRITQKSMEPPLRETWQQVVQEMVMRKQR------
-------DEEEKQNLVTGLQ-ASSGDPIYTGNSS-DRSTRGPGGKTKRRK--GWF--QWL
RKLRAREKNIPSQFYPDM
*
>P1;REV_VMV

MASKES-----------------KPSRTTRRGMEPPLRETWNQVLQELVKRQQQ------
-------EEEEQQGLVSGLQ-ASKADQIYTGNSG-DRSTGGIGGKTKKKR--GWY--KWL
RKLRAREKNIPSQFYPDM
*
>P1;REV_SIVMAC

MRSHTG-----------------EEELRRRLRLIHLLHQTNPYPTGSGSANQRR------
-------QKRRRWRQRWQQL-LALADRIYSFPD--PPTDTPLD---------LAI--QQL
QNL----AIES---IPDP
*
>P1;REV_HIV-2

MNERAD-----------------EEGLQRKLRLIRLLHQTNPYPQGPGTASQRR------
-------NRRRRWKQRWRQI-LALADSIYTFPD--PPADSPLD---------QTI--QHL
QGL---TIQE----LPDP
*
>P1;REV_SIVAGM

MSLG-------------------SEDLRRIIQIIRILYHSNQYPPGEGTARQRR------
-------RRRQRFQQQQRQV-AALSERIFIAQQRRDPSGGESLA--------AAF--DQL
VLD---NQQLVIETLPDP
*
>P1;REV_CAEV

MVLMAK-----------------VYSYYSSRIIRMHSDKSCDMCMSTSCADIQ-------
-------NSKYPDIPTGHSH-HGNKSRRRRRKS-------------------GFW--RWL
RGIRQQRNKRKSDSTESL
*
>P1;REV_BIV

MDQDLD-----------------RAERGERLDFLERLDKN-HYSNHCTLASDKD------
-------SPRYVKKLRQGQP-ELPTSPGGGGGRGHRARKLPGERRP------GFW--KSL
RELVEQNRRKQERRLSGL
*
>P1;REV_FIV

MAEGFAA----------------NRQWIGPEEAEELLDFDKATQMNEEGPLNPG------
-------VNPFRVPAVTEAD-KQEYCKILQPRLQ-EIRNEIQEVKLEEGN--AGM--KKK
RQRRRRKKKAFKKMMTDL
*
>P1;REV_EIAV

MAESKEARDQEMNLKEESKEEKRRNDWW-KIDPQGPL-ESDQW---CRVLRQSLP-----
-------EEKIPSQTCITRRHLGPGPTQHTPSRR-DRWIRGQILQAEVLQERLEWRIRGV
QQAAKELGEVNRGIWREL
*
