>P1;REX_STcLV2PP1664

MPKARRQRTRRTRSNRPPTPWPTFQVSDR---ASSMDT-QSTCLA--IVFKPIGVPFQVG
FVPPACTGMPFSPPARSTSSPGTPSMDALSALLSNTLSLGSPPSPPREPPRPSRSSLPLP
-LLS-PPRFHPPFSNPCVNSPPTGTGAYTQLSET---SSPPLPSPT-PVSGPKTSTPPGE
EP--
*
>P1;REX_HTLV-2

MPKTRRQRTRRARRNRPPTPIS--QDLDR---ASYMDT-PSTCLA--IVYRPIGVPSQVV
YVPPAYIDMPSWPPVQSTNSPGTPSMDALSALLSNTLSLASPPSPPREPQGPSRS-LPLP
PLLS-PPRFHLPSFNQCESTPPTEMDAWNQPSGI---SSPPSPSLN-LASVPKTSTPPGE
KP--
*
>P1;REX_BLV

MPKERRSR-RRPQ---PIIRWQVLLVGGP---TLYMPARPWFCPM--MSPSMPGAPSAGP
MNDSNSKGSTPRSPARPTVSPGPPMDDLLASMEHCSLDCMSPRPAPKGPDDSGSTAPFRP
FALS-PARFHFPPSSSPPSSP-TNANCPRPLATVA-PSSG-------------TAFFPGT
T---
*
>P1;REX_HTLV-1

MPKTRR-RPRRSQRKRPPTPWAHFPGFGQSLLFGYPVYVFGDCVQGDWCPISGGLCSARL
HRHALLATCPEHQI---TWDPIDGR-VIGSALQFLIPRLPSFPTQRTSKTLKVLTPPITH
TTPNIPPSF-LQAMRKY--SPFRN-GYM-EPTLGQHLPTLSFPDPGLRPQNLYTLWGGSV
VC--
*
