>P1;ROF_ORFI__HTLV-1

MPKTRRQRTRRARRNRPPTPWDLLFPFQEIHITLKQVTKPIKTQESYTLQ
LLMPFFPLPALLILFPQALLSAPLPLLTLLQKF
*
>P1;ROF_ORFI__HTLV-2

MPKTRRQRTRRARRNRPPTPWDLLFPFQEIHITLKQVTKPIKTQESYTLQ
LLMPFFPLPALLILFPLALLSAPLPLLTLLQKF
*
>P1;ROF_ORFI__STcLV2PP1664

MPKARRQRTRRTRSNRPPTPWPLP---------------------SALLL
LLALFQNFHDFLLLFRQRPP-ATIPYI-LSDRP
*
