>P1;SORF2_MPMV

VFCPEPCCPDDVLASVCSSSML-I-DGVFPGSSPSYFPAGANVSRSWAYVAFLALLLSMR
PVSFPSHLLPVYIRQHIATIK
*
>P1;SORF3_MPMV

IKSPMLYRLDDVLASVCSSSML-I-DGVFPGSSPSYFPAGANVSRSWAYVAFLALLLSMR
PVSFPSHLLPVYIRQH-----
*
>P1;SORF1_MPMV

VTCPEPCCPDDVLASVCSSSML-I-DGVFPGSSPSYFPAGANVSRSWAYVAFLALLLSMR
PVSFPSHLLPVYIRQHIATIK
*
>P1;3'SORF_SRV-1

VTCPEPCCPDDVLASVCSSSTLKIQDGELPGSSLCCFPAGANVSRS-AYVAFPVLQLSMR
PVLLPSHLLPVYIRQRIATIK
*
>P1;5'SORF_SRV-1

--CPEPCCPDDVLASVCSSSTLKIQDGELPGSSLCCFPAGANVSRS-AYVAFPVLQLSMR
PVLLPSHLLPVYIRQRIATIK
*
