>P1;TAT_SIVMAC

ME-TPLREQENSLESSNERSSYISEAAAAIPESANLGEEILSQLYRPLEACYN-TCYCKK
CCYHCQFCFLKKGLGISYEKSHRRRR--TPKKAKANTSSASNEPIPNRIRLCQPKKAKKE
T
*
>P1;TAT_HIV-2

ME-TPLKAPESSLKSCNEPFSRTSEQDVATQELARQGEEILSQLYRPLETCNN-SCYCKR
CCYHCQMCFLNKGLGICYERKGRRRR--TPKKTKTHPSPTPDKSISTRTGDSQPTKKQKK
T
*
>P1;TAT_HIV-1

ME-LVDPKLEP----------------------------WNHPGSQPTTACN--KCYCKK
CCWHCQLCFLKKGLGISYGRKKRKHRRGTPCSSKNHQNPLPEQPRTITRGNPTVPKESKK
E
*
>P1;TAT_SIVAGM

MESEG-DGMAES---------------------------LLQDLHRPLTPCTN-KCFCKR
CCYHCQVCFLQKGLGITYHVSR-IRR--PKKNHSNHQNLVSQQSISAWGGNSQTTQEEKT
K
*
>P1;TAT_SA-OMVV

MEEAP-RRRPG----------------------------GSREAEGIFRYYEDWECWDHV
S-QRVPNEVLQRWLAM-LTNNQLRRK--VIREAQIWMWKNANAPIRRNCG-CRLCNPGWG
S
*
>P1;TAT_VMV

MEEVP-RRQPG----------------------------GLVEVEGVFQFYEDWECWDYV
S-QRVPGERLQRWLAM-LTNNQLRRQ--VIREAQIWMWKHKGAAVRRNCG-CRLCNPGWG
S
*
>P1;TAT_CAEV

SEELP-QRRET----------------------------HPEELVRNVRERE-RDTWQWT
S-IRVPAEILQRWLAM-LRSGRNRKK--VYREMQKWMWIHPKAPVIRACG-CRLCNPGWG
T
*
>P1;TAT_BIV

LPQ-P-KESFGGK-----------------------PIGWLFWNTCKGPRRDCPHCCCPI
CSWHCQLCFLQKNLGVNYGSGP-RPRGTRGKGRRIRRTASGEDQRREADS--QRSFTNMD
Q
*
>P1;TAT_EIAV

MLNLADRRIPG-------------------------TAEENLQKSSGGVPGQNTGGQEAR
PNYHCQLCFL-RSLGIDYLDASLRKK---NKQRLKAIQQGRQPQYLL-------------
-
*
>P1;TAT_SIVMND

MEPSG-KEDHNCPPQDSGQE-------------EIDYKQLLEEYYQPLQACEN-KCWCKK
CCFHCMLCFQKKGLGIRYHVY--RKRVP-GTNKKIPGSG--EEAIRRAID-LSFHRTASR
T
*
