>P1;TOF_ORFII__STcLV2PP1664

MPFFSPLS---RFRTEPPLWIPSLRVWRLCSSRLVSRFRWALFHPPAPAC
PSRHLPGAPAHLGPHRWTRCRLSSPIPYPSAPLLPHPENLQDPQGPHSPY
HSCLPQDSTRLFPIHA
*
>P1;TOF_ORFII__HTLV-2

ITILSPLSPFPRIWTEPPIWIPRLRVWRLCTGRLVSRLRWSMFHPPTSTC
PPGHLSRAPTHLGPHRWTRCQLSSPIPYPSPPLLPHPENLKDPQGPYPSH
HSCLPQGSTCLLSINA
*
>P1;TOF_ORFII__HTLV-1

MLIISPLP---RVWTESSFRIPSLRVWRLCTRRLVPHLWGTMFGPPTSSR
PTGHLSRASDHLGPHRWTRYRLSSTVPYPSTPLLPHPENL-DP-GPYPAN
HSYNPQHSTLLPPGHA
*
