>P1;VIF_SIVMAC

MEEEKRWIVVPT-WRIP-ERLERWHSLIKY-LKYKTKD-LQ-KACYVPHHKVGWAWWTC-
-SRVIFPLQEGSH-LEVQGYWNL-TPERGWLST-YAV---RIT-WYSKD--FWTDVTPEY
ADILLHSTYFPCFTAGEVRRAIRGERLL-SCCRFPRAH-KHQVP----S--LQ-YLALRV
VS
*
>P1;VIF_HIV-2

MEEDKRWIVVPT-WRVP-GRMEKWHSLVKY-LKYKTKD-LE-KVCYVPHHKVGWAWWTC-
-SRVIFPLKGNSH-LEIQAYWNL-TPEKGWLSS-YSV---RIT-WYTEK--FWTDVTPDC
ADVLIHSTYFPCFTAGEVRRAIRGEKLL-SCCNYPRAH-RAQVP----S--LQ-FLALVV
VQ
*
>P1;VIF_HIV-1

MEN-R-WQVMIV-WQVDRMRIRTWNSLVKH-HMYVSKK-AK-RWLYR-HHYESQNPKVS-
-SEVHIPLR-EAR-LVIKTYWGLQTGEKDWQLG-HGV---SIE-WRQGN--YSTQIDPDL
ADRLIHLQYFDCFSDSAIRTAILGRVVR-SRCEYPSGH-N-KVG----S--LQ-YLALKA
LT
*
>P1;VIF_BIV

M-E-RPLQSVVGRRRGSSNRGRGKNSLIST-PSYALHP-PP-RFRY-PRW-EFVRQTEYS
MTACVRKGKLVLI-YQYAIWKRVWTIETGFTDP-SLF---MTP-AGTHT--TEEIGHLDL
FWLRYCSCPHEMPPWLDFLRGTLNLRIS-CRRALQASV-LTSTP----RHSLQRLAALQL
CT
*
>P1;VIF_FIV

MSD-EDWQVSRRLFAVLQGGVYNAMLYISR-LPQDERE-KY-KKDFKKRLLDTETGFIKR
LRK-AEGIKWSFHTRDYHVGY-VREMVAGPTTPHSLR---LYV-YISNP--LWHSQYRPG
LVNFNKEWPFVNLWIKTGFMWDDIEKQN-ICIGG-EVS-PGWGP----G--MI-GIAIKA
FS
*
>P1;VIF_SIVAGM

MEREKLWVTRL-TWRVSGEHIDKWKGIVK----YHMRNRLQ-DWTYLMHYQCGWAWYTC-
-SRFLIPLGGEGK-IVVDCYWHLTPE-QGWLST-YAV-AISFENW-Q-NT-YKTEVTPDV
ADHMIHCHYFPCFTDRAIQQAIRGESFL--WCTYKEGHVAENHWGQVRS--LQ-FLALTV
YT
*
>P1;VIF_SIVMND

MERVER-IVRL-TWKVSSQRIEKWHWLVRRQMAWATANNEEGCWWLYPHFMAYNEWYTC-
-SKVVIIINRDIR-LIVRSYWHLQIE-VGCLST-YAVSIEAVVRPPPFEKEWCTEITPEV
ADHLIHLHFYDCFMDSAVMKAIRGEEVLK-VCRFPAGHKA-QGVL---S--LQ-FLCLRV
IY
*
