>P1;VIF_BIV

VVGRRRG-SSNRGRGKNSLISTPSY--ALHPPPRFRYPRWE-FVRQTE--YSMTACVRKG
KLVLIYQYAIWKRVWTIETGFTDPSLFMTPAGTHT-TE----EIGHLD--L-F-------
--------------------------------------------WLRY----CSCPHEMP
PWLDFLRGTLNL-RI---S-CRRALQASVLTSTPRH--SLQRLAALQLC
*
>P1;VIF_FIV

MSDED-W-QVSRRLFA--VLQGGVYN-AMLYISRLPQDEREKYKKDFKKRLLDTE-TGFI
KRLRKAEGIKW-SFHTRD--YHVGYVREMVAGPTTPHSLRLYVYISNP--L-WHSQYRPG
LVNFNKEWPFVN--LWIKTGFMWDDIEKQNICIGGEVSPGWGPGMIGIAIKAFSCGERKI
EATPVMIIRGEINPKKWCGDCWNLMCLR-N-SPPE---TLQRLAMLACG
*
>P1;VIF_SIVMAC

MEEEKRW------IV---VP---TWRIPE-RLER-----WHSLIKY--LKYKTKD-LQ-K
ACYVPHHKVGWAWW-TCS-RVIFPLQEGSH-LEVQ-GY---WNLTPE--RG-WLSTYAV-
---RIT-WYSKD--FWTDVT--PEYADI----------------LLHSTYF--PCFTAGE
VRRAIR---GER-LL---S-CCRFPRAHKH-QVP----SLQYLALRVVS
*
>P1;VIF_HIV-2

MEEDKRW------IV---VP---TWRVPG-RMEK-----WHSLVKY--LKYKTKD-LE-K
VCYVPHHKVGWAWW-TCS-RVIFPLKGNSH-LEIQ-AY---WNLTPE--KG-WLSSYSV-
---RIT-WY-TEK-FWTDVT--PDCADV----------------LIHSTYF--PCFTAGE
VRRAIR---GEK-LL---S-CCNYPRAHRA-QVP----SLQFLALVVVQ
*
>P1;VIF_HIV-1

--MENRW------QV---MI---VWQVDRMRIRT-----WNSLVKH--HMYVSKK-AK-R
WLYR-HHYESQNPK-VSS-EVHIPLR-EAR-LVIK-TY---WGLQTG-EKD-WQLGHGV-
---SIE-WRQGN--YSTQID--PDLADR----------------LIHLQYF--DCFSDSA
IRTAIL---GRV-VR---SRC-EYPSGH-N-KVG----SLQYLALKALT
*
>P1;VIF_SIVAGM

MEREKLW------VT---RL---TWRVSGEHIDK-----WKGIVK-----YHMRNRLQ-D
WTYLMHYQCGWAWY-TCS-RFLIPLGGEGK-IVVD-CY---WHLTPE--QG-WLSTYAV-
-AISFENW-Q-NT-YKTEVT--PDVADH----------------MIHCHYF--PCFTDRA
IQQAIR---GES-FL----WC-TYKEGHVAENHWGQVRSLQFLALTVYT
*
>P1;VIF_SIVMND

MERVER-------IV---RL---TWKVSSQRIEK-----WHWLVRRQ-MAWATANNEEGC
WWLYPHFMAYNEWY-TCS-KVVIIINRDIR-LIVR-SY---WHLQIE---VGCLSTYAV-
SIEAVVRPPPFEKEWCTEIT--PEVADH----------------LIHLHFY--DCFMDSA
VMKAIR---GEE-VLK---VC-RFPAGHKA-QGVL---SLQFLCLRVIY
*
>P1;ORFQ_SA-OMVV

YRNQKKYKQNKIREVGPQLPLW-AWKEIAFSINQEPY--WYSTIRLQGLMW---NKRG-H
KLIFVKEENGYEYWETTNKQWRMELRRDLR-LIAQ--I--NFRN------A-WQ--YKS-
---QEK-WNIIGI-WY-DS--PGEYRDKEKQF------------WFHWRIAMCSCKKERW
DIRDFMV--GKHRWDLCKS-CIQGEIVR--HTEPR---SLQRLALLHIV
*
>P1;ORFQ_VMV

YRHQKKYKKNKAREIGPQLPLW-AWKETAFSINQEPY--WYSTIRLQGLMW---NKRG-H
KLMFVKENQGYEYWETSGKQWKMEIRRDLD-LIAQ--I--NFRN------A-WQ--YKS-
---QGE-WKTIGV-WY-ES--PGDYKGKENQF------------WFHWRIALCSCNKTRW
DIREFMI--GKHRWDLCKS-CIQGEIVK--NTNPR---SLQRLALLHLA
*
>P1;ORFQ_CAEV

SRHQQK-KRNKK--PGPELPLA-LWIHIAESINGDSS--WYITMRLQQMMW---GKRG-N
KLQYKNEDREYENWEITSWGWKMHLRRVKQ-WIQD-----NRRG-----SP-WQ--YKV-
---GGT-WKSIGV-WF-LQ--AGDYRKVDRHF------------WWAWRILICSCRKEKF
DIREFMR--GRHRWDLCKS-CAQGEVVK--HTRTK---SLERLVLLQMV
*
