>P1;VPR_SIVMAC

MEER----PPENEGPQREPWDEWVVEVLKELKEEALKHFDPRLLTALGNHIYNRHGDTLE
GAGELIRILQRALFIHFRS-GCSHSRIGQPGGGNPLSTIPPSRSML
*
>P1;VPR_HIV-2

MAEAPTELPPVDGTPLREPGDEWIIEILREIKEEALKHFDPRLLIALGKYIYTRHGDTLE
GARELIKVLQRALFTHFRA-GCGHSRIGQTRGGNPLSAIPTPRNMQ
*
>P1;VPR_HIV-1

MEQN-----PENQGPQRDNG--WTLELLEELKNEAVRHFPRPWLHGLGQYIYTTYGDTWE
GVEAIIRILQQLLFVHFRI-GCQHSRIGIFPGRRGRNGAG--RS--
*
>P1;VPR_SIVMND

MGQKRDEQVSEDQGPPREPYNQWLADTMEEIKEEARKHF-PLIILNAVSEYCVQNTGSEE
EACEKFITLMNRAIWVHLAQGCD-GTFRERRPQLPPSGFRP-RGDR
*
