>P1;VPX_HIV-2

MTDPRETVPPGNSGEETIGEAFAWLNRTVE---AINREAVNHL-PRELIFQVWQRSWRYW
HD-EQGMSESYTKYRYLCIIQKAVYMHVRKGC-------TCLGRGHGPGGWRPGPPPPPP
PG
*
>P1;VPX_SIVMAC

MSDPRERIPPGNSGEETIGEAFEWLNRTVE---EINREAVNHL-PRELIFQVWQRSWEYW
HD-EQGMSQSYTKYRYLCLIQKALFMHCKKGC-------RCLGEGHGAGGWRPGPPPPPP
PG
*
>P1;VPX_SIVAGM

MAEGRDSRERRPGWLEIWDLSREPWDELRDMVAELNQEAQRHF-GRELLFQVWNFCQEE-
GE-RNGAPMIERAYRYYRLVQKALFVHFRCGCRRRTPFEPYEERRNGVGGG-RDGRE-PP
PG
*
>P1;VPR_SIVMAC

MEER----PPENEGPQ-REPWDEWVVEVLK---ELKEEALKHFDPR-LLTALGNHIYNRH
GDTLEGAGE------LIRILQRALFIHFRSGC-------SHSRIGQPGGGNPLSTIPPSR
SM
*
>P1;VPR_HIV-2

MAEAPTELPPVDGTPL-REPGDEWIIEILR---EIKEEALKHFDPR-LLIALGKYIYTRH
GDTLEGARE------LIKVLQRALFTHFRAGC-------GHSRIGQTRGGNPLSAIPTPR
NM
*
>P1;VPR_HIV-1

MEQN-----PENQGPQ-RDNG--WTLELLE---ELKNEAVRHF-PRPWLHGLGQYIYTTY
GDTWEGVEA------IIRILQQLLFVHFRIGC-------QHSRIGIFPGRRGRNGAGRS-
--
*
>P1;VPR_SIVMND

MGQKRDEQVSEDQGPP-REPYNQWLADTME---EIKEEARKHF-PLIILNAVSEYCVQNT
GSEEEACEK------FITLMNRAIWVHLAQGC-------DGTFRERRPQLPPSGFRPRGD
RL
*
