>P1;HIV-2

MTDPRETVPPGNSGEETIGEAFAWLNRTVE---AINREAVNHLPRELIFQVWQRSWRYWH
DEQGMSESYTKYRYLCIIQKAVYMHVRKGC-------TCLGRGHGPGGWRPGPPPPPPPG
*
>P1;SIVMAC

MSDPRERIPPGNSGEETIGEAFEWLNRTVE---EINREAVNHLPRELIFQVWQRSWEYWH
DEQGMSQSYTKYRYLCLIQKALFMHCKKGC-------RCLGEGHGAGGWRPGPPPPPPPG
*
>P1;SIVAGM

MAEGRDSRERRPGWLEIWDLSREPWDELRDMVAELNQEAQRHFGRELLFQVWNFCQEE-G
ERNGAPMIERAYRYYRLVQKALFVHFRCGCRRRTPFEPYEERRNGVGGGRD-GRE-PPPG
*
