#!/usr/bin/perl
# Don't know what this is quite yet
# Take from
# http://nucleus.cshl.org/agsa/presentations.html

my $count = 0;

while (<>) {
	if ($count > 1) {
		my @f = split(' ');

		my $score   = $f[0];
		my $seqname = $f[4];

		my $start   = $f[5];
		my $end     = $f[6];

		my $family = $f[10];

		my $hstart;
		my $hend;
		my $hstrand;

		if ($f[8] eq '+') {
			$hstrand = "+";
			$hstart = $f[11];
			$hend   = $f[12];
		} elsif ($f[8] eq 'C') {
			$hstrand = "-";
			$hstart  = $f[13];
			$hend    = $f[12];
		}

		my $hid = $f[9];

		if ($hstart > $hend) {
			my $tmp = $hstart;
			$hstart = $hend;
			$hend   = $tmp;
		}

		print "$seqname\t$family\trepeat\t$start\t$end\t$score\t$hstrand\t.\t$hid\t$hstart\t$hend\n";

	}
	$count++;
}
		
			
